crates/cli/src/commands/project.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/snapshots/moon_cli__commands__project__tests__advanced_config.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project__tests__basic_config.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project__tests__depends_on_paths.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project__tests__empty_config.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project__tests__no_config.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project__tests__with_tasks.snap
crates/project/src/project.rs
crates/project/src/project_graph.rs
crates/project/tests/project_test.rs
crates/toolchain/src/toolchain.rs
crates/toolchain/src/tools/npm.rs
crates/toolchain/src/tools/pnpm.rs
crates/toolchain/src/tools/yarn.rs
crates/workspace/src/workspace.rs

I found it too confusing, as I always think of things in root verbiage.

fix: Rename `dir` to `root`.

---

crates/config/src/project/global.rs
crates/config/src/project/mod.rs
crates/project/src/errors.rs
crates/project/src/file_group.rs
crates/project/src/project.rs
crates/project/src/task.rs
crates/project/src/test.rs
crates/project/src/token.rs
crates/project/tests/project_test.rs
crates/utils/src/fs.rs

For the "run from workspace root" option to work correctly, I need everything to be `PathBuf`s instead of strings.

fix: Improve token paths.

---

Cargo.lock

deps: Upgrade to latest.

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/commands/project_graph.rs
crates/cli/src/commands/snapshots/moon_cli__commands__project_graph__tests__many_projects.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project_graph__tests__no_projects.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project_graph__tests__single_project_no_dependencies.snap
crates/cli/src/commands/snapshots/moon_cli__commands__project_graph__tests__single_project_with_dependencies.snap
crates/project/Cargo.toml
crates/project/src/constants.rs
crates/project/src/project.rs
crates/project/src/project_graph.rs
crates/workspace/src/dep_graph.rs

- Reworked to use petgraph under the hood.
- Switched from `RefCell<>` to `Arc<RwLock<>>`.

new: Update `ProjectGraph` to be `Sync` compatible.

---

crates/toolchain/src/helpers.rs
crates/toolchain/src/tools/npm.rs
crates/toolchain/src/tools/pnpm.rs
crates/toolchain/src/tools/yarn.rs
crates/utils/src/lib.rs
crates/utils/src/process.rs
crates/workspace/src/jobs/run_target.rs
crates/workspace/src/vcs/git.rs
crates/workspace/src/vcs/svn.rs

Just some organization cleanup.

fix: Move process utils to a subscope.

---

crates/cache/src/engine.rs
crates/cache/src/items.rs
crates/cache/src/lib.rs
crates/cache/src/runfiles.rs
crates/cli/src/commands/run.rs
crates/utils/src/process.rs
crates/workspace/src/task_runner.rs
crates/workspace/src/tasks/run_target.rs
packages/runtime/src/context.ts

new: Set env vars when running tasks.

---

Cargo.lock
crates/cache/Cargo.toml
crates/cache/src/engine.rs
crates/cache/src/items.rs
crates/cache/src/runfiles.rs
crates/cli/Cargo.toml
crates/cli/src/commands/bin.rs
crates/cli/src/commands/project.rs
crates/cli/src/commands/project_graph.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/setup.rs
crates/cli/src/commands/teardown.rs
crates/toolchain/Cargo.toml
crates/utils/Cargo.toml
crates/utils/src/fs.rs
crates/workspace/Cargo.toml
crates/workspace/src/workspace.rs

Will start applying async in other places.

new: Make cache engine fully async.

---

Cargo.lock
crates/cli/src/commands/setup.rs
crates/config/Cargo.toml
crates/config/src/package.rs
crates/config/src/tsconfig.rs
crates/error/src/lib.rs
crates/project/Cargo.toml
crates/project/src/project.rs
crates/project/tests/project_test.rs
crates/toolchain/src/toolchain.rs
crates/utils/src/fs.rs
crates/workspace/src/tasks/setup_toolchain.rs
crates/workspace/src/tasks/sync_project.rs
crates/workspace/src/workspace.rs

Had to move stuff to methods, but its fine.

new: Make package/tsconfig async.

---

Cargo.lock
crates/cache/src/items.rs
crates/cache/src/runfiles.rs
crates/config/Cargo.toml
crates/config/src/package.rs
crates/config/src/tsconfig.rs
crates/project/Cargo.toml
crates/utils/Cargo.toml
crates/utils/src/fs.rs

We should skip `None` values, and preserve order.

fix: Fix some JSON serialize issues.

---

crates/cli/src/app.rs
crates/cli/src/commands/run.rs
crates/cli/src/main.rs
crates/workspace/src/task_runner.rs
crates/workspace/src/tasks/run_target.rs

You can now do `moon run runtime:build runtime:typecheck`.

new: Allow multiple targets to be ran.

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/app.rs

This includes many changes.
I'm also trying to enable headings for commands/options.

deps: Upgrade to clap v3.1.

---

crates/cli/src/app.rs
crates/cli/src/commands/run.rs
crates/cli/src/lib.rs
crates/error/src/lib.rs
crates/utils/src/process.rs
crates/workspace/src/vcs/git.rs
crates/workspace/src/vcs/mod.rs
crates/workspace/src/vcs/svn.rs
crates/workspace/src/workspace.rs

new: Detect affected changes between branches.

---

.moon/workspace.yml
crates/config/src/workspace/mod.rs
crates/config/src/workspace/node.rs
crates/toolchain/src/helpers.rs
crates/toolchain/src/tools/npm.rs
docs/workspace.md

Implements https://github.com/milesj/moon/issues/60

new: Add env vars for overriding toolchain versions.

---

crates/config/src/tsconfig.rs
crates/config/src/workspace/mod.rs
crates/config/src/workspace/node.rs
crates/config/src/workspace/typescript.rs
crates/config/templates/project.yml
crates/config/templates/workspace.yml
crates/project/src/errors.rs
crates/project/src/project.rs
crates/workspace/src/tasks/sync_project.rs
crates/workspace/src/workspace.rs
docs/project.md
docs/roadmap.md
docs/workspace.md

Provide a little more control.

new: Add `typescript` config settings.

---

.github/workflows/rust.yml

It's possible for this to report different results.

ci: Enable linting on Windows.

---

crates/cli/src/commands/ci.rs
crates/project/src/project_graph.rs
crates/workspace/src/dep_graph.rs

Noticed this while testing CI.

fix: Touching global config files should affect all projects.

---

Cargo.lock
crates/cli/src/commands/project.rs
crates/config/src/project/global.rs
crates/config/src/project/mod.rs
crates/config/src/project/task.rs
crates/config/src/workspace/mod.rs
crates/config/src/workspace/node.rs
crates/config/src/workspace/typescript.rs
crates/config/src/workspace/vcs.rs
crates/project/src/project.rs
crates/project/src/task.rs
crates/project/tests/project_test.rs
crates/toolchain/src/toolchain.rs
crates/toolchain/tests/node_test.rs
crates/toolchain/tests/npm_test.rs
crates/toolchain/tests/pnpm_test.rs
crates/toolchain/tests/toolchain_test.rs
crates/toolchain/tests/yarn_test.rs
crates/workspace/src/dep_graph.rs
crates/workspace/src/tasks/install_node_deps.rs
crates/workspace/src/tasks/sync_project.rs
crates/workspace/src/vcs/mod.rs

`Option` was causing a ton of problems, but it turns out I was actually using figment incorrectly. These should use serde defaults + no option.

fix: Improve config optional fields.

---

.gitattributes
.github/workflows/moon.yml
.github/workflows/node.yml
.github/workflows/rust.yml
.gitignore
Cargo.lock
crates/cli/src/commands/ci.rs
crates/logger/src/color.rs
crates/project/src/project.rs
crates/project/src/task.rs
crates/project/src/token.rs
crates/toolchain/Cargo.toml
crates/toolchain/src/helpers.rs
crates/toolchain/src/tools/node.rs
crates/toolchain/src/tools/npm.rs
crates/toolchain/src/tools/pnpm.rs
crates/toolchain/src/tools/yarn.rs
crates/toolchain/tests/npm_test.rs
crates/toolchain/tests/pnpm_test.rs
crates/toolchain/tests/yarn_test.rs
crates/utils/src/fs.rs
crates/utils/src/process.rs
crates/workspace/src/errors.rs
crates/workspace/src/tasks/run_target.rs
crates/workspace/src/workspace.rs
packages/runtime/src/context.ts
rustfmt.toml

new: Support unpacking zip archives, and fix npm binary issues.

---

.moon/project.yml
.moon/workspace.yml
Cargo.lock
Cargo.toml
Makefile.toml
crates/config/Cargo.toml
crates/config/src/main.rs
crates/config/src/project/global.rs
crates/config/src/project/mod.rs
crates/config/src/project/task.rs
crates/config/src/workspace/mod.rs
crates/config/src/workspace/node.rs
crates/config/src/workspace/typescript.rs
crates/config/src/workspace/vcs.rs
crates/config/templates/global_project.yml
crates/config/templates/project.yml
crates/config/templates/workspace.yml
crates/project/tests/project_test.rs
schemas/global-project.json
schemas/project.json
schemas/workspace.json

Some tooling supports this, so why not.

new: Generate JSON schemas for YAML configs.

---

.github/workflows/release.yml
Cargo.toml
scripts/buildBinary.mjs
scripts/publishPackages.sh
scripts/syncArtifacts.mjs

Streamline this process and test npm publish.

build: Fix release workflow.

---

.github/workflows/moon.yml
.github/workflows/node.yml
.github/workflows/release-npm.yml
.github/workflows/release.yml
.github/workflows/rust.yml

ci: Rework Cargo and Yarn caching.

---

crates/toolchain/src/helpers.rs
crates/toolchain/src/tool.rs
crates/toolchain/src/tools/node.rs
crates/toolchain/src/tools/npm.rs
crates/toolchain/src/tools/pnpm.rs
crates/toolchain/src/tools/yarn.rs
crates/utils/src/process.rs
crates/workspace/src/actions/run_target.rs
crates/workspace/src/vcs/git.rs
crates/workspace/src/vcs/svn.rs

new: Wrap process utils into a `Command` struct.

---

.github/workflows/moon-stub.yml
.github/workflows/moon.yml
.github/workflows/rust-stub.yml
.github/workflows/rust.yml
packages/cli/README.md

This should stop running rust/moon workflows so much.

Only run workflows if specific files change.

---

.yarn/versions/10d52316.yml
.yarnrc.yml
crates/config/templates/global_project.yml
crates/config/templates/workspace.yml
packages/cli/CHANGELOG.md
website/static/schemas/global-project.json
website/static/schemas/project.json
website/static/schemas/workspace.json

fix: Fix template whitespace and comments.

---

.github/workflows/pr.yml
.github/workflows/release.yml
.yarn/versions/758f5743.yml
packages/cli/moon
packages/cli/postinstall.js
scripts/checks/cliBinary.sh

We are inadvertently publishing the 50mb binary within the `cli` package. This fixes it.

build: Fix release scripts.

---

.github/workflows/release.yml
.yarn/versions/0664589e.yml
README.md
ROADMAP.md
crates/lang-node/src/node.rs
crates/toolchain/tests/node_test.rs
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core-linux-x64-gnu/package.json
packages/core-macos-arm64/README.md
packages/core-macos-arm64/package.json
packages/core-macos-x64/package.json
scripts/helpers.mjs
scripts/release/testBinary.mjs
website/docs/install.mdx
website/docs/intro.mdx
website/src/pages/index.tsx
yarn.lock

This will support the new macOS M1 machines.

new: Support `aarch64-apple-darwin` target.

---

.cargo/config.toml
.github/workflows/rust-stub.yml
.github/workflows/rust.yml
CONTRIBUTING.md
ROADMAP.md
crates/cli/src/main.rs

I'm worried this won't be that accurate since a lot of our tests are running the moon binary as a child process...

ci: Integrate code coverage reports.

---

README.md

Sorry, saw it real quick haha.

README typo. :)

---

.github/workflows/rust.yml
Makefile.toml

I'm not sure why this stopped working.

ci: Fix code coverage failing to upload.

---

Cargo.lock

The biggest change is tokio v1.19. https://github.com/tokio-rs/tokio/releases/tag/tokio-1.19.0

deps: Update Cargo deps.

---

crates/cli/src/commands/project.rs
crates/cli/tests/snapshots/project_test__advanced_config.snap
crates/cli/tests/snapshots/project_test__basic_config.snap
crates/cli/tests/snapshots/project_test__depends_on_paths.snap
crates/cli/tests/snapshots/project_test__empty_config.snap
crates/cli/tests/snapshots/project_test__with_tasks.snap
crates/config/src/lib.rs
crates/config/src/project/mod.rs
crates/project/tests/project_test.rs
packages/cli/CHANGELOG.md
tests/fixtures/projects/basic/project.yml
website/docs/config/project.mdx
website/docs/create-project.mdx
website/docs/intro.mdx
website/static/schemas/project.json

Another field useful for metrics.

new: Add a `language` setting to `project.yml`.

---

.yarn/versions/a679620e.yml
crates/cli/src/commands/init.rs
crates/cli/tests/init_test.rs
crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nodenv.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nvm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn_from_package.snap
crates/config/templates/global_project.yml
crates/config/templates/project.yml
crates/config/templates/workspace.yml
crates/lang-node/src/lib.rs
crates/lang/src/lib.rs
packages/cli/CHANGELOG.md

The templating syntax was still being weird, so used snapshots to verify holistically.

fix: More fixes to config generation via templates.

---

.yarn/versions/b28493c5.yml
crates/utils/src/lib.rs
packages/cli/CHANGELOG.md

Noticed this act weird sometimes, so let's check more addresses.

fix: Improve offline detection by using Google's DNS.

---

.moon/workspace.yml
Cargo.lock
crates/cli/tests/run_test.rs
crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nodenv.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nvm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn_from_package.snap
crates/cli/tests/snapshots/run_test__general__logs_command_for_project_root.snap
crates/cli/tests/snapshots/run_test__general__logs_command_for_workspace_root.snap
crates/config/src/project/task.rs
crates/config/src/workspace/mod.rs
crates/config/templates/workspace.yml
crates/utils/Cargo.toml
crates/utils/src/process.rs
crates/workspace/src/actions/run_target.rs
packages/cli/CHANGELOG.md
tests/fixtures/cases/base/project.yml
website/docs/config/workspace.mdx
website/static/schemas/workspace.json

Nice to know exactly what's happening.

new: Log the task command when running a target.

---

.yarn/versions/3404e508.yml
ROADMAP.md
crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nodenv.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nvm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn_from_package.snap
crates/config/templates/workspace.yml
crates/workspace/src/dep_graph.rs
scripts/checks/cliBinary.sh
website/docs/run-task.mdx

Fix some typos

---

crates/utils/src/lib.rs
packages/cli/CHANGELOG.md

Stop gap for https://github.com/moonrepo/moon/issues/154

fix: Temporarily disable offline checks.

---

crates/utils/src/process.rs
crates/workspace/src/actions/run_target.rs
packages/cli/CHANGELOG.md

This helps to differentiate output in CI.

new: Prefix streamed output with the running target.

---

crates/cli/src/commands/ci.rs
crates/config/src/errors.rs
crates/config/src/package.rs
crates/config/src/tsconfig.rs
crates/logger/src/color.rs
crates/logger/src/logger.rs
crates/project/src/helpers.rs
crates/project/src/project_graph.rs
crates/project/src/token.rs
crates/terminal/src/terminal.rs
crates/toolchain/src/helpers.rs
crates/toolchain/src/tools/node.rs
crates/utils/src/fs.rs
crates/utils/src/glob.rs
crates/utils/src/path.rs
crates/utils/src/process.rs
crates/workspace/src/actions/install_node_deps.rs
crates/workspace/src/actions/run_target.rs
crates/workspace/src/dep_graph.rs
crates/workspace/src/vcs/git.rs
crates/workspace/src/vcs/svn.rs

Also defaults some unwraps to avoid crashing the app.
Implements https://github.com/moonrepo/moon/issues/147

new: Implement `#[track_caller]` for potential panics.

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/commands/init.rs
crates/cli/tests/init_test.rs
crates/config/templates/workspace.yml
crates/utils/src/test.rs
crates/vcs/src/lib.rs
packages/cli/CHANGELOG.md

new: Detect VCS settings during `moon init`.

---

website/docs/guides/examples/eslint.mdx
website/docs/guides/examples/jest.mdx
website/docs/guides/examples/packemon.mdx
website/docs/guides/examples/prettier.mdx
website/docs/guides/examples/react.mdx
website/docs/guides/examples/typescript.mdx
website/docs/guides/examples/vite.mdx
website/docs/guides/examples/vue.mdx
website/sidebars.js
website/src/components/AddDepsTabs.tsx
website/src/components/CreateDepTabs.tsx

These are being searched a bit on the website.

docs: Add guides for React, Vue, and Vite/Vitest.

---

crates/lang-node/src/node.rs
crates/toolchain/src/pms/npm.rs
crates/toolchain/src/pms/pnpm.rs
crates/toolchain/src/pms/yarn.rs
crates/toolchain/src/tools/node.rs
crates/utils/src/process.rs
crates/workspace/src/actions/run_target.rs
packages/cli/postinstall.js

Attempted fix for https://github.com/moonrepo/moon/issues/176

new: Fix global executable not working for PowerShell.

---

.github/workflows/moon.yml
crates/action-runner/src/actions/target/hasher.rs
crates/vcs/src/git.rs
packages/cli/CHANGELOG.md

Noticed our development PRs were pointing to master instead of the development branch.

ci: Use base/head from GH environment.

---

crates/action-runner/src/dep_graph.rs
crates/cli/src/commands/project.rs
crates/cli/src/queries/projects.rs
crates/cli/tests/snapshots/project_test__no_config.snap
crates/config/src/project/mod.rs
crates/project/src/project.rs
crates/project/src/test.rs
crates/project/src/token.rs
crates/project/tests/project_test.rs
packages/cli/CHANGELOG.md
website/docs/config/project.mdx

Only when the language is unknown (not configured).

new: Infer project `language` from local config files.

---

crates/action/src/context.rs
crates/action/src/install_node_deps.rs
crates/cli/src/commands/ci.rs
crates/cli/src/commands/run.rs
packages/cli/CHANGELOG.md

This will solve situations where `package.json` deps were modified manually.

new: Install Node.js deps when a `package.json` change is detected.

---

website/docs/config/project.mdx
website/docs/create-task.mdx
website/docs/faq.mdx
website/docs/guides/examples/vue.mdx
website/docs/install.mdx
website/docs/run-task.mdx
website/docs/terminology.md
website/sidebars.js

Will start documenting questions more.

docs: Add new FAQ page.

---

Cargo.lock
crates/action-runner/Cargo.toml
crates/action-runner/src/runner.rs
crates/action/src/install_node_deps.rs
crates/action/src/run_target.rs
crates/cli/src/app.rs
crates/cli/src/commands/bin.rs
crates/cli/src/commands/ci.rs
crates/cli/src/commands/mod.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/setup.rs
crates/cli/src/commands/sync.rs
crates/cli/src/commands/teardown.rs
crates/cli/src/lib.rs
crates/cli/tests/snapshots/sync_test__syncs_all_projects.snap
crates/cli/tests/sync_test.rs
crates/error/src/lib.rs
crates/terminal/src/lib.rs
packages/cli/CHANGELOG.md
tests/fixtures/project-graph/dependencies/.moon/workspace.yml
tests/fixtures/project-graph/dependencies/package.json
tests/fixtures/project-graph/dependents/.moon/workspace.yml
tests/fixtures/project-graph/dependents/package.json
website/docs/commands/bin.mdx
website/docs/commands/sync.mdx
website/sidebars.js

Provides a manually way to sync _all projects_ in the workspace.

new: Add `moon sync` command.

---

.github/workflows/rust-stub.yml
.github/workflows/rust.yml

This is adding like 10-20 minutes extra worth of CI time, and it's really kind of a hindrance.

ci: Only run coverage on master and develop branches.

---

crates/cli/src/app.rs
packages/cli/CHANGELOG.md
website/docs/commands/dep-graph.mdx
website/docs/commands/project-graph.mdx
website/docs/commands/project.mdx
website/docs/commands/run.mdx

Just some shortcuts that are useful.

new: Add command aliases.

---

crates/action/src/sync_node_project.rs
crates/cli/tests/bin_test.rs
crates/cli/tests/dep_graph_test.rs
crates/cli/tests/init_test.rs
crates/cli/tests/migrate_test.rs
crates/cli/tests/node_test.rs
crates/cli/tests/project_graph_test.rs
crates/cli/tests/project_test.rs
crates/cli/tests/query_test.rs
crates/cli/tests/run_node_test.rs
crates/cli/tests/run_test.rs
crates/cli/tests/setup_teardown_test.rs
crates/cli/tests/sync_test.rs
crates/utils/src/lib.rs
crates/utils/src/test.rs
crates/vcs/src/git.rs

Renames some stuff and avoids git usage when not necessary.

internal: Clean up fixtures.

---

crates/action/src/run_target.rs
crates/action/src/target/runner.rs
crates/cli/tests/dep_graph_test.rs
crates/cli/tests/run_test.rs
crates/config/src/project/global.rs
crates/config/src/project/task.rs
crates/project/tests/project_test.rs
crates/task/src/task.rs
packages/cli/CHANGELOG.md
tests/fixtures/cases/outputs/project.yml
website/docs/config/project.mdx

Allows the hashing/caching layer to be disabled.

new: Add a `cache` option to tasks.

---

crates/config/src/project/task.rs
crates/config/src/types.rs
crates/hasher/src/hasher.rs
crates/project/tests/project_test.rs
crates/task/src/task.rs
crates/task/src/token.rs
crates/task/src/types.rs
crates/task/tests/task_test.rs
crates/utils/src/regex.rs
packages/cli/CHANGELOG.md
website/docs/config/project.mdx
website/docs/config/workspace.mdx
website/docs/create-task.mdx

Simply prefix the var name with `$`.

new: Support environment variables within inputs.

---

website/docs/comparison.mdx
website/sidebars.js
website/src/components/ComparisonTable.tsx

This will mostly be a table right now.

docs: Add feature comparison with competitors.

---

.yarn/versions/152bf91c.yml
crates/cli/tests/dep_graph_test.rs
crates/cli/tests/project_test.rs
crates/cli/tests/run_test.rs
crates/cli/tests/snapshots/project_test__root_level.snap
crates/cli/tests/snapshots/run_test__caching__creates_run_state_cache.snap
crates/project/src/helpers.rs
tests/fixtures/cases/.moon/workspace.yml
tests/fixtures/cases/project.yml
website/docs/config/project.mdx
website/docs/faq.mdx
website/docs/guides/root-project.mdx
website/sidebars.js

Required some minor code tweaks unfortunately.

docs: Add guide on a root-level project.

---

Cargo.lock
crates/action/Cargo.toml
crates/action/src/install_node_deps.rs
crates/archive/src/zip.rs
crates/lang/src/lib.rs
packages/cli/CHANGELOG.md

This should reduce CI times by a couple of minutes.

new: Avoid double installing deps in CI.

---

crates/action-runner/src/dep_graph.rs
crates/cli/tests/dep_graph_test.rs
crates/cli/tests/run_test.rs
crates/cli/tests/snapshots/run_test__dependencies__can_run_deps_in_serial.snap
crates/config/src/project/task.rs
crates/project/tests/project_test.rs
crates/task/src/task.rs
packages/cli/CHANGELOG.md
tests/fixtures/cases/depends-on/moon.yml
website/docs/config/project.mdx

Allows tasks to also run deps in serial! Implements https://github.com/moonrepo/moon/issues/207

new: Add a `runDepsInParallel` option.

---

.github/workflows/moon.yml
.github/workflows/rust.yml
crates/cache/src/items.rs
crates/cli/src/enums.rs
crates/config/src/project/dep.rs
crates/config/src/project/global.rs
crates/config/src/project/mod.rs
crates/config/src/project/task.rs
crates/config/src/workspace/mod.rs
crates/config/src/workspace/node.rs
crates/config/src/workspace/typescript.rs
crates/config/src/workspace/vcs.rs
crates/lang-node/src/package.rs
crates/lang-node/src/tsconfig.rs
crates/task/src/file_group.rs
crates/task/src/task.rs
crates/task/src/token.rs
packages/cli/CHANGELOG.md
rust-toolchain.toml

Blog: https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html
Most of these changes don't affect us.

build: Update to Rust v1.63

---

packages/cli/CHANGELOG.md
website/docs/commands/dep-graph.mdx
website/docs/commands/query/projects.mdx
website/docs/commands/query/touched-files.mdx
website/docs/commands/sync.mdx
website/docs/concepts/token.mdx
website/docs/config/global-project.mdx
website/docs/config/project.mdx
website/docs/config/workspace.mdx
website/src/components/Docs/VersionLabel.tsx

Basically "this was released in x version" badges will help consumers.

docs: Add released in version badges.

---

crates/action/src/install_node_deps.rs
crates/action/src/target/node.rs
crates/lang-node/src/node.rs
crates/project/src/helpers.rs
crates/toolchain/src/pms/pnpm.rs
crates/toolchain/src/tools/node.rs
crates/utils/src/glob.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/261

fix: Add error handling to bin parsing.

---

.yarn/versions/80254232.yml
crates/task/src/task.rs
crates/task/tests/task_test.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/266

fix: When `envFile` is enabled, check for file existence in CI.

---

Cargo.lock
crates/action-runner/src/actions/run_target.rs
crates/action-runner/src/runner.rs
crates/action/Cargo.toml
crates/action/src/action.rs
crates/action/src/context.rs
crates/cache/Cargo.toml
crates/cache/src/engine.rs
crates/cache/src/items.rs
crates/cli/src/app.rs
crates/cli/src/commands/ci.rs
crates/cli/src/commands/clean.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/setup.rs
crates/cli/src/commands/sync.rs
crates/cli/src/commands/teardown.rs
crates/cli/src/helpers.rs
crates/cli/src/lib.rs
crates/cli/tests/dep_graph_test.rs
crates/cli/tests/run_test.rs
crates/utils/Cargo.toml
packages/cli/CHANGELOG.md
tests/fixtures/cases/base/moon.yml
website/docs/commands/run.mdx
website/src/components/ComparisonTable.tsx

This information will feed into other tooling.

new: Generate ci/run reports.

---

website/docusaurus.config.js
website/src/theme/Footer/Layout/ContactForm.tsx
website/src/theme/Footer/Layout/index.tsx

docs: Add an email contact form.

---

crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces.snap
crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces_expanded.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nodenv.snap
crates/cli/tests/snapshots/init_test__node__infers_version_from_nvm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm_from_package.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn.snap
crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn_from_package.snap
crates/config/templates/workspace.yml
packages/cli/CHANGELOG.md

These should of been `false` by default, not `true`.

fix: Fix default values in init templates.

---

website/docs/guides/examples/eslint.mdx

Add missing comma for ESLint integration doc

---

.moon/workspace.yml
crates/action-runner/src/actions/run_target.rs
crates/action-runner/src/runner.rs
crates/cli/tests/run_test.rs
crates/config/src/workspace/config.rs
crates/config/src/workspace/mod.rs
crates/config/src/workspace/runner.rs
crates/config/tests/workspace_test.rs
crates/project-graph/src/graph.rs
packages/cli/CHANGELOG.md
tests/fixtures/config-extends/workspace/base-0.yml
tests/fixtures/config-extends/workspace/base-1.yml
tests/fixtures/config-extends/workspace/base-2.yml
website/blog/2022-09-01_v0.13.md
website/docs/commands/overview.mdx
website/docs/config/workspace.mdx
website/static/schemas/workspace.json

This naming will align with future settings.

breaking: Rename `actionRunner` setting to `runner`.

---

Cargo.lock
crates/lang-node/Cargo.toml
crates/lang-node/src/npm.rs
crates/lang-node/src/pnpm.rs
crates/lang-node/src/yarn.rs
crates/lang-node/src/yarn_classic.rs

Adds more tests based on real-world upstream lockfiles. I want to ensure I'm catching all variations.

tests: Add more lockfile parsing tests.

---

crates/cli/src/app.rs
crates/cli/src/commands/check.rs
crates/cli/src/commands/mod.rs
crates/cli/src/commands/run.rs
crates/cli/src/lib.rs
crates/cli/tests/check_test.rs
crates/cli/tests/dep_graph_test.rs
crates/project-graph/Cargo.toml
crates/project-graph/src/graph.rs
crates/project/src/errors.rs
crates/project/src/project.rs
crates/task/src/task.rs
crates/task/src/test.rs
packages/types/src/project.ts
tests/fixtures/cases/base/moon.yml
website/blog/2022-09-01_v0.13.md
website/docs/commands/check.mdx
website/docs/concepts/task.mdx
website/docs/guides/examples/eslint.mdx
website/sidebars.js

This simplifies and speeds up the feedback loop of testing a project.

new: Add `moon check` command.

---

Cargo.lock
crates/cli/src/commands/generate.rs
crates/cli/tests/generate_test.rs
crates/cli/tests/snapshots/generate_test__interpolates_destination_path.snap
crates/cli/tests/snapshots/generate_test__overwrites_existing_files_when_interpolated_path.snap
crates/cli/tests/snapshots/generate_test__supports_custom_filters.snap
crates/generator/Cargo.toml
crates/generator/src/filters.rs
crates/generator/src/generator.rs
crates/generator/src/lib.rs
crates/generator/src/template.rs
tests/fixtures/generator/templates/vars/filters.txt
website/docs/commands/generate.mdx
website/docs/guides/codegen.mdx
website/docs/guides/profile.mdx
website/docs/guides/root-project.mdx
website/docusaurus.config.js
website/src/theme/prism-include-languages.js

Adds important casing filters and finalizes the docs.

new: Add custom template filters.

---

.github/workflows/rust.yml
Makefile.toml
crates/action-runner/src/actions/run_target.rs
crates/cli/src/commands/setup.rs
crates/cli/tests/snapshots/run_node_test__handles_process_exit_code_zero.snap
crates/cli/tests/snapshots/run_node_test__handles_process_exit_zero.snap
crates/cli/tests/snapshots/run_node_test__inherits_moon_env_vars.snap
crates/cli/tests/snapshots/run_node_test__runs_cjs_files.snap
crates/cli/tests/snapshots/run_node_test__runs_from_project_root.snap
crates/cli/tests/snapshots/run_node_test__runs_from_workspace_root.snap
crates/cli/tests/snapshots/run_node_test__runs_mjs_files.snap
crates/cli/tests/snapshots/run_node_test__runs_package_managers.snap
crates/cli/tests/snapshots/run_node_test__runs_standard_script.snap
crates/cli/tests/snapshots/run_node_test__sets_env_vars.snap
crates/cli/tests/snapshots/run_node_test__supports_top_level_await.snap
crates/utils/src/lib.rs
packages/cli/CHANGELOG.md
website/docs/guides/ci.mdx
website/docs/guides/docker.mdx
website/docs/guides/open-source.mdx
website/docusaurus.config.js
website/sidebars.js

This provides many benefits as described in the docs.

new: Disable caching in Docker containers.

---

.gitignore

If they shouldn't be committed, gitignore.

QOL: Add *.profraw to .gitignore

---

.github/workflows/rust.yml
crates/action-runner/src/dep_graph.rs
crates/action-runner/src/node.rs
crates/action-runner/src/runner.rs
crates/action-runner/tests/dep_graph_test.rs
crates/action-runner/tests/snapshots/dep_graph_test__run_target__avoids_dupe_targets.snap
crates/action-runner/tests/snapshots/dep_graph_test__run_target__deps_chain_target.snap
crates/action-runner/tests/snapshots/dep_graph_test__run_target__runs_all_projects_for_target_all_scope.snap
crates/action-runner/tests/snapshots/dep_graph_test__run_target__single_targets.snap
crates/action-runner/tests/snapshots/dep_graph_test__run_target_if_touched__skips_if_untouched_project.snap
crates/action-runner/tests/snapshots/dep_graph_test__run_target_if_touched__skips_if_untouched_task.snap
crates/action-runner/tests/snapshots/dep_graph_test__sync_project__avoids_dupe_projects.snap
crates/action-runner/tests/snapshots/dep_graph_test__sync_project__isolated_projects.snap
crates/action-runner/tests/snapshots/dep_graph_test__sync_project__projects_with_tasks.snap
crates/cli/src/commands/ci.rs
crates/cli/src/commands/dep_graph.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/setup.rs
crates/cli/src/commands/sync.rs
crates/cli/tests/snapshots/dep_graph_test__aliases__can_focus_using_an_alias.snap
crates/cli/tests/snapshots/dep_graph_test__aliases__resolves_aliases_in_task_deps.snap
crates/cli/tests/snapshots/dep_graph_test__focused_by_target.snap
crates/cli/tests/snapshots/dep_graph_test__includes_dependencies_when_focused.snap
crates/cli/tests/snapshots/dep_graph_test__includes_dependents_when_focused.snap
crates/contract/src/lib.rs
crates/platform-node/src/actions/setup_toolchain.rs
crates/project-graph/src/graph.rs

Updates the dependency graph and action runner to require an explicit version for tools. This is a stepping stone for supporting project-level versions.

new: Rework tools to require an explicit version within the action graph.

---

crates/cli/tests/snapshots/run_test__caching__uses_cache_on_subsequent_runs-2.snap
crates/cli/tests/snapshots/run_test__outputs__hydration__reuses_cache_from_previous_run-2.snap
crates/runner/src/runner.rs
crates/terminal/src/output.rs

Tried many options here, but nothing really looked good or rendered correctly. :[

new: Add ASCII art when run is fully cached.

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/main.rs
packages/cli/CHANGELOG.md

We should see reduced memory consumption and increased performance. https://github.com/microsoft/mimalloc
Too bad we don't have benchmarks currently.

new: Enable mimalloc as our memory allocator.

---

crates/config/src/main.rs
crates/config/src/project/task.rs
crates/config/src/project/task_options.rs
crates/config/src/template/config.rs
crates/config/src/template/frontmatter.rs
packages/cli/CHANGELOG.md
templates/crate/template.yml
tests/fixtures/generator/templates/extensions/template.yml
tests/fixtures/generator/templates/frontmatter/template.yml
tests/fixtures/generator/templates/standard/template.yml
tests/fixtures/generator/templates/vars/template.yml
website/static/schemas/template-frontmatter.json
website/static/schemas/template.json

Honestly, I forgot to do this when releasing the generator.

new: Add JSON schema support for `template.yml`.

---

website/src/theme/PaginatorNavLink.tsx

docs: Reduce size of paginator nav links.

---

Cargo.lock
crates/action/Cargo.toml
crates/archive/Cargo.toml
crates/cli/Cargo.toml
crates/cli/tests/bin_test.rs
crates/cli/tests/run_node_test.rs
crates/cli/tests/snapshots/run_test__configs__bubbles_up_invalid_global_project_config.snap
crates/cli/tests/snapshots/run_test__configs__bubbles_up_invalid_project_config.snap
crates/cli/tests/snapshots/run_test__configs__bubbles_up_invalid_workspace_config.snap
crates/cli/tests/utils.rs
crates/config/Cargo.toml
crates/config/src/project/global_config.rs
crates/config/src/project/local_config.rs
crates/config/src/providers/url.rs
crates/config/src/template/config.rs
crates/config/src/template/frontmatter.rs
crates/config/src/workspace/config.rs
crates/config/src/workspace/runner.rs
crates/config/tests/global_project_test.rs
crates/config/tests/local_project_test.rs
crates/config/tests/tasks_test.rs
crates/error/Cargo.toml
crates/generator/Cargo.toml
crates/lang-node/Cargo.toml
crates/task/Cargo.toml
crates/utils/Cargo.toml
packages/cli/CHANGELOG.md
website/blog/2022-10-06_v0.16.mdx
website/blog/2022-10-21_v0.17.mdx
website/docs/config/project.mdx

Implements https://github.com/moonrepo/moon/issues/164

new: Support YAML references.

---

.github/workflows/benchmark.yml
crates/emitter/Cargo.toml
crates/emitter/benches/emitter_benchmark.rs
crates/project-graph/Cargo.toml
crates/project-graph/benches/project_graph_benchmark.rs
crates/runner/Cargo.toml
crates/runner/benches/dep_graph_benchmark.rs
crates/runner/benches/runner_benchmark.rs
crates/runner/benches/utils.rs

Now that the other PR landed, we can create a "baseline".

build: Integrate benchmark workflow.

---

.github/workflows/benchmark.yml
crates/lang-node/src/node.rs
crates/lang/src/lib.rs
crates/project-graph/benches/project_graph_benchmark.rs
crates/terminal/src/helpers.rs
crates/terminal/src/output.rs
crates/utils/src/fs.rs
crates/utils/src/glob.rs
crates/utils/src/lib.rs
crates/utils/src/path.rs
crates/utils/src/process.rs
crates/utils/src/regex.rs
crates/utils/src/semver.rs
crates/utils/src/shell.rs
scripts/version/applyAndTagVersions.mjs

Implements https://github.com/moonrepo/moon/issues/144
I primarily enabled `#[inline]` for the utils crate, since its used everywhere.

perf: Enable Rust inlining.

---

.yarn/versions/4d057106.yml
crates/cli/src/app.rs
crates/cli/src/commands/check.rs
crates/cli/src/lib.rs
crates/cli/tests/check_test.rs
crates/project-graph/src/graph.rs

Add a `--all` flag for `check` subcommand

---

.github/workflows/benchmark.yml

The new output format didn't handle multiline strings very well.

build: Fix benchmark comments.

---

Cargo.lock
Cargo.toml
crates/cli/src/app.rs
crates/cli/tests/run_test.rs
crates/cli/tests/snapshots/project_test__root_level.snap
crates/cli/tests/snapshots/run_test__output_styles__hash.snap
crates/core/project/src/project.rs
crates/core/utils/Cargo.toml
crates/core/vcs/Cargo.toml
crates/core/vcs/src/git.rs
crates/core/vcs/src/svn.rs
crates/core/vcs/src/vcs.rs
crates/core/vcs/tests/git_test.rs
crates/node/lang/Cargo.toml
crates/typescript/lang/Cargo.toml
packages/cli/CHANGELOG.md
tests/fixtures/cases/.moon/workspace.yml
tests/fixtures/cases/files/moon.yml
tests/fixtures/cases/moon.yml

Investigation into https://github.com/moonrepo/moon/issues/414

internal: Clean up and test affected logic.

---

crates/core/runner/src/actions/run_target.rs
crates/core/vcs/src/git.rs
packages/cli/CHANGELOG.md
website/docs/install.mdx

Fixes https://github.com/moonrepo/moon/issues/426

fix: Fix git branch detection on old versions.

---

crates/cli/src/commands/generate.rs
crates/core/generator/src/template.rs
crates/core/utils/src/json.rs
crates/core/utils/src/yaml.rs
crates/core/utils/tests/json_test.rs
packages/cli/CHANGELOG.md
tests/fixtures/generator/templates/configs/file.json
tests/fixtures/generator/templates/configs/file.yaml
tests/fixtures/generator/templates/configs/template.yml
website/blog/2022-11-14_v0.19.mdx
website/src/components/ComparisonTable.tsx

If the generator encounters a JSON or YAML at the destination, prompt the user with the ability to merge the files.

new: Add a generator prompt for merging JSON/YAML files.

---

scripts/release/publishBinaryPackages.sh
scripts/release/publishPackages.sh
website/blog/2022-10-06_v0.16.mdx
website/docs/guides/codegen.mdx
website/docs/guides/profile.mdx
website/src/js/darkModeSyncer.ts
website/tailwind.config.js

Found via `codespell -S crates,.yarn,./yarn.lock -L crate,otification`

docs: fix typos

---

.github/workflows/moon.yml
.moon/workspace.yml

Testing that it actually works 👍

ci: Enable remote caching.

---

.cargo/nextest.toml
.github/workflows/rust.yml
CONTRIBUTING.md
Makefile.toml

This is almost 50% faster than `cargo test`.
https://nexte.st/index.html

tests: Migrate to nextest for faster tests.

---

crates/core/utils/src/yaml.rs
crates/core/utils/tests/snapshots/yaml_test__editor_config__can_change_space_indent.snap
crates/core/utils/tests/snapshots/yaml_test__editor_config__can_change_tab_indent.snap
crates/core/utils/tests/snapshots/yaml_test__editor_config__uses_defaults_when_no_config.snap
crates/core/utils/tests/yaml_test.rs
packages/cli/CHANGELOG.md
tests/fixtures/editor-config/file.yaml
website/docs/faq.mdx

new: Support `.editorconfig` for YAML files.

---

.yarn/versions/d52cf3ca.yml
crates/cli/src/commands/bin.rs
crates/cli/src/commands/ci.rs
crates/cli/src/commands/project.rs
crates/cli/src/main.rs
crates/core/lang/src/config.rs
crates/core/logger/src/logger.rs
crates/core/toolchain/src/manager.rs
crates/core/toolchain/src/tools/node.rs
crates/core/utils/src/process.rs
crates/core/utils/src/yaml.rs
crates/node/lang/src/pnpm/mod.rs
crates/node/platform/src/actions/run_target.rs
packages/cli/CHANGELOG.md

Wasn't expecting this case to be hit, but it was!

fix: Fix panics for non-installed tools.

---

crates/cli/tests/run_node_test.rs
crates/cli/tests/run_system_test.rs
crates/cli/tests/snapshots/run_system_test__unix__caching__creates_run_state_cache.snap
crates/core/runner/src/actions/run_target.rs
crates/node/platform/src/actions/install_deps.rs
packages/cli/CHANGELOG.md
tests/fixtures/node/base/moon.yml
tests/fixtures/system/unix/moon.yml
website/docs/config/project.mdx

Fixes some edge cases and improves the affected flow.

new: Add `MOON_AFFECTED_FILES` env var and improve flow.

---

crates/cli/src/commands/generate.rs
crates/cli/src/commands/run.rs
crates/core/generator/src/template.rs
crates/core/utils/src/json.rs
crates/core/utils/src/yaml.rs
crates/core/utils/tests/json_test.rs
packages/cli/CHANGELOG.md
tests/fixtures/generator/templates/configs/file.json
tests/fixtures/generator/templates/configs/file.yaml
tests/fixtures/generator/templates/configs/template.yml
website/src/components/ComparisonTable.tsx

This seems to have been completely lost during the 0.19 release...

internal: Re-implement generator file merging.

---

crates/cli/src/commands/generate.rs
crates/cli/tests/snapshots/generate_test__supports_custom_filters.snap
crates/core/generator/src/filters.rs
crates/core/generator/src/template.rs
packages/cli/CHANGELOG.md
tests/fixtures/generator/templates/vars/filters.txt
website/blog/2022-11-28_v0.20.mdx
website/docs/guides/codegen.mdx
website/docs/guides/remote-cache.mdx

We now provide `path_join` and `path_relative`.

new: Support path related filters in generator templates.

---

crates/core/toolchain/src/pms/pnpm.rs
crates/node/platform/src/actions/install_deps.rs
packages/cli/CHANGELOG.md

It seems to actually cause problems.

fix: Don't run `pnpm prune` when deduping.

---

.yarn/versions/15baeed3.yml
crates/core/config/src/workspace/vcs.rs
crates/core/generator/src/filters.rs
crates/core/pipeline-provider/src/aws_codebuild.rs
crates/core/vcs/src/git.rs
crates/core/vcs/src/lib.rs
crates/core/vcs/src/loader.rs
crates/core/vcs/src/svn.rs
crates/core/vcs/tests/git_test.rs
packages/cli/CHANGELOG.md
packages/types/src/workspace-config.ts
website/docs/config/workspace.mdx

Allows this list to be customized so that it's no longer hard-coded.

new: Add `vcs.remoteCandidates` setting.

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/app.rs
crates/cli/src/commands/ci.rs
crates/cli/src/commands/run.rs
crates/core/action/Cargo.toml
crates/core/action/src/lib.rs
crates/core/cache/Cargo.toml
crates/core/cache/src/lib.rs
crates/core/runner-context/Cargo.toml
crates/core/runner-context/src/lib.rs
crates/core/runner/Cargo.toml
crates/core/runner/benches/runner_benchmark.rs
crates/core/runner/src/actions/run_target.rs
crates/core/runner/src/actions/setup_toolchain.rs
crates/core/runner/src/lib.rs
crates/core/runner/src/run_report.rs
crates/core/runner/src/runner.rs
crates/core/task/src/target.rs
crates/node/platform/Cargo.toml
crates/node/platform/src/actions/install_deps.rs
crates/node/platform/src/actions/run_target.rs
crates/node/platform/src/actions/sync_project.rs
packages/types/src/runner.ts

This was growing larger than what the action crate was intended for.

internal: Move action context into a runner-context crate.

---

website/docs/comparison.mdx
website/docs/concepts/task.mdx
website/docs/concepts/toolchain.mdx
website/src/components/ComparisonColumn.tsx
website/src/components/ComparisonTable.tsx

Finally getting around to this.

docs: Add Turborepo comparison.

---

.yarn/versions/b5d4e7f0.yml
crates/cli/src/commands/ci.rs
crates/cli/src/commands/dep_graph.rs
crates/cli/src/commands/run.rs
crates/cli/tests/snapshots/run_test__outputs__hydration__reuses_cache_from_previous_run-2.snap
crates/core/runner-context/src/lib.rs
crates/core/runner/benches/utils.rs
crates/core/runner/src/actions/run_target.rs
crates/core/runner/src/dep_graph.rs
crates/core/runner/tests/dep_graph_test.rs
crates/node/platform/src/actions/install_deps.rs
packages/cli/CHANGELOG.md
packages/types/src/runner.ts

Fixes https://github.com/moonrepo/moon/issues/453

fix: Fix an issue when touching `package.json` wouldn't trigger a deps install.

---

.github/workflows/pr.yml
crates/cli/src/main.rs
website/static/install.ps1
website/static/install.sh

We can't rely on everyone installing moon with node/npm, so this adds installation scripts.

new: Add language agnostic installation scripts.

---

crates/core/toolchain/src/tools/pnpm.rs
crates/node/platform/src/actions/install_deps.rs
packages/cli/CHANGELOG.md

pnpm doesn't support this natively.

new: Use `pnpm-deduplicate` for pnpm deduping.

---

.github/workflows/benchmark.yml
.github/workflows/moon.yml
.github/workflows/rust.yml
Cargo.lock
crates/cli/src/commands/init/mod.rs
crates/core/config/src/project/global_config.rs
crates/core/config/src/toolchain/config.rs
crates/core/config/src/workspace/config.rs
crates/core/config/src/workspace/runner.rs
crates/core/config/tests/local_project_test.rs
crates/core/config/tests/tasks_test.rs
crates/core/config/tests/template_test.rs
crates/core/logger/src/color.rs
crates/core/logger/src/logger.rs
crates/core/moon/src/lib.rs
crates/core/project/tests/project_test.rs
crates/core/runner/src/actions/run_target.rs
crates/core/runner/src/runner.rs
crates/core/task/tests/token_test.rs
crates/core/utils/src/fs.rs
crates/core/utils/src/shell.rs
crates/core/workspace/src/workspace.rs
crates/node/lang/src/yarn/mod.rs
crates/node/platform/src/actions/install_deps.rs
crates/node/platform/src/actions/sync_project.rs
crates/typescript/lang/src/tsconfig.rs
packages/cli/CHANGELOG.md
rust-toolchain.toml
scripts/Dockerfile

https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html

deps: Upgrade to Rust v1.66

---

.yarn/versions/94193bd3.yml
Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/commands/graph/dep.rs
crates/cli/src/commands/graph/project.rs
crates/cli/src/commands/graph/utils.rs
packages/cli/CHANGELOG.md
packages/cli/postinstall.js
scripts/release/buildPackages.sh
website/docs/install.mdx
website/static/install.ps1
website/static/install.sh

A few issues that were caught after release.

fix: Version 0.21 release fixes.

---

crates/cli/src/app.rs
crates/cli/src/lib.rs
crates/cli/src/main.rs
packages/cli/CHANGELOG.md

internal: Include version and bin path in the logs.

---

crates/cli/src/app.rs
crates/cli/src/commands/graph/dep.rs
crates/cli/src/commands/graph/project.rs
crates/cli/src/lib.rs
crates/cli/tests/dep_graph_test.rs
crates/cli/tests/project_graph_test.rs
crates/cli/tests/snapshots/dep_graph_test__outputs_json.snap
crates/cli/tests/snapshots/project_graph_test__outputs_json.snap
packages/cli/CHANGELOG.md

This is required for the VSC extension.

new: Add `--json` flag for graph commands.

---

.yarn/versions/c8c64028.yml
crates/core/config/src/project/language_platform.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/task/src/task.rs
packages/cli/CHANGELOG.md
tests/fixtures/task-inheritance/platform-detect-lang/moon.yml
tests/fixtures/task-inheritance/platform-detect/moon.yml

fix: Fix task platform inheritance merging.

---

crates/cli/src/app.rs
packages/cli/CHANGELOG.md
website/docs/commands/overview.mdx
website/docs/setup-toolchain.mdx

Didn't realize clap supported this!

new: Allow global args to be passed anywhere in the command line.

---

crates/cli/src/app.rs
crates/cli/src/commands/check.rs
crates/cli/src/commands/ci.rs
crates/cli/src/commands/run.rs
crates/cli/src/lib.rs
crates/core/action-pipeline/src/pipeline.rs
packages/cli/CHANGELOG.md
website/docs/commands/overview.mdx

Implements https://github.com/moonrepo/moon/issues/477

new: Add global `--concurrency` option.

---

website/blog/2023-01-04_2023-roadmap.mdx
website/package.json
yarn.lock

docs: Add 2023 blog post.

---

website/blog/2023-01-04_2023-roadmap.mdx

docs: Add more to 2023 blog post.

---

crates/cli/src/app.rs
crates/cli/src/commands/run.rs
crates/cli/src/lib.rs
crates/cli/src/queries/touched_files.rs
crates/core/vcs/src/vcs.rs
packages/cli/CHANGELOG.md
scripts/release-workflow.md
website/blog/2023-01-17_v0.22.mdx
website/docs/commands/query/touched-files.mdx
website/docs/commands/run.mdx
website/docs/run-task.mdx

Using git verbiage here as it makes more sense.

breaking: Rename `--upstream` to `--remote`.

---

website/docs/guides/examples/storybook.mdx
website/sidebars.js

Add documentation on setting up and using Storybook with Moon 
Closes #539

new: Add Storybook support

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/lib.rs
crates/core/launchpad/Cargo.toml
crates/core/launchpad/src/lib.rs

Check if there's a new version of moon

Check for a new version on launch in the background

---

Cargo.lock
crates/core/tool/Cargo.toml
crates/core/tool/src/errors.rs
crates/node/platform/Cargo.toml
crates/node/platform/src/actions/run_target.rs
crates/node/platform/src/platform.rs
crates/node/tool/Cargo.toml
crates/node/tool/src/node_tool.rs
crates/node/tool/src/npm_tool.rs
crates/node/tool/src/pnpm_tool.rs
crates/node/tool/src/yarn_tool.rs
crates/proto/cli/Cargo.toml
crates/proto/cli/src/bin.rs
crates/proto/cli/src/commands/list.rs
crates/proto/cli/src/commands/list_remote.rs
crates/proto/cli/src/commands/mod.rs
crates/proto/cli/src/lib.rs

new: Add `proto list` and `proto list-remote`.

---

crates/proto/core/src/shimmer.rs
crates/proto/core/templates/bash_global.tpl
crates/proto/core/templates/batch_global.tpl
crates/proto/node/src/depman/shim.rs
crates/proto/node/src/shim.rs
crates/proto/node/tests/node_depman_test.rs
crates/proto/node/tests/node_test.rs

These will be used in the future to intercept commands.

new: Create global proto shims.

---

crates/cli/tests/dep_graph_test.rs
crates/core/config/src/project/config.rs
crates/core/config/src/project/mod.rs
crates/core/project-graph/src/project_builder.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/test-utils/src/configs.rs
packages/types/src/project-config.ts
tests/fixtures/tasks/expand-env-project/.env
tests/fixtures/tasks/expand-env-project/moon.yml
website/blog/2023-01-30_v0.23.mdx
website/docs/concepts/task.mdx
website/docs/config/project.mdx

Implements https://github.com/moonrepo/moon/issues/489

new: Add project-level `env` setting to `moon.yml`.

---

crates/core/utils/src/json.rs
crates/node/platform/src/actions/sync_project.rs
crates/node/platform/tests/sync_project_test.rs
crates/typescript/lang/src/tsconfig.rs
packages/cli/CHANGELOG.md
tests/fixtures/base/tsconfig-json/a/tsconfig.json
tests/fixtures/base/tsconfig-json/b/tsconfig.json
tests/fixtures/base/tsconfig-json/tsconfig.multi-inherits.json

Basically supporting all the new compiler options: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/

new: Add TypeScript 5 support.

---

website/docs/guides/examples/sveltekit.mdx
website/sidebars.js

Adds a SvelteKit guide to the documentation
Closes #543

Sveltekit guide

---

crates/core/config/src/project/config.rs
crates/core/project-graph/src/project_builder.rs
crates/core/project-graph/tests/projects_test.rs
packages/cli/CHANGELOG.md
packages/types/src/project-config.ts
tests/fixtures/project-graph/langs/project-platform/moon.yml
website/blog/2023-02-13_v0.24.mdx
website/docs/concepts/task.mdx
website/docs/config/project.mdx
website/docs/faq.mdx
website/static/schemas/project.json

This was rather easy to support.

new: Add `platform` setting to `moon.yml`.

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/app.rs
crates/cli/src/commands/completions.rs
crates/cli/src/commands/mod.rs
crates/cli/src/lib.rs
crates/proto/cli/Cargo.toml
crates/proto/cli/src/app.rs
crates/proto/cli/src/bin.rs
crates/proto/cli/src/commands/completions.rs
crates/proto/cli/src/commands/mod.rs
crates/proto/error/src/lib.rs
packages/cli/CHANGELOG.md
website/blog/2023-02-13_v0.24.mdx
website/docs/commands/completions.mdx
website/sidebars.js

Via the new `moon completions` command.

new: Support shell auto-completion.

---

crates/cli/src/commands/migrate/from_package_json.rs
crates/core/lang/src/config.rs
crates/node/platform/src/actions/install_deps.rs
crates/node/platform/src/actions/sync_project.rs
crates/typescript/lang/src/tsconfig.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/607

fix: Fix writing to config files unnecessarily.

---

crates/cli/tests/dep_graph_test.rs
crates/core/project-graph/src/errors.rs
crates/core/project-graph/src/token_resolver.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/project-graph/tests/token_resolver_test.rs
crates/core/project/src/project.rs
packages/cli/CHANGELOG.md
tests/fixtures/tasks/tokens/moon.yml
website/blog/2023-02-13_v0.24.mdx
website/docs/concepts/token.mdx

Implements https://github.com/moonrepo/moon/issues/401

new: Support token functions in task `output`s.

---

.yarn/versions/a8f26b69.yml
crates/core/action-pipeline/src/estimator.rs
crates/core/action-pipeline/src/lib.rs
crates/core/action-pipeline/src/pipeline.rs
crates/core/action-pipeline/tests/estimator_test.rs
crates/core/action/src/action.rs
packages/cli/CHANGELOG.md
packages/report/tests/report.test.ts
packages/types/src/pipeline.ts

Noticed some buginess while testing this.

fix: Improve estimate calculation.

---

crates/cli/src/commands/bin.rs
crates/cli/tests/bin_test.rs
packages/cli/CHANGELOG.md

It requires the toolchain, but we forgot to load the toolchain...

fix: Fix `moon bin` command failing.

---

website/docs/__partials__/node/package-workspaces.mdx
website/docs/guides/examples/sveltekit.mdx
website/docs/guides/javascript/__partials__/workspace-commands.mdx
website/docs/guides/javascript/node-handbook.mdx
website/docs/setup-toolchain.mdx
website/sidebars.js

docs: Add Node.js handbook.

---

crates/core/project-graph/src/project_builder.rs
packages/cli/CHANGELOG.md

Causes too many issues at the moment: https://github.com/moonrepo/moon/issues/637

fix: Remove caching for project globbing.

---

.yarn/versions/3554d34c.yml
crates/cli/src/lib.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/655

fix: Defer version check till after a command has ran.

---

crates/cli/src/commands/init/mod.rs
crates/core/launchpad/src/lib.rs

Hopefully we can get some feedback on why people stop using moon.

internal: Add survey link to init flow.

---

.yarn/versions/136f481a.yml
Cargo.lock
Cargo.toml
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/660
Previously the timeout was 3 seconds, which I believe is the 6 second delay in the issue above. I dropped the timeout to 1 second.

fix: Reduce offline check timeout.

---

crates/cli/src/app.rs
crates/cli/src/commands/docker/mod.rs
crates/cli/src/commands/docker/setup.rs
crates/cli/src/lib.rs
crates/cli/tests/docker_test.rs
crates/core/dep-graph/src/dep_builder.rs
packages/cli/CHANGELOG.md
website/blog/2023-03-13_v0.26.mdx
website/docs/commands/docker/scaffold.mdx
website/docs/commands/docker/setup.mdx
website/docs/guides/docker.mdx
website/sidebars.js

Fixes https://github.com/moonrepo/moon/issues/625

new: Add `moon docker setup` command.

---

.github/workflows/pr.yml
website/static/install/proto.ps1
website/static/install/proto.sh

Had to debug this on my desktop PC.

internal: Fix Windows proto installer.

---

crates/core/runner/src/inputs_collector.rs
packages/cli/CHANGELOG.md

CI environments may create files that wouldnt exist locally, but `git status` would pull them into the hashing layer, causing unexpected issues.
For example, pnpm creates a `.pnpm-store` directory that causes hashing to hang.
```
[debug 18:45:51] moon:action:run-target Running target api:emit-types
[trace 18:45:51] moon:utils:process Running command git ls-files --cached --modified --others --full-name --exclude-standard apps/api (in /opt/atlassian/pipelines/agent/build)
[trace 18:45:51] moon:action-pipeline:batch:3:2 Processing action SyncNodeProject(client)
[trace 18:45:51] moon:utils:process Running command git hash-object --stdin-paths - apps/api/.env.example apps/api/.env.pipeline apps/api/.eslintrc.cjs apps/api/.gitignore apps/api/config/admin.ts apps/api/config/api.ts …
```

fix: Don't hash local touched files in CI.

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
packages/cli/CHANGELOG.md
scripts/Dockerfile

Noticed these crashing with ssl problems...

ci: Fix release build workflow.

---

.yarn/versions/93ac8dff.yml
crates/cli/src/commands/docker/mod.rs
crates/cli/src/commands/docker/prune.rs
crates/cli/src/commands/docker/scaffold.rs
crates/cli/src/commands/docker/setup.rs
crates/cli/tests/docker_test.rs
packages/cli/CHANGELOG.md

fix: Fix Docker manifest missing for staged builds.

---

crates/core/cache/src/engine.rs
crates/core/config/src/project/config.rs
crates/core/config/src/template/config.rs
crates/core/project-graph/src/helpers.rs
crates/core/project-graph/src/project_builder.rs
crates/core/project-graph/src/token_resolver.rs
crates/core/project-graph/tests/project_graph_test.rs
crates/core/project-graph/tests/token_resolver_test.rs
crates/core/runner/src/inputs_collector.rs
crates/core/task/src/file_group.rs
crates/core/task/tests/file_group_test.rs
crates/core/utils/src/glob.rs
crates/node/platform/src/platform.rs

Debugging some inconsistencies...

fix: Fix project sources and globs using incorrect slashes on Windows.

---

.yarn/versions/ee8bc2a6.yml
package.json
packages/visualizer/package.json
website/docs/concepts/toolchain.mdx
website/docs/setup-toolchain.mdx
yarn.lock

The toolchain was changed quite a bit since this was originally written, so this updates to the latest functionality.

docs: Rewrite setup toolchain article.

---

.github/workflows/pr.yml
website/static/install.ps1
website/static/install.sh
website/static/install/proto.ps1
website/static/install/proto.sh

Fixes https://github.com/moonrepo/proto/issues/43

fix: Fix proto Windows installer not always working.

---

crates/core/project-graph/src/token_resolver.rs
crates/core/project-graph/tests/token_resolver_test.rs
crates/core/utils/src/regex.rs
packages/cli/CHANGELOG.md
website/blog/2023-03-27_moon-v1.0.mdx
website/docs/concepts/token.mdx

Implements https://github.com/moonrepo/moon/issues/705

new: Add date/time token variables.

---

.yarn/versions/58d5cfed.yml
crates/cli/src/app.rs
crates/cli/src/commands/project.rs
crates/cli/src/lib.rs
crates/cli/src/queries/projects.rs
crates/cli/tests/query_test.rs
crates/cli/tests/snapshots/project_test__advanced_config.snap
crates/cli/tests/snapshots/project_test__basic_config.snap
crates/cli/tests/snapshots/project_test__depends_on_paths.snap
crates/core/config/src/project/config.rs
crates/core/config/tests/project_test.rs
crates/core/project/tests/project_test.rs
packages/cli/CHANGELOG.md
packages/types/src/project-config.ts
tests/fixtures/projects/advanced/moon.yml
tests/fixtures/projects/basic/moon.yml
tests/fixtures/projects/deps/foo/moon.yml
website/blog/2023-03-27_moon-v1.0.mdx
website/docs/commands/query/projects.mdx
website/docs/config/project.mdx

This PR adds tagging to projects via the `tags` setting. This is the first PR of many that will integrate new features built around tagging, with the first being querying.
Related to: https://github.com/moonrepo/moon/issues/583

new: Add project tagging system. Integrate querying.

---

.yarn/versions/55d37ffc.yml
crates/cli/src/main.rs
crates/cli/tests/run_system_test.rs
crates/cli/tests/snapshots/run_system_test__unix__handles_process_exit_nonzero_inline.snap
packages/cli/CHANGELOG.md
tests/fixtures/system/unix/moon.yml

Fixes https://github.com/moonrepo/moon/issues/720

fix: Fix global binary exit code not propagating.

---

crates/cli/tests/run_typescript_test.rs
crates/cli/tests/snapshots/run_typescript_test__refs__doesnt_sync_root_project.snap
crates/cli/tests/snapshots/run_typescript_test__refs__doesnt_sync_root_project.snap.new
crates/cli/tests/snapshots/run_typescript_test__refs__syncs_root_project_if_root_config_custom_name.snap
crates/core/test-utils/src/configs.rs
crates/typescript/platform/src/sync_project.rs
packages/cli/CHANGELOG.md
tests/fixtures/typescript/moon.yml
website/docs/config/toolchain.mdx

Fixes https://github.com/moonrepo/moon/issues/723

fix: Fix root project syncing to root `tsconfig.json`.

---

crates/core/config/src/workspace/hasher.rs
crates/core/runner/src/inputs_collector.rs
crates/core/runner/src/runner.rs
crates/core/runner/tests/inputs_collector_test.rs
packages/cli/CHANGELOG.md
packages/types/src/workspace-config.ts
website/blog/2023-03-27_moon-v1.0.mdx
website/docs/config/workspace.mdx
website/static/schemas/project.json
website/static/schemas/workspace.json

The warnings currently can get pretty spammy, so this adds a setting to control it.

new: Add `hasher.warnOnMissingInputs` setting to `.moon/workspace.yml`.

---

crates/cli/src/queries/touched_files.rs
crates/cli/tests/snapshots/run_system_test__unix__passes_args_through.snap
crates/cli/tests/snapshots/run_system_test__windows__passes_args_through.snap
crates/core/config/src/project/language_platform.rs
crates/core/config/src/project/task_options.rs
crates/core/dep-graph/src/dep_builder.rs
crates/core/runner/src/runner.rs
crates/core/task/src/task_options.rs
crates/core/task/tests/task_test.rs
crates/core/utils/src/process.rs
crates/core/utils/src/shell.rs
packages/cli/CHANGELOG.md
packages/types/src/project-config.ts
packages/types/src/project.ts
tests/fixtures/cases/depends-on/moon.yml
tests/fixtures/system/unix/moon.yml
tests/fixtures/system/windows/moon.yml
website/blog/2023-03-27_moon-v1.0.mdx
website/docs/config/project.mdx
website/docs/faq.mdx

Fixes https://github.com/moonrepo/moon/issues/696 and https://github.com/moonrepo/moon/issues/223

new: Wrap system tasks in a shell.

---

crates/core/cache/src/engine.rs
crates/core/cache/tests/engine_test.rs
crates/core/project-graph/src/project_builder.rs
packages/cli/CHANGELOG.md

Context: https://bford.info/cachedir/

new: Create a cache directory tag.

---

.github/workflows/rust.yml
Makefile.toml
crates/cli/src/helpers.rs
crates/cli/src/lib.rs
crates/cli/tests/run_node_test.rs
crates/core/config/src/workspace/config.rs
crates/core/config/tests/workspace_test.rs
crates/core/launchpad/src/lib.rs
crates/core/moon/src/lib.rs
crates/core/terminal/src/output.rs
crates/core/workspace/src/workspace.rs
packages/cli/CHANGELOG.md
packages/types/src/workspace-config.ts
website/blog/2023-03-27_moon-v1.0.mdx
website/docs/config/workspace.mdx

This will disable the version check request.

new: Add a `telemetry` setting.

---

crates/core/project-graph/src/graph_hasher.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/utils/src/lib.rs
packages/cli/CHANGELOG.md

fix: Fix project graph cache across container boundaries.

---

crates/cli/src/app.rs
crates/cli/tests/run_test.rs
crates/cli/tests/snapshots/run_test__target_scopes__errors_for_cwd.snap
crates/core/dep-graph/src/dep_builder.rs
crates/core/project-graph/src/project_graph.rs
packages/cli/CHANGELOG.md
website/blog/2023-04-03_moon-v1.1.mdx
website/docs/commands/run.mdx

Implements https://github.com/moonrepo/moon/issues/719

new: Support running tasks based on cwd.

---

crates/node/lang/src/pnpm/dependency_path.rs
packages/cli/CHANGELOG.md
website/blog/2023-04-03_moon-v1.1.mdx

We technically support it already since we're always testing against pnpm master, but I added more tests just in case.
https://github.com/pnpm/pnpm/releases/tag/v8.0.0

new: Support pnpm v8's new lockfile.

---

crates/cli/src/app.rs
crates/cli/src/commands/mod.rs
crates/cli/src/commands/project.rs
crates/cli/src/commands/task.rs
crates/cli/src/lib.rs
crates/cli/tests/snapshots/project_test__advanced_config.snap
crates/cli/tests/snapshots/project_test__basic_config.snap
crates/cli/tests/snapshots/project_test__depends_on_paths.snap
crates/cli/tests/snapshots/project_test__empty_config.snap
crates/cli/tests/snapshots/project_test__no_config.snap
crates/cli/tests/snapshots/project_test__root_level.snap
crates/cli/tests/snapshots/project_test__with_tasks.snap
crates/cli/tests/snapshots/task_test__shows_inputs.snap
crates/cli/tests/snapshots/task_test__shows_outputs.snap
crates/cli/tests/snapshots/task_test__unknown_task.snap
crates/cli/tests/task_test.rs
crates/core/moon/src/lib.rs
crates/core/moonbase/Cargo.toml
crates/core/moonbase/src/common.rs
crates/core/moonbase/src/lib.rs
crates/core/terminal/src/terminal.rs
packages/cli/CHANGELOG.md
tests/fixtures/projects/tasks/moon.yml
website/blog/2023-04-03_moon-v1.1.mdx
website/docs/commands/task.mdx
website/sidebars.js

This new command will display resolved information, to help with debugging issues.

new: Add `moon task` command.

---

.yarn/versions/0043aa8c.yml
crates/core/config/src/workspace/hasher.rs
crates/core/project-graph/src/project_builder.rs
crates/core/runner/src/inputs_collector.rs
crates/core/vcs/src/git.rs
crates/core/vcs/src/svn.rs
crates/core/vcs/src/vcs.rs
crates/core/vcs/tests/git_test.rs
packages/cli/CHANGELOG.md
packages/types/src/workspace-config.ts
website/docs/config/workspace.mdx

This actually solves a couple problems. Refer to the docs/comments for more info.

fix: Fix input collection performance issues.

---

crates/cli/tests/dep_graph_test.rs
crates/core/project-graph/src/project_builder.rs
crates/core/project-graph/src/token_resolver.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/project-graph/tests/token_resolver_test.rs
packages/cli/CHANGELOG.md
tests/fixtures/tasks/tokens/moon.yml
website/blog/2023-04-03_moon-v1.1.mdx
website/docs/concepts/token.mdx

Implements https://github.com/moonrepo/moon/issues/752

new: Support token variables in task commands.

---

crates/cli/tests/run_test.rs
crates/core/action-pipeline/src/actions/run_target.rs
crates/core/project-graph/src/project_builder.rs
crates/core/runner/src/runner.rs
packages/cli/CHANGELOG.md
website/blog/2023-04-03_moon-v1.1.mdx

new: Update `noop` tasks to be cacheable.

---

Cargo.lock
Cargo.toml
crates/core/test-utils/src/cli.rs
crates/node/tool/src/node_tool.rs
crates/node/tool/src/npm_tool.rs
crates/node/tool/src/pnpm_tool.rs
crates/node/tool/src/yarn_tool.rs
packages/cli/CHANGELOG.md
website/blog/2023-04-17_moon-v1.2.mdx

https://moonrepo.dev/blog/proto-v0.6

deps(proto): Update to v0.6.

---

.github/workflows/benchmark.yml
.github/workflows/moon.yml
.github/workflows/release.yml
.github/workflows/rust.yml

ci: Change Windows runner to a t2 box.

---

.yarn/versions/d189b739.yml
crates/core/project-graph/tests/token_resolver_test.rs
crates/core/utils/src/regex.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/792

fix: Fix `$projectAlias` not working.

---

crates/core/action-pipeline/src/pipeline.rs
packages/cli/CHANGELOG.md

Reports of zombie processes. I'm not 100% sure this will fix the problem as it's hard to test/reproduce.

fix: Fix running tasks not being killed.

---

.yarn/versions/94cb73eb.yml
crates/cli/src/main.rs
crates/node/tool/src/pnpm_tool.rs
crates/node/tool/src/yarn_tool.rs
packages/cli/CHANGELOG.md

fix: Fix a handful of Node.js dependency manager issues.

---

.yarn/versions/c7579135.yml
crates/node/lang/src/pnpm/mod.rs
packages/cli/CHANGELOG.md
website/docs/commands/run.mdx
website/docs/commands/task.mdx
website/docs/concepts/query-lang.mdx
website/docs/concepts/task.mdx
website/src/components/Docs/VersionLabel.tsx

Fixes https://github.com/moonrepo/moon/issues/814

fix: Fix empty `pnpm-lock.yaml` parsing.

---

.github/workflows/moon.yml
.github/workflows/release.yml
.github/workflows/rust-stub.yml
.github/workflows/rust.yml
scripts/Dockerfile

Started failing after I added the nextgen folder.

ci: Fix broken release workflow.

---

crates/cli/src/app.rs
crates/cli/tests/check_test.rs
crates/cli/tests/run_test.rs
crates/core/action-context/src/lib.rs
crates/core/action-pipeline/benches/pipeline_benchmark.rs
crates/core/dep-graph/benches/dep_graph_benchmark.rs
crates/core/dep-graph/src/dep_builder.rs
crates/core/project-graph/src/project_builder.rs
crates/core/project-graph/src/project_graph.rs
crates/core/project-graph/tests/project_graph_test.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/utils/src/regex.rs
nextgen/query/src/builder.rs
nextgen/query/tests/builder_test.rs
nextgen/target/src/errors.rs
tests/fixtures/cases/base/moon.yml
tests/fixtures/cases/depends-on/moon.yml
tests/fixtures/cases/deps-a/moon.yml
tests/fixtures/cases/deps-b/moon.yml
tests/fixtures/cases/deps-c/moon.yml
website/blog/2023-05-01_moon-v1.4.mdx
website/docs/cheat-sheet.mdx
website/docs/commands/run.mdx
website/docs/concepts/target.mdx

Implements https://github.com/moonrepo/moon/issues/803

new: Support tag (#tag) target scope.

---

crates/core/runner/src/runner.rs
packages/cli/CHANGELOG.md
website/blog/2023-05-15_moon-v1.6.mdx

Indicator for long-running processes.

new: Log a checkpoint every 30 seconds.

---

Cargo.lock
nextgen/config/Cargo.toml
nextgen/config/src/inherited_tasks_config.rs
nextgen/config/src/project/task_config.rs
nextgen/config/src/project_config.rs
nextgen/config/src/template_config.rs
nextgen/config/src/toolchain_config.rs
nextgen/config/src/workspace_config.rs
nextgen/config/tests/project_config_test.rs
nextgen/config/tests/workspace_config_test.rs

internal: Update schematic.

---

.yarn/versions/277848dc.yml
Cargo.lock
crates/node/platform/src/platform.rs
nextgen/config/Cargo.toml
nextgen/config/src/inherited_tasks_config.rs
nextgen/config/src/project/task_config.rs
nextgen/config/src/project_config.rs
nextgen/config/src/template/frontmatter.rs
nextgen/config/src/template_config.rs
nextgen/config/src/toolchain_config.rs
nextgen/config/src/workspace_config.rs
nextgen/config/tests/workspace_config_test.rs
nextgen/process/src/command_inspector.rs
packages/cli/CHANGELOG.md

deps(schematic): Update to v0.7.

---

crates/cli/src/commands/migrate/from_turborepo.rs
crates/core/action-pipeline/src/subscribers/local_cache.rs
crates/core/cache/src/items/run_target_state.rs
crates/core/project-graph/src/project_builder.rs
crates/core/project-graph/src/token_resolver.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/project-graph/tests/token_resolver_test.rs
crates/core/runner/src/target_hasher.rs
crates/core/task/src/task.rs
crates/node/platform/src/task.rs
crates/node/platform/tests/task_test.rs
nextgen/config/src/project/task_config.rs
nextgen/config/src/shapes/input_path.rs
nextgen/config/src/shapes/mod.rs
nextgen/config/src/shapes/output_path.rs
nextgen/config/tests/task_config_test.rs
packages/cli/CHANGELOG.md

Output companion PR to https://github.com/moonrepo/moon/pull/886

internal: Use an enum for task outputs.

---

Cargo.lock
nextgen/codeowners/Cargo.toml
nextgen/codeowners/src/codeowners_hash.rs
nextgen/codeowners/src/codeowners_hasher.rs
nextgen/codeowners/src/lib.rs
nextgen/hash/Cargo.toml
nextgen/hash/src/hash_engine.rs
nextgen/hash/src/hash_error.rs
nextgen/hash/src/hasher.rs
nextgen/hash/src/lib.rs
nextgen/hash/tests/hash_engine_test.rs
nextgen/hash/tests/hasher_test.rs

Our current hasher is over-engineered and hard to use.
This rethinks the approach, and will slowly be adopted.

new: Implement new content hasher crate.

---

website/src/components/ComparisonTable.tsx

Updating the comparison table to reflect some recent Turborepo releases (generators, and run summaries).

feat(docs): update generators comparison

---

crates/rust/platform/src/lib.rs
crates/rust/platform/src/rust_platform.rs
packages/cli/CHANGELOG.md
tests/fixtures/project-graph/langs/rust-config/Cargo.toml

Fixes https://github.com/moonrepo/moon/issues/907

fix: Improve Cargo workspace root detection.

---

Cargo.lock
crates/cli/src/queries/projects.rs
crates/core/actions/src/sync_codeowners.rs
crates/core/hasher/src/helpers.rs
crates/core/project-graph/src/helpers.rs
crates/core/project-graph/src/project_builder.rs
crates/core/project-graph/tests/project_graph_test.rs
crates/core/project-graph/tests/projects_test.rs
crates/core/project-graph/tests/token_resolver_test.rs
crates/core/project/Cargo.toml
crates/core/project/src/project.rs
crates/core/project/tests/project_test.rs
crates/core/runner/src/runner.rs
crates/core/test-utils/src/cli.rs
crates/node/platform/src/platform.rs
crates/rust/platform/src/rust_platform.rs
crates/typescript/platform/src/sync_project.rs
nextgen/common/src/path.rs
nextgen/file-group/src/file_group.rs
nextgen/file-group/tests/file_group_test.rs
packages/cli/CHANGELOG.md

Still running into some issues where path separators between Win/Nix are causing hash inconsistencies. Another pass to resolve these.

fix: Fix path separator issues.

---

.yarn/versions/da60f09b.yml
crates/cli/tests/run_system_test.rs
crates/cli/tests/snapshots/run_system_test__unix__passes_args_through.snap
nextgen/args/src/lib.rs
nextgen/args/tests/args_test.rs
packages/cli/CHANGELOG.md
tests/fixtures/system/unix/moon.yml

Fixes https://github.com/moonrepo/moon/issues/925

fix: Fix shell argument quoting.

---

.github/workflows/rust.yml

ci: Use new macos m1 runner.

---

crates/cli/src/app.rs
crates/cli/src/commands/syncs/codeowners.rs
crates/cli/src/commands/syncs/hooks.rs
crates/cli/src/lib.rs
crates/cli/tests/sync_test.rs
crates/core/action-pipeline/src/actions/sync_workspace.rs
crates/core/actions/src/sync_codeowners.rs
crates/core/actions/src/sync_vcs_hooks.rs
nextgen/codeowners/src/codeowners_generator.rs
nextgen/vcs-hooks/src/hooks_generator.rs
nextgen/vcs-hooks/tests/hooks_generator_test.rs
packages/cli/CHANGELOG.md
website/docs/commands/sync/codeowners.mdx
website/docs/commands/sync/hooks.mdx
website/docs/guides/vcs-hooks.mdx

new: Support unsyncing/cleaning up.

---

crates/cli/src/commands/ci.rs
crates/cli/src/commands/run.rs
crates/cli/src/lib.rs
crates/cli/src/queries/touched_files.rs
crates/cli/tests/query_test.rs
packages/cli/CHANGELOG.md
website/docs/commands/ci.mdx
website/docs/commands/run.mdx
website/docs/guides/ci.mdx

Also improves how `moon run` handles this flow.

new: Support `MOON_BASE` and `MOON_HEAD` env vars.

---

crates/cli/src/helpers.rs
crates/core/utils/src/lib.rs
packages/cli/CHANGELOG.md

fix: Hide upgrade message when `--json` is requested.

---

.yarn/versions/415cc74d.yml
crates/core/platform-detector/src/language_files.rs
crates/core/platform-detector/src/project_language.rs
crates/python/lang/src/lib.rs

As soon as I noticed the existence of moon, it captivated me. I hope this is my first of many contributions accepted.

Add Poetry dependency manager for python

---

crates/cli/src/commands/check.rs
crates/cli/src/commands/ci.rs
crates/core/dep-graph/src/dep_builder.rs
nextgen/project-builder/tests/project_builder_test.rs
nextgen/project-expander/src/project_expander.rs
nextgen/project/src/project.rs
nextgen/project/src/project_error.rs
nextgen/task/src/task.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/989

fix: Fix `moon ci` not gathering targets. Improve unexpanded task checks.

---

nextgen/vcs/src/git.rs
nextgen/vcs/tests/git_test.rs
packages/cli/CHANGELOG.md
website/src/components/ComparisonTable.tsx

https://git-scm.com/docs/git-worktree

new: Add git worktree support.

---

.moon/workspace.yml
.yarn/versions/68b9d98d.yml
crates/cli/tests/run_test.rs
crates/cli/tests/snapshots/run_test__dependencies__changes_primary_hash_if_deps_hash_changes.snap
crates/cli/tests/snapshots/run_test__dependencies__generates_unique_hashes_for_each_target.snap
crates/cli/tests/snapshots/run_test__output_styles__hash.snap
crates/core/action-pipeline/src/actions/run_target.rs
crates/core/action-pipeline/src/pipeline.rs
crates/core/action/src/action.rs
crates/core/runner/src/runner.rs
crates/core/test-utils/src/configs.rs
nextgen/config/src/project/task_options_config.rs
nextgen/project-expander/src/expander_context.rs
nextgen/project-expander/src/tasks_expander.rs
nextgen/project-expander/src/tasks_expander_error.rs
nextgen/project-expander/tests/tasks_expander_test.rs
nextgen/project-expander/tests/utils.rs
nextgen/task-builder/src/tasks_builder.rs
nextgen/task/src/task_options.rs
packages/cli/CHANGELOG.md
packages/types/src/tasks-config.ts
tests/fixtures/cases/states/moon.yml
website/blog/2023-09-04_moon-v1.13.mdx
website/docs/config/project.mdx
website/moon.yml
website/static/schemas/project.json
website/static/schemas/tasks.json

Through a new `allowFailure` option.

new: Allow tasks to fail and not abort the pipeline.

---

Cargo.lock
Cargo.toml
crates/core/tool/src/lib.rs
crates/core/workspace/src/workspace.rs
nextgen/app-components/src/resources.rs
nextgen/app/src/systems/startup.rs
packages/cli/CHANGELOG.md

deps: Update to proto v0.16.

---

nextgen/target/src/target.rs
nextgen/target/tests/target_test.rs
nextgen/task-builder/src/tasks_builder.rs
nextgen/task-builder/tests/__fixtures__/builder/global-overrides/tasks.yml
nextgen/task-builder/tests/tasks_builder_test.rs
packages/cli/CHANGELOG.md

Context: https://twitter.com/shellscape/status/1698444995181564024

fix: Fix global task deps not applying exclude/rename.

---

.yarn/versions/4539b14a.yml
crates/node/tool/src/node_tool.rs
crates/node/tool/src/npm_tool.rs
crates/node/tool/src/pnpm_tool.rs
crates/node/tool/src/yarn_tool.rs
crates/rust/platform/src/rust_platform.rs
crates/rust/tool/src/rust_tool.rs
packages/cli/CHANGELOG.md

I missed this as part of the WASM migration.
Fixes https://github.com/moonrepo/moon/issues/1044

fix: Fix globals directory not being located.

---

.github/workflows/moon.yml
crates/cli/src/commands/ci.rs
crates/core/dep-graph/src/dep_graph.rs
packages/cli/CHANGELOG.md
website/docs/commands/ci.mdx
website/docs/guides/ci.mdx

Will help with https://github.com/moonrepo/moon/issues/1047

new: Allow targets to be passed to `moon ci`.

---

Cargo.lock
Cargo.toml
crates/cli/src/lib.rs
crates/cli/tests/run_test.rs
nextgen/config/Cargo.toml
packages/cli/CHANGELOG.md
website/blog/2023-09-25_moon-v1.14.mdx
website/docs/commands/run.mdx
website/docs/run-task.mdx

new: Support shorthand `moon run`.

---

crates/cli/src/commands/docker/scaffold.rs
nextgen/app/src/systems/startup.rs
nextgen/config/src/inherited_tasks_config.rs
nextgen/config/tests/__fixtures__/inheritance/nested/tasks.yml
nextgen/config/tests/__fixtures__/inheritance/nested/tasks/dotnet/dotnet-application.yml
nextgen/config/tests/__fixtures__/inheritance/nested/tasks/dotnet/dotnet.yml
nextgen/config/tests/__fixtures__/inheritance/nested/tasks/node/node-library.yml
nextgen/config/tests/__fixtures__/inheritance/nested/tasks/node/node.yml
nextgen/config/tests/inherited_tasks_config_test.rs
nextgen/project-graph/src/project_graph_builder.rs
nextgen/project-graph/tests/project_graph_test.rs
nextgen/task-builder/tests/tasks_builder_test.rs
nextgen/workspace/src/workspace.rs
packages/cli/CHANGELOG.md
website/blog/2023-09-25_moon-v1.14.mdx
website/docs/concepts/task-inheritance.mdx
website/docs/config/tasks.mdx
website/docs/guides/debug-task.mdx

Implements https://github.com/moonrepo/moon/issues/1066

new: Allow task configs to be nested in folders.

---

website/blog/2023-09-25_moon-v1.14.mdx
website/docs/guides/examples/astro.mdx
website/docs/guides/examples/nest.mdx
website/docs/guides/examples/next.mdx
website/docs/guides/examples/packemon.mdx
website/docs/guides/examples/remix.mdx
website/docs/guides/examples/sveltekit.mdx
website/docs/guides/examples/vite.mdx

Need to bubble up this repo more.

docs: Update examples to use moon-configs.

---

Cargo.lock
Cargo.toml
nextgen/config/Cargo.toml

deps: Update proto to latest.

---

Cargo.lock
Cargo.toml
packages/cli/CHANGELOG.md

fix: Fix glob clean panic.

---

.github/workflows/release-npm.yml
.github/workflows/release.yml
.github/workflows/rust-stub.yml
.github/workflows/rust.yml
scripts/release/planRelease.sh
scripts/release/publishBinaryPackages.sh
scripts/release/publishPackages.sh
scripts/release/setupNpm.sh
website/docs/install.mdx

This will help to catch issues sooner.

ci: Add nightly releases.

---

.yarn/versions/07432d6e.yml
crates/cli/src/commands/generate.rs
nextgen/codegen/src/template.rs
nextgen/codegen/tests/template_test.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/1123
It's weird, I have tests around this use case that pass, but it does seem to be failing for users. So moving things around.

fix: Fix raw files being rendered during codegen.

---

.yarn/versions/7b9badc9.yml
crates/cli/src/lib.rs
crates/core/tool/src/lib.rs
crates/deno/tool/src/deno_tool.rs
crates/node/tool/src/bun_tool.rs
crates/node/tool/src/node_tool.rs
crates/node/tool/src/npm_tool.rs
crates/node/tool/src/pnpm_tool.rs
crates/node/tool/src/yarn_tool.rs
crates/rust/platform/src/rust_platform.rs
crates/rust/tool/src/rust_tool.rs
nextgen/app/src/main.rs
nextgen/project-graph/src/project_graph.rs
tests/fixtures/node/base/envVarsMoon.js
tests/fixtures/rust/cases/src/bin/env_vars_moon.rs
tests/fixtures/system/unix/envVarsMoon.sh
website/blog/2023-10-30_moon-v1.16.mdx
website/docs/concepts/toolchain.mdx

Useful for environments like CI or Docker.

new: Support forcing globals instead of downloading tools.

---

.yarn/versions/bd79fcf5.yml
Cargo.lock
Cargo.toml
crates/cli/src/commands/ci.rs
nextgen/query/src/mql.pest
nextgen/query/tests/parser_test.rs
packages/cli/CHANGELOG.md

fix: Audit 11/03

---

.yarn/versions/bb5e5642.yml
crates/cli/tests/run_node_test.rs
crates/core/test-utils/src/sandbox.rs
nextgen/config/src/toolchain/node_config.rs
nextgen/config/tests/toolchain_config_test.rs
packages/cli/CHANGELOG.md
website/docs/config/toolchain.mdx

Fixes https://github.com/moonrepo/moon/issues/1168

fix: Add fallback for unsupported `node.dependencyVersionFormat`.

---

.github/workflows/rust.yml
nextgen/codegen/src/template.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/1184

fix: Use correct source when merging JSON/YAML.

---

.yarn/versions/730be944.yml
crates/cli/src/app.rs
crates/rust/platform/src/rust_platform.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/1195

fix: Fix cargo-binstall install issues.

---

.yarn/versions/fa2671e9.yml
Cargo.lock
Cargo.toml
crates/cli/src/app.rs
crates/cli/src/commands/upgrade.rs
crates/cli/src/lib.rs
crates/cli/src/main.rs
crates/rust/platform/src/rust_platform.rs
crates/rust/platform/tests/rust_platform_test.rs
nextgen/common/src/path.rs
packages/cli/CHANGELOG.md

fix: Fix Cargo bin detection on Windows.

---

.github/workflows/release-npm.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
nextgen/config/tests/toolchain_config_test.rs
packages/cli/CHANGELOG.md
scripts/release/planRelease.sh
scripts/release/setupNpm.sh
website/docs/install.mdx

Using the same nightly system.

new: Add canary releases.

---

nextgen/action-graph/src/action_graph_builder.rs
nextgen/args/src/lib.rs
nextgen/process/src/async_command.rs
nextgen/process/src/command_inspector.rs
nextgen/project-expander/src/token_expander.rs
nextgen/project-expander/tests/token_expander_test.rs
nextgen/project-graph/src/project_graph.rs
nextgen/project/src/project.rs
nextgen/query/src/builder.rs
nextgen/query/src/parser.rs
nextgen/query/tests/builder_test.rs
nextgen/vcs/src/vcs.rs
packages/cli/CHANGELOG.md

This will help reduce string allocations.

internal: Use `Cow` when appropriate.

---

.yarn/versions/a26771bf.yml
nextgen/config/src/project_config.rs
nextgen/config/tests/project_config_test.rs
nextgen/project-builder/src/project_builder.rs
nextgen/project-graph/src/project_graph_builder.rs
nextgen/project-graph/tests/__fixtures__/custom-id-old-ref/bar/moon.yml
nextgen/project-graph/tests/__fixtures__/custom-id-old-ref/foo/moon.yml
nextgen/project-graph/tests/__fixtures__/custom-id/bar/moon.yml
nextgen/project-graph/tests/__fixtures__/custom-id/baz/moon.yml
nextgen/project-graph/tests/__fixtures__/custom-id/foo/moon.yml
nextgen/project-graph/tests/project_graph_test.rs
packages/cli/CHANGELOG.md
packages/types/src/project-config.ts
website/blog/2023-12-12_moon-v1.18.mdx
website/docs/config/project.mdx
website/docs/config/workspace.mdx
website/static/schemas/project.json

This has been a long requested feature.

new: Allow project ID to be configured in `moon.yml`.

---

Cargo.lock
crates/cli/src/commands/docker/scaffold.rs
crates/cli/src/commands/docker/setup.rs
crates/core/action-pipeline/Cargo.toml
crates/core/action-pipeline/src/actions/sync_workspace.rs
crates/core/actions/Cargo.toml
crates/core/actions/src/install_proto.rs
crates/core/actions/src/lib.rs
packages/cli/CHANGELOG.md

Fixes: https://github.com/moonrepo/moon/issues/1263

fix: Fix proto not being available in Docker.

---

.yarn/versions/c4983cac.yml
Cargo.lock
crates/core/actions/src/install_proto.rs
crates/core/moon/Cargo.toml
crates/core/moon/src/lib.rs
packages/cli/CHANGELOG.md

Was not expecting this branch to be hit but here we are.

fix: Another attempt at fixing proto in docker.

---

.yarn/versions/6350425d.yml
nextgen/config/src/inherited_tasks_config.rs
nextgen/config/tests/__fixtures__/inheritance/options/tasks.yml
nextgen/config/tests/__fixtures__/inheritance/options/tasks/node-library.yml
nextgen/config/tests/__fixtures__/inheritance/options/tasks/node.yml
nextgen/config/tests/inherited_tasks_config_test.rs
nextgen/task-builder/src/tasks_builder.rs
nextgen/task-builder/tests/__fixtures__/builder/global/tasks.yml
nextgen/task-builder/tests/__fixtures__/builder/global/tasks/node-application.yml
nextgen/task-builder/tests/__fixtures__/builder/global/tasks/node.yml
nextgen/task-builder/tests/__fixtures__/builder/options-default/moon.yml
nextgen/task-builder/tests/tasks_builder_test.rs
packages/cli/CHANGELOG.md
packages/types/src/tasks-config.ts
website/blog/2024-01-22_moon-v1.20.mdx
website/docs/config/tasks.mdx
website/static/schemas/tasks.json

Implements https://github.com/moonrepo/moon/issues/1012 and https://github.com/moonrepo/moon/issues/881

new: Support default task options in task configs.

---

website/src/components/ComparisonTable.tsx

https://turbo.build/repo/docs/reference/command-line-reference/run#--ignore
https://turbo.build/repo/docs/reference/command-line-reference/run#--concurrency

docs: update ignore and serial for turborepo

---

website/src/components/ComparisonTable.tsx

Hi @milesj,
Congrats on all the great work with moon and proto!
I was a bit dismayed to see how significantly mistaken the website's comparison table is about Nx, so I have made the necessary changes here for your review.
Please let me know if anything is unclear or you want to discuss further.
Cheers!

fix(website): comparison table is significantly mistaken about nx

---

.yarn/versions/ab67f2df.yml
Cargo.lock
crates/core/runner/src/runner.rs
crates/system/platform/src/system_platform.rs
nextgen/config/src/main.rs
nextgen/config/src/project/task_options_config.rs
nextgen/console/Cargo.toml
nextgen/console/src/console.rs
nextgen/process/src/async_command.rs
nextgen/process/src/command.rs
nextgen/process/src/command_inspector.rs
nextgen/process/src/lib.rs
nextgen/process/src/shell.rs
nextgen/task-builder/src/tasks_builder.rs
nextgen/task/src/task_options.rs
packages/cli/CHANGELOG.md
packages/types/src/project-config.ts
packages/types/src/tasks-config.ts
website/docs/config/project.mdx
website/moon.yml
website/static/schemas/project.json
website/static/schemas/tasks.json

Fixes https://github.com/moonrepo/moon/issues/1284
cc @shellscape

new: Allow Unix and Windows shells to be customizeable.

---

crates/cli/src/commands/init/bun.rs
crates/cli/src/commands/init/node.rs
crates/cli/src/commands/init/rust.rs
crates/cli/src/commands/init/typescript.rs
crates/cli/src/systems/execute.rs
nextgen/common/src/env.rs
nextgen/console/src/console.rs
nextgen/console/src/printer.rs

Removing `BufWriter` as it seemed unnecessary.

internal: More console buffer improvements.

---

.github/workflows/pr.yml
website/docs/proto/install.mdx
website/static/install/proto.ps1
website/static/install/proto.sh

build: Update proto install scripts.

---

Cargo.lock
nextgen/file-group/Cargo.toml
nextgen/file-group/src/file_group.rs
nextgen/file-group/src/file_group_error.rs
nextgen/file-group/tests/file_group_test.rs
nextgen/project-builder/src/project_builder.rs
nextgen/project-expander/src/tasks_expander.rs
nextgen/project-expander/src/token_expander.rs
nextgen/project-expander/tests/token_expander_test.rs
nextgen/project-expander/tests/utils.rs
packages/cli/CHANGELOG.md
website/blog/2024-02-07_moon-v1.21.mdx
website/docs/concepts/token.mdx

Fixes https://github.com/moonrepo/moon/issues/1310

new: Support env vars in file groups.

---

.yarn/versions/acef3110.yml
nextgen/config/src/project/task_options_config.rs
nextgen/config/tests/task_config_test.rs
nextgen/project-expander/src/tasks_expander.rs
nextgen/project-expander/tests/tasks_expander_test.rs
nextgen/task-builder/src/tasks_builder.rs
nextgen/task-builder/tests/__fixtures__/builder/options/moon.yml
nextgen/task-builder/tests/tasks_builder_test.rs
nextgen/task/src/task_options.rs
packages/cli/CHANGELOG.md
packages/report/tests/action.test.ts
packages/report/tests/report.test.ts
packages/types/src/pipeline.ts
packages/types/src/project.ts
website/docs/config/project.mdx

new: Support a list for `options.envFile`.

---

.github/workflows/release.yml
.yarn/versions/6bf0843f.yml
packages/cli/CHANGELOG.md

Looks like the new arm64 runners cause issues.

fix: Revert back to old release targets.

---

Cargo.lock
nextgen/config/src/patterns.rs
nextgen/config/src/shapes/input_path.rs
nextgen/config/tests/task_config_test.rs
nextgen/file-group/src/file_group.rs
nextgen/project-expander/Cargo.toml
nextgen/project-expander/src/token_expander.rs
nextgen/project-expander/tests/token_expander_test.rs
packages/cli/CHANGELOG.md
website/docs/concepts/file-group.mdx
website/docs/config/project.mdx

Easier to use `$VITE_*` then list all variables manually!

new: Support environment variable wildcards for inputs.

---

Cargo.lock
Cargo.toml
nextgen/config/src/main.rs
packages/types/src/project-config.ts
packages/types/src/tasks-config.ts
packages/types/src/toolchain-config.ts
packages/types/src/workspace-config.ts
website/static/schemas/project.json
website/static/schemas/tasks.json
website/static/schemas/template-frontmatter.json
website/static/schemas/template.json
website/static/schemas/toolchain.json
website/static/schemas/workspace.json

This should work better with the vscode extension.

new: Remove nullable from JSONSchema types.

---

Cargo.lock
Cargo.toml
nextgen/config/src/project/owners_config.rs
nextgen/config/src/project/task_config.rs
nextgen/config/src/project/task_options_config.rs
nextgen/config/src/project_config.rs
nextgen/config/src/template_config.rs
nextgen/config/src/toolchain/bin_config.rs
nextgen/config/src/workspace/notifier_config.rs
nextgen/config/src/workspace_config.rs
packages/types/src/tasks-config.ts
packages/types/src/template-config.ts
packages/types/src/toolchain-config.ts
packages/types/src/workspace-config.ts
website/static/schemas/project.json
website/static/schemas/tasks.json
website/static/schemas/template-frontmatter.json
website/static/schemas/template.json
website/static/schemas/toolchain.json
website/static/schemas/workspace.json

new: Add more schema descriptions, remove some titles.

---

nextgen/vcs-hooks/src/hooks_generator.rs
nextgen/vcs-hooks/tests/snapshots/hooks_generator_test__windows__links_git_hooks-2.snap
nextgen/vcs-hooks/tests/snapshots/hooks_generator_test__windows__links_git_hooks.snap
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/1338

fix: Fix Windows VCS hooks.

---

.yarn/versions/f71cf542.yml
nextgen/vcs/src/git.rs
nextgen/vcs/tests/git_test.rs
packages/cli/CHANGELOG.md

This regressed at some point...

fix: Fix invalid paths when moon is nested within a git repository.

---

.github/workflows/release.yml
nextgen/config/src/main.rs
packages/cli/CHANGELOG.md
scripts/release/prepareArtifacts.sh
scripts/release/renameJsonSchemas.sh
scripts/release/syncArtifacts.mjs

new: Include JSON schemas as a release artifact.

---

.github/workflows/pr.yml
crates/cli/src/systems/startup.rs
crates/javascript/platform/src/sync_project.rs
nextgen/plugin/src/plugin_registry.rs
packages/cli/CHANGELOG.md

fix: Fix Bun `link:` format.

---

website/src/data/proto-tools.tsx

Add [k3d](https://k3d.io) proto toml plugin

docs: add k3d plugin

---

Cargo.lock
Cargo.toml
crates/cli/src/commands/ci.rs
packages/cli/CHANGELOG.md
website/blog/2024-04-17_moon-v1.24.mdx
website/docs/guides/ci.mdx

For https://github.com/moonrepo/moon/issues/1412

new: Auto-detect base/head from CI providers.

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
crates/core/platform/src/manager.rs
nextgen/action-graph/src/action_graph_builder.rs
nextgen/action-graph/tests/action_graph_test.rs
nextgen/common/src/consts.rs
nextgen/process/src/command_inspector.rs
nextgen/task-builder/src/tasks_builder.rs
nextgen/task-builder/tests/__fixtures__/builder/moon.yml
nextgen/task-builder/tests/tasks_builder_test.rs
nextgen/task/src/task.rs
nextgen/workspace/src/workspace.rs
packages/cli/CHANGELOG.md
packages/types/src/project.ts
website/docs/guides/root-project.mdx

Couldn't land these on master.

fix: Minor fixes for v1.24.

---

nextgen/project-expander/src/tasks_expander.rs
nextgen/project-expander/src/token_expander.rs
nextgen/project-expander/tests/tasks_expander_test.rs
packages/cli/CHANGELOG.md

fix: Fix task deps args/env not supporting tokens.

---

website/src/data/proto-tools.tsx

Hi,
I've added the openapi cli tools of pb33f to the docs.

docs: added pb33f tools

---

website/blog/2024-05-05_proto-v0.35.mdx
website/docs/proto/commands/setup.mdx

docs: Add proto v0.35 blog post.

---

.github/workflows/rust.yml
README.md
crates/common/src/consts.rs

I forgot to do this in the other PR.

internal: Bump proto version.

---

.yarn/versions/2c0d13e6.yml
crates/config/src/workspace/plugins_config.rs
packages/cli/CHANGELOG.md
website/docs/guides/extensions.mdx

deps: Update extensions.

---

crates/vcs/src/git.rs
crates/vcs/tests/git_test.rs
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/1490

fix: Fix git version parsing.

---

.github/workflows/rust.yml
.yarn/versions/c68909ea.yml
Cargo.lock
Cargo.toml
crates/common/src/consts.rs
legacy/bun/tool/src/bun_tool.rs
legacy/node/platform/src/actions/setup_tool.rs
legacy/node/tool/src/bun_tool.rs
packages/cli/CHANGELOG.md

I forgot to await the locks...

fix: Fix a potential deadlock.

---

.moon/workspace.yml
Cargo.lock
Cargo.toml
packages/cli/CHANGELOG.md

Fixes https://github.com/moonrepo/moon/issues/1532

fix: Fix glob with leading `./`.

---

crates/config/src/config_cache.rs
crates/config/src/toolchain/node_config.rs
justfile
legacy/node/platform/src/actions/setup_tool.rs
legacy/node/tool/src/node_tool.rs
legacy/node/tool/src/yarn_tool.rs
packages/cli/CHANGELOG.md
packages/types/src/toolchain-config.ts
website/docs/config/toolchain.mdx
website/static/schemas/toolchain.json

Fixes https://github.com/moonrepo/moon/issues/1533 https://github.com/moonrepo/moon/issues/1534

new: Improve Node/Yarn handling.

---

crates/action-pipeline/src/action_runner.rs
crates/actions/src/actions/install_deps.rs
crates/cli/tests/docker_test.rs
crates/console/src/buffer.rs
crates/console/src/console.rs
justfile
legacy/core/action-pipeline/src/processor.rs
packages/cli/CHANGELOG.md

internal: Improve automatic deps install flow.

---

.yarn/versions/b3e6ef24.yml
CHANGELOG.md
crates/project-expander/src/token_expander.rs
crates/project-expander/tests/tasks_expander_test.rs
crates/project-expander/tests/token_expander_test.rs

Fixes https://github.com/moonrepo/moon/issues/1563

fix: Fix file group path resolving for script/env.

---

CHANGELOG.md
crates/project-expander/src/token_expander.rs
crates/project-expander/src/token_expander_error.rs
crates/project-expander/tests/tasks_expander_test.rs
crates/project-expander/tests/token_expander_test.rs
website/docs/concepts/token.mdx

Fixes https://github.com/moonrepo/moon/issues/1566

fix: Improve token handling.

---

.yarn/versions/8841b6e0.yml
CHANGELOG.md
crates/project-expander/src/token_expander.rs
crates/project-expander/tests/token_expander_test.rs

Fixes https://github.com/moonrepo/moon/issues/1590

fix: Fix token replacement for multiple variables.

---

CHANGELOG.md
crates/action-graph/src/action_graph_builder.rs
crates/app/src/commands/docker/file.rs
crates/app/src/commands/graph/action.rs
crates/app/src/commands/project.rs
crates/app/src/commands/query.rs
crates/app/src/queries/projects.rs
crates/cli/tests/query_test.rs
crates/cli/tests/snapshots/query_test__tasks__returns_all_by_default.snap
crates/project-expander/src/tasks_expander.rs
crates/project/src/project.rs

Sort of fix for https://github.com/moonrepo/moon/issues/1582

fix: Fix internal tasks showing up in queries.

---

.github/workflows/rust.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
crates/app/Cargo.toml
crates/app/src/commands/query.rs
crates/app/src/commands/run.rs
crates/cli/Cargo.toml
crates/common/src/consts.rs
crates/query/Cargo.toml
crates/vcs/Cargo.toml
legacy/core/test-utils/Cargo.toml
legacy/rust/lang/Cargo.toml

internal: Update dependencies.

---

.yarn/versions/be4e77ac.yml
CHANGELOG.md
crates/vcs-hooks/src/hooks_generator.rs
crates/vcs-hooks/tests/hooks_generator_test.rs

Fixes https://github.com/moonrepo/moon/issues/1683

fix: Fix invalid path separators for hook files.

---

.yarn/versions/be4e77ac.yml
CHANGELOG.md
crates/actions/src/actions/setup_toolchain.rs
crates/config/src/project/task_config.rs
crates/config/src/project/task_options_config.rs
crates/config/tests/inherited_tasks_config_test.rs
crates/config/tests/task_config_test.rs
crates/task-builder/src/tasks_builder.rs
crates/task-builder/tests/__fixtures__/builder/global/tasks/tag-merge.yml
crates/task-builder/tests/__fixtures__/builder/merge-append/moon.yml
crates/task-builder/tests/__fixtures__/builder/merge-prepend/moon.yml
crates/task-builder/tests/__fixtures__/builder/merge-preserve/moon.yml
crates/task-builder/tests/__fixtures__/builder/merge-replace-empty/moon.yml
crates/task-builder/tests/__fixtures__/builder/merge-replace-undefined/moon.yml
crates/task-builder/tests/__fixtures__/builder/merge-replace/moon.yml
crates/task-builder/tests/tasks_builder_test.rs
packages/types/src/project-config.ts
packages/types/src/tasks-config.ts
website/docs/concepts/task-inheritance.mdx
website/docs/config/project.mdx
website/static/schemas/project.json
website/static/schemas/tasks.json

Fixes https://github.com/moonrepo/moon/issues/1685

fix: Fix replace merge strategy wiping out fields.

---

CHANGELOG.md
crates/affected/src/affected.rs
crates/affected/src/affected_tracker.rs
crates/app/src/queries/projects.rs
crates/cli/tests/query_test.rs

Fixes https://github.com/moonrepo/moon/issues/1684

fix: Fix `moon query projects` issues.

---

CHANGELOG.md
crates/app/src/commands/upgrade.rs
crates/config/src/toolchain_config.rs
crates/project-expander/src/token_expander.rs
crates/project-expander/tests/token_expander_test.rs
packages/types/src/toolchain-config.ts
website/docs/config/toolchain.mdx
website/static/schemas/toolchain.json

Fixes https://github.com/moonrepo/moon/issues/1679

fix: Fix token + env variable substitution.

---

README.md

Just thought it looked slightly better

Made the moon acronym bold and italic for better visibility

---

CHANGELOG.md
crates/cli/tests/run_python_test.rs
crates/process/Cargo.toml
crates/vcs/src/git.rs
crates/vcs/src/git_submodule.rs
crates/vcs/src/git_worktree.rs
crates/vcs/src/lib.rs
crates/vcs/tests/git_test.rs
legacy/python/tool/src/python_tool.rs

Fixes https://github.com/moonrepo/moon/issues/1756

fix: Fix hooks dir for Git submodules/worktrees.

---

CHANGELOG.md
crates/action-graph/src/action_graph_builder.rs
crates/action-graph/tests/action_graph_test.rs
crates/action-graph/tests/snapshots/action_graph_test__action_graph__run_from_requirements__runs_by_project_glob.snap
crates/action-graph/tests/snapshots/action_graph_test__action_graph__run_from_requirements__runs_by_tag_glob.snap
crates/action-graph/tests/snapshots/action_graph_test__action_graph__run_from_requirements__runs_by_task_glob.snap
crates/app/src/commands/ci.rs
crates/target/src/target_locator.rs
crates/target/tests/target_locator_test.rs

Implements https://github.com/moonrepo/moon/issues/1762

new: Support glob based targets.

---

CHANGELOG.md
crates/app/src/app.rs
crates/app/src/commands/templates.rs
crates/cli/src/main.rs
crates/codegen/Cargo.toml
crates/codegen/src/codegen.rs
crates/codegen/src/templates_command.rs
crates/codegen/tests/codegen_test.rs
crates/config/src/template/template_locator.rs
crates/config/tests/workspace_config_test.rs
crates/task-runner/src/command_executor.rs
crates/task-runner/src/task_runner.rs
website/docs/commands/run.mdx
website/docs/guides/codegen.mdx

Based on this thread https://github.com/moonrepo/moon/issues/1385

new: Codegen improvements.

---

website/docs/install.mdx
website/docs/proto/install.mdx
website/src/components/Products/Proto/HeroTerminal.tsx
website/src/pages/proto.tsx
website/static/install/proto.ps1
website/static/install/proto.sh

Fixes https://github.com/moonrepo/proto/issues/692

fix: Rework proto install script.

---

CHANGELOG.md
crates/app/src/commands/graph/action.rs
crates/app/src/commands/graph/project.rs
crates/app/src/commands/graph/task.rs
crates/app/src/commands/graph/utils.rs
crates/codegen/src/codegen.rs

Fixes https://github.com/moonrepo/moon/issues/1843 https://github.com/moonrepo/moon/issues/1844 https://github.com/moonrepo/moon/issues/1841

fix: Audit 02/26

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/action-graph/Cargo.toml
crates/action-graph/src/action_graph_builder.rs
crates/app/src/session.rs
crates/app/src/systems/startup.rs
crates/cli/tests/run_test.rs
crates/env/src/lib.rs
packages/cli/moonx.js
packages/cli/package.json
website/docs/concepts/target.mdx
yarn.lock

Fixes https://github.com/moonrepo/moon/issues/1828 and https://github.com/moonrepo/moon/issues/1805

new: Add `moonx` and other new features.

---

.moon/toolchain.yml
CHANGELOG.md
crates/action-graph/src/action_graph_builder.rs
crates/action-graph/tests/action_graph_test.rs
crates/action-graph/tests/utils.rs
crates/action-pipeline/src/action_pipeline.rs
crates/action-pipeline/src/action_runner.rs
crates/action-pipeline/src/job_context.rs
crates/actions/src/actions/install_deps.rs
crates/actions/src/actions/run_task.rs
crates/actions/src/actions/setup_toolchain_plugin.rs
crates/actions/src/actions/sync_project.rs
crates/actions/src/actions/sync_workspace.rs
crates/affected/src/affected_tracker.rs
crates/affected/tests/affected_tracker_test.rs
crates/app/src/commands/ci.rs
crates/app/src/commands/docker/setup.rs
crates/app/src/commands/graph/action.rs
crates/app/src/commands/query.rs
crates/app/src/commands/run.rs
crates/app/src/commands/sync.rs
crates/app/src/commands/syncs/projects.rs
crates/app/src/session.rs
crates/plugin/src/host.rs
crates/plugin/tests/plugin_registry_test.rs
crates/test-utils/src/app_context_mocker.rs
crates/workspace/src/projects_locator.rs
rust-toolchain.toml

This aligns with how other components work.

internal: Wrap workspace graph in an `Arc`.
