crates/toolchain/src/helpers.rs, crates/toolchain/src/lib.rs, crates/toolchain/src/tool.rs, crates/toolchain/src/toolchain.rs, crates/toolchain/src/tools/node.rs, crates/toolchain/src/tools/npm.rs, crates/toolchain/src/tools/pnpm.rs, crates/toolchain/src/tools/yarn.rs, crates/workspace/src/task_runner.rs, crates/workspace/src/tasks/run_target.rs, yarn.lock
Otherwise nvm shims would take precedence and break our runner.
=> new: Set `PATH` env var when running binaries.

.moon/workspace.yml, Cargo.lock, crates/config/Cargo.toml, crates/config/src/package.rs, crates/config/src/tsconfig.rs, crates/toolchain/src/toolchain.rs, docs/roadmap.md, package.json
Serde doesn't preserve field order (https://github.com/serde-rs/json/issues/858), which results in these files constantly being mutated and creating diffs.
=> fix: Use `json` crate for writing package.json/tsconfig.json.

crates/cache/src/engine.rs, crates/cache/src/items.rs, crates/cli/src/commands/bin.rs, crates/cli/src/commands/setup.rs, crates/toolchain/src/tool.rs, crates/toolchain/src/toolchain.rs, crates/toolchain/src/tools/node.rs, crates/toolchain/src/tools/npm.rs, crates/toolchain/src/tools/pnpm.rs, crates/toolchain/src/tools/yarn.rs, crates/workspace/src/tasks/setup_toolchain.rs
Running `--version` as a child process on every run adds considerable overhead, so only do this once every 12 hours (basically once every work day).
=> new: Defer version checks of package managers.

Cargo.lock, crates/config/Cargo.toml, crates/config/src/project/task.rs
A little bit cleaner for consumers.
=> new: Support a string value for task `args`.

crates/config/src/project/global.rs, crates/config/src/project/mod.rs, crates/config/src/workspace/mod.rs
Building documentation resulted in warnings due to bare URL's, switching to automatic URL's to resolve
=> Changing URL's to automatic URL's to suppress warnings

.github/workflows/release-npm.yml, .github/workflows/release.yml, scripts/release-workflow.md
My last few attempts to release have failed, as the workflow never runs. It turns out that pushing more than 3 tags _does not_ trigger the workflow, wtf! https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
Moving this to manual dispatches.
=> ci: Switch to manual releases.

crates/cli/src/main.rs, website/docs/install.mdx
I want moon to accomplish 2 things:
- The `moon` binary version is pinned in the root dependencies.
- Developers can also run `moon` as a global and bypass package scripts.
These are both conflicting ideas. If moon is installed as a dependency in the root `package.json`, then you simply can't run `moon` without doing `yarn moon`. If you install moon globally, then you run the risk of version drift.
This PR attempts to resolve both of these by doing the following:
- At the start of the CLI, _before_ clap parses arguments, we detect if the running executable has been installed globally.
- If so, then we attempt to find the `moon` binary in the repos `node_modules`.
- If found, we execute that binary instead of the currently running one. 
If none of these conditions are true, then we just …
=> new: Support being installed globally.

Cargo.lock, crates/cache/Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/commands/init.rs, crates/cli/src/lib.rs, crates/cli/tests/init_test.rs, crates/config/Cargo.toml, crates/config/src/lib.rs, crates/config/src/project/global.rs, crates/config/src/project/mod.rs, crates/config/src/workspace/mod.rs, crates/config/src/workspace/node.rs, crates/config/templates/global_project.yml, crates/config/templates/workspace.yml, crates/error/Cargo.toml, crates/logger/Cargo.toml, crates/project/Cargo.toml, crates/terminal/Cargo.toml, crates/terminal/src/lib.rs, crates/terminal/src/theme.rs, crates/toolchain/Cargo.toml, crates/utils/Cargo.toml, crates/workspace/Cargo.toml, website/docs/commands/init.mdx, website/docs/guides/examples/eslint.mdx, website/docs/install.mdx
This vastly improves the `init` command and makes it easier to adopt moon. The command will now:
- Infer the Node.js version from any nvm/nodenv file.
- Infer the package manager based on config and lock files.
- Infer the package manager version from the `packageManager` field.
- Infer projects from the `workspaces` field.
It also uses actual template rendering via Tera.
Implements https://github.com/moonrepo/moon/issues/101
=> new: Infer settings and environment during `init`. [#101]

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/init.rs, crates/cli/src/main.rs, crates/config/Cargo.toml, crates/config/src/workspace/node.rs, crates/lang-node/Cargo.toml, crates/lang-node/src/lib.rs, crates/lang-node/src/node.rs, crates/lang/Cargo.toml, crates/lang/src/error.rs, crates/lang/src/lib.rs, crates/toolchain/Cargo.toml, crates/toolchain/src/errors.rs, crates/toolchain/src/helpers.rs, crates/toolchain/src/pms/npm.rs, crates/toolchain/src/pms/pnpm.rs, crates/toolchain/src/pms/yarn.rs, crates/toolchain/src/tools/node.rs, crates/toolchain/src/traits.rs, crates/toolchain/tests/node_test.rs, crates/toolchain/tests/npm_test.rs, crates/toolchain/tests/pnpm_test.rs, crates/toolchain/tests/yarn_test.rs, crates/workspace/Cargo.toml, crates/workspace/src/actions/install_node_deps.rs, crates/workspace/src/actions/run_target.rs
This PR adds language based crates, starting with Node.js. I wanted a place that stored all metadata and utils unique to the language, its package managers, and any version managers.
The other crates like toolchain and config then utilize this.
=> new: Add language crates.

.yarn/versions/cb91120d.yml, packages/cli/package.json
While this worked for npm, this breaks Yarn 2 since it filters packages that don't align.
=> fix: Remove os/arch/etc from CLI package.

.github/workflows/rust-stub.yml, .github/workflows/rust.yml, .yarn/versions/005acb02.yml, CONTRIBUTING.md, Makefile.toml, crates/cli/tests/project_test.rs, crates/cli/tests/snapshots/project_test__advanced_config.snap, crates/cli/tests/snapshots/project_test__basic_config.snap, crates/cli/tests/snapshots/project_test__depends_on_paths.snap, crates/cli/tests/snapshots/project_test__empty_config.snap, crates/cli/tests/snapshots/project_test__no_config.snap, crates/cli/tests/snapshots/project_test__unknown_project.snap, crates/cli/tests/snapshots/project_test__with_tasks.snap, crates/cli/tests/snapshots/run_test__node__inherits_moon_env_vars.snap, crates/cli/tests/snapshots/run_test__system__inherits_moon_env_vars.snap, crates/utils/src/process.rs, crates/utils/src/test.rs
Our code coverage works, but it was an issue where each OS uploads there report at different intervals, resulting in the GitHub PR comment representing an invalid state. This is especially true for Windows, which is reported like 5 minutes after the others.
This changes code coverage to upload all 3 reports at the same time, hopefully generating a more accurate coverage percentage.
Edit: Looks like windows doesn't work at all...
=> ci: Upload code coverage as a batch.

.github/workflows/rust.yml
This increases CI times by 10 minutes... let's not use it.
=> ci: Remove `cargo-make` usage in CI workflows.

crates/cli/src/commands/project.rs, crates/cli/tests/snapshots/project_test__advanced_config.snap, crates/cli/tests/snapshots/project_test__basic_config.snap, crates/cli/tests/snapshots/project_test__depends_on_paths.snap, crates/cli/tests/snapshots/project_test__empty_config.snap, crates/cli/tests/snapshots/project_test__with_tasks.snap, crates/config/src/project/mod.rs, crates/project/tests/project_test.rs, packages/cli/CHANGELOG.md, tests/fixtures/projects/advanced/project.yml, website/docs/config/project.mdx, website/static/schemas/project.json
This allows the type to be configured without having to define all the `project` metadata.
=> breaking: Move `type` setting in `project.yml` to the top-level.

.github/workflows/rust.yml, Makefile.toml
When code coverage is ran, it generates a ton of `.profraw` files in the root, and a handful of nested folders. I noticed that  missing coverage is for tests that run the binary as a child process using `assert_cmd`, which places `.profraw` files in nested folders. I have a feeling that grcov does not recursively find these files and only checks the root.
After many attempts, I found that using an absolute file path for `LLVM_PROFILE_FILE` bumps coverage from 70% -> 85%. Success!
=> ci: Write all `.profraw` files to the root for consistent code coverage.

.yarn/versions/ec726743.yml, crates/cli/src/commands/ci.rs, crates/project/src/project.rs, crates/workspace/src/dep_graph.rs, packages/cli/CHANGELOG.md
The `project.is_affected()` call was an old implementation that assumed all task inputs start with the project source. This isn't true because tasks can also reference workspace relative files.
Because of this, some targets wouldn't run in CI correctly.
=> fix: Fix tasks referencing workspace files not being affected.

.yarn/versions/a73d03ac.yml, crates/utils/src/process.rs, packages/cli/CHANGELOG.md
When you set `--color`, piped colors work correctly because we set `FORCE_COLOR`. For other scenarios, colors are lost. This was an oversight on my part.
This now will simply inherit color settings from your terminal and force them for the child process.
=> fix: Fix colors not being inherited correctly.

.moon/workspace.yml, crates/cli/src/commands/ci.rs, crates/cli/src/commands/run.rs, crates/workspace/src/actions/hashing/target.rs, crates/workspace/src/vcs/git.rs, crates/workspace/src/vcs/svn.rs, crates/workspace/src/workspace.rs, packages/cli/CHANGELOG.md
We were constantly calling `git status` and `git ls-tree` commands. This should greatly reduce that.
=> new: Add caching to VCS layer.

crates/utils/src/process.rs, packages/cli/CHANGELOG.md, packages/runtime/src/context.ts
Our Windows implementation assumes `cmd.exe` for running `.cmd/.bat` files. While this works, `cmd.exe` is a very old terminal and may cause issues when a developer is using PowerShell or Windows Terminal.
This change reads the `COMSPEC` env vars to try and determine the current shell and use that instead. This should maybe resolve https://github.com/moonrepo/moon/issues/154
=> new: Add COMSPEC support for Windows.

.moon/workspace.yml, Cargo.lock, crates/action-runner/src/actions/target/node.rs, crates/lang-node/Cargo.toml, crates/lang-node/src/node.rs, crates/utils/src/process.rs, packages/cli/CHANGELOG.md
Previously, moon would execute the `node_modules/.bin/*.cmd` files directly with cmd.exe when running a task. This worked and is how Node.js package managers also work. 
However, with this approach, we can't pass Node.js CLI arguments directly and must use `NODE_OPTIONS`. This worked until we needed to support [CPU/heap profiling](https://github.com/moonrepo/moon/pull/181), and as it turns out, not every argument can be passed to `NODE_OPTIONS`. Because of this restriction, that PR is currently blocked.
To work around this issue, I'm updating the Windows logic to execute the package binary directly with node.exe. This is rather complicated since it's impossible to infer the npm package name from the binary... but, the `*.cmd` file contains a relative path to the binary. So now I'm …
=> internal: Run package binaries directly on Windows.

crates/action/src/run_target.rs, crates/action/src/sync_node_project.rs, crates/cli/src/commands/project.rs, crates/cli/src/commands/run.rs, crates/cli/tests/run_test.rs, crates/cli/tests/utils.rs, crates/hasher/src/hasher.rs, crates/lang-node/src/node.rs, crates/lang-node/src/package.rs, crates/lang-node/src/tsconfig.rs, crates/lang/src/lib.rs, crates/logger/src/color.rs, crates/project/src/project.rs, crates/project/src/token.rs, crates/terminal/src/helpers.rs, crates/terminal/src/output.rs, crates/terminal/src/terminal.rs, crates/toolchain/src/pms/npm.rs, crates/toolchain/src/pms/pnpm.rs, crates/toolchain/src/pms/yarn.rs, crates/toolchain/src/tools/node.rs, crates/utils/src/fs.rs, crates/utils/src/glob.rs, crates/utils/src/path.rs, crates/utils/src/process.rs, crates/utils/src/test.rs, crates/workspace/src/workspace.rs
All of our shared code/utils should be using `AsRef`, so this starts that initial process.
=> internal: Migrate to `AsRef`.

crates/project/src/task.rs, packages/cli/CHANGELOG.md, website/docs/config/project.mdx, website/docs/guides/ci.mdx
This is a rather popular name for this.
=> new: Support `dev` as a non-CI task ID.

crates/action-runner/src/dep_graph.rs, crates/action-runner/tests/dep_graph_test.rs, crates/action/src/sync_node_project.rs, crates/cli/src/commands/ci.rs, crates/cli/tests/run_test.rs, crates/cli/tests/snapshots/run_test__caching__creates_run_state_cache.snap, crates/config/src/workspace/mod.rs, crates/project/src/project.rs, crates/project/src/project_graph.rs, crates/project/src/task.rs, crates/project/src/test.rs, crates/project/src/token.rs, crates/project/tests/project_graph_test.rs, crates/project/tests/project_test.rs, crates/toolchain/src/toolchain.rs, crates/utils/src/regex.rs, crates/vcs/src/loader.rs, crates/workspace/src/workspace.rs, packages/cli/CHANGELOG.md, website/docs/concepts/token.mdx, website/docs/config/workspace.mdx
This adds a new setting, `actionRunner.implicitInputs` to `.moon/workspace.yml`, that defines inputs that are inherited by all tasks. This replaces the hard-coded "globally affected" logic.
=> new: Support implicit inputs for all tasks.

crates/action/src/run_target.rs, crates/cli/tests/dep_graph_test.rs, crates/cli/tests/run_test.rs, crates/cli/tests/snapshots/run_test__caching__creates_run_state_cache.snap, crates/cli/tests/snapshots/run_test__noop__runs_noop.snap, crates/cli/tests/snapshots/run_test__noop__runs_noop_deps.snap, crates/project/src/task.rs, packages/cli/CHANGELOG.md, tests/fixtures/cases/.moon/workspace.yml, tests/fixtures/cases/noop/project.yml, website/docs/config/project.mdx
Useful for grouping tasks in parallel, but not actually executing anything.
=> new: Add `noop` (no operation) command support to tasks.

crates/action/src/install_node_deps.rs, crates/action/src/sync_node_project.rs, crates/lang-node/src/package.rs, crates/lang-node/src/tsconfig.rs, crates/lang/src/config.rs, packages/cli/CHANGELOG.md
I would still see random race conditions, so this solves it with a new method that locks the cache and syncs with the file system. Ideally this is rather quick and doesn't run into deadlocks.
=> internal: Refactor language config caching.

crates/action/src/target/hasher.rs, packages/cli/CHANGELOG.md
Noticed that calls to `git hash-object` were not being cached correctly because the order of files in the input kept changing, so this sorts them.
=> fix: Fix file hashing cache being busted.

README.md, packages/cli/README.md, website/docs/commands/migrate/from-package-json.mdx, website/docs/commands/project-graph.mdx, website/docs/commands/project.mdx, website/docs/commands/query/projects.mdx, website/docs/commands/run.mdx, website/docs/concepts/project.mdx, website/docs/concepts/target.mdx, website/docs/concepts/task.mdx, website/docs/concepts/token.mdx, website/docs/config/project.mdx, website/docs/config/workspace.mdx, website/docs/create-project.mdx, website/docs/faq.mdx, website/docs/intro.mdx, website/docs/run-task.mdx
Easier to understand. This is just for docs, internals will still use ID.
=> docs: Rename ID to name.

.yarn/versions/98a21dcd.yml, crates/action/src/install_node_deps.rs, crates/toolchain/src/pms/pnpm.rs, crates/toolchain/src/pms/yarn.rs, crates/toolchain/src/tools/node.rs, packages/cli/CHANGELOG.md
Most of our tests explicitly set the version, but using the defaults should be acceptable.
=> fix: Fix pnpm/yarn crash when version not explicitly set.

.yarn/versions/da55504b.yml, crates/vcs/src/git.rs, crates/vcs/src/svn.rs, packages/cli/CHANGELOG.md
Right now moon assumes it's at the root.
=> fix: Find the VCS root when configured in a sub-folder.

crates/cli/tests/snapshots/migrate_test__from_package_json__converts_scripts-2.snap, crates/cli/tests/snapshots/migrate_test__from_package_json__links_depends_on-2.snap, crates/config/src/project/task.rs, crates/platform-node/src/task.rs, crates/project/src/project.rs, crates/project/tests/project_test.rs, crates/utils/src/regex.rs, packages/cli/CHANGELOG.md
More automation behind the scenes is always better than consumers having to explicitly define these.
=> new: Infer task type based on the command name.

.yarn/versions/34364e45.yml, crates/action/src/target/runner.rs, crates/config/src/project/task.rs, crates/project/tests/project_test.rs, crates/task/src/task.rs
I would like to be able to run multiple `dev`-style tasks at the same time - for example, I have a Remix application and run both a Remix dev server and a Tailwind CSS dev server simultaneously. With moon, that looks something like this:
```yaml
tasks:
dev:
command: noop
deps:
- app:dev-css
- app:dev-remix
dev-css:
command: tailwindcss
args: -w -i styles/app.css -o app/styles/app.css
dev-remix:
command: remix
args: dev
```
Currently though, moon only streams the output of the primary task, so running `moon run app:dev` runs both dev servers, but prints nothing.
This PR adds a new task option named `streamOutput` that when true, streams the output of the task, even if it is not the primary task:
```yaml
dev:
command: noop
deps:
- app:dev-css
- app:dev-remix
dev-css:
command: tailwindcss …
```
=> new: Add an `outputStyle` option to  tasks.

Cargo.lock, crates/config/src/project/task.rs, crates/project/src/project.rs, crates/project/tests/project_test.rs, crates/task/Cargo.toml, crates/task/src/errors.rs, crates/task/src/lib.rs, crates/task/src/task.rs, crates/task/src/test.rs, crates/task/src/token.rs, crates/task/tests/task_test.rs, crates/task/tests/token_test.rs, website/docs/config/project.mdx, website/static/schemas/global-project.json, website/static/schemas/project.json
This is a much cleaner and easier approach to using multiple environment variables.
=> new: Add `.env` support with the `envFile` task option.

Cargo.lock, crates/action/src/target/node.rs, crates/cli/tests/run_node_test.rs, crates/lang-node/Cargo.toml, crates/lang-node/src/node.rs, crates/toolchain/src/pms/npm.rs, crates/toolchain/src/pms/pnpm.rs, crates/toolchain/src/pms/yarn.rs, crates/toolchain/src/tools/node.rs, crates/toolchain/src/traits.rs, crates/utils/src/test.rs, packages/cli/CHANGELOG.md, tests/fixtures/node/.moon/workspace.yml, tests/fixtures/node/esbuild/index.js, tests/fixtures/node/esbuild/moon.yml, tests/fixtures/node/esbuild/package.json, tests/fixtures/node/package.json, tests/fixtures/node/swc/index.js, tests/fixtures/node/swc/moon.yml, tests/fixtures/node/swc/package.json, website/docs/guides/profile.mdx
Some npm packages, primarily esbuild and swc, ship non-js code (go and rust respectively). moon crashes when trying to read these files since they are binary, not utf-8, so this attempts to resolve that.
Fixes https://github.com/moonrepo/moon/issues/261
=> fix: Ensure rust/go binaries in node modules work.

.eslintrc.js, .moon/project.yml, package.json, prettier.config.js, tsconfig.options.json, website/.eslintrc.js, website/docs/guides/examples/eslint.mdx, website/docs/guides/examples/typescript.mdx, website/docusaurus.config.js, website/package.json, website/sidebars.js, yarn.lock
Spun up a new repo to house eslint/jest/etc configs (https://github.com/moonrepo/dev) and this PR migrates to it.
=> new: Migrate to new `moon` developer tooling configs.

crates/cli/src/app.rs, crates/cli/src/commands/query.rs, crates/cli/src/lib.rs, crates/cli/src/queries/projects.rs, crates/cli/tests/query_test.rs, crates/project/src/project.rs, crates/task/src/task.rs, packages/cli/CHANGELOG.md, website/docs/commands/query/projects.mdx
Provides more control to consumers.
=> new: Add `--affected` to `moon query projects`.

.yarn/versions/0179ff1c.yml, crates/utils/src/fs.rs, packages/cli/CHANGELOG.md
Note to self, test moon in Docker.
=> fix: Fix creation time metadata failures in unsupported environments.

scripts/helpers.mjs
So I just discovered that the published arm64 npm packages don't actually have a `moon` binary file included in the package, and I tracked it down to a typo of mine in `targetToPackage`. 🙈 
Since the `x86_64` targets are listed last, it thankfully didn't actually publish arm packages as x86, but this typo did prevent the arm packages from actually releasing.
=> Fix typo for arm64 in targetToPackage

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/commands/generate.rs, crates/cli/src/lib.rs, crates/cli/tests/generate_test.rs, crates/cli/tests/snapshots/generate_test__errors_when_parsing_custom_var_types.snap, crates/cli/tests/snapshots/generate_test__renders_with_custom_vars_via_args-2.snap, crates/cli/tests/snapshots/generate_test__renders_with_custom_vars_via_args.snap, crates/generator/src/errors.rs, website/docs/commands/generate.mdx, website/src/components/ComparisonTable.tsx
As the title states. Any arguments defined after `--` when running `moon generate` will be considered template variables.
=> new: Allow template variables to be defined with CLI arguments.

CONTRIBUTING.md
Cannot run test-coverage without git>=2.28, Ubuntu 20.04 users for example will currently only be pulling git=2.25 from apt.
=> QOL: making test-coverage requires git>=2.28 for git's initial-step flag

.yarn/versions/654e700a.yml, crates/platform-node/src/lib.rs, packages/cli/CHANGELOG.md
This change was a side-effect of the implicit dependency scanning where the alias logic was still running even when extracting aliases was disabled.
=> fix: Fix alias scanning logging warnings.

crates/utils/src/process.rs, packages/cli/CHANGELOG.md, website/src/pages/index.tsx
cmd.exe is just very problematic, especially around file paths and quoting. This defaults to powershell to avoid these issues.
=> fix: Use PowerShell as the default Windows shell.

.yarn/versions/334e6c8f.yml, crates/action-runner/src/runner.rs, crates/action/src/action.rs, crates/cache/src/items.rs, crates/cache/src/lib.rs, crates/cache/src/reports.rs, packages/types/src/runner.ts
Includes the total duration and data around how much time has been saved (estimated). This will then be used by the GH action.
=> new: Include more data in run reports.

crates/action-runner/src/actions/run_target.rs, crates/cli/tests/run_test.rs, crates/cli/tests/snapshots/run_test__output_styles__stream.snap, crates/logger/src/lib.rs, crates/utils/src/process.rs, packages/cli/CHANGELOG.md
As the title states. The prefixes will now be uniform in width, and be colored to differentiate based on target. It now looks something like the following:
=> new: Improve output prefixes when streaming concurrent tasks.

crates/cli/src/commands/generate.rs, crates/cli/tests/generate_test.rs, crates/cli/tests/snapshots/generate_test__frontmatter__changes_dest_path.snap, crates/cli/tests/snapshots/generate_test__frontmatter__force_writes_file.snap, crates/cli/tests/snapshots/generate_test__frontmatter__supports_component_vars.snap, crates/cli/tests/snapshots/generate_test__renders_and_interpolates_templates-2.snap, crates/cli/tests/snapshots/generate_test__renders_with_custom_vars_via_args-2.snap, crates/config/src/template/frontmatter.rs, crates/config/src/template/mod.rs, crates/generator/src/errors.rs, crates/generator/src/filters.rs, crates/generator/src/generator.rs, crates/generator/src/template.rs, crates/generator/tests/template_test.rs, packages/cli/CHANGELOG.md, tests/fixtures/generator/templates/frontmatter/component.tsx, tests/fixtures/generator/templates/frontmatter/forced.txt, tests/fixtures/generator/templates/frontmatter/skipped.txt, tests/fixtures/generator/templates/frontmatter/template.yml, tests/fixtures/generator/templates/frontmatter/to.txt, website/docs/config/template.mdx, website/docs/guides/codegen.mdx
This PR adds support for frontmatter (via YAML) to all template files. This allows us to provide file level configuration that isn't possible in `.moon/workspace.yml`, `template.yml`, or through CLI arguments.
For example, frontmatter can define a `to` field, which overrides the destination path for the template file in question. This is pretty awesome as it also takes advantage of Tera's rendering engine.
=> new: Support frontmatter in template files.

.moon/workspace.yml, crates/utils/src/lib.rs, crates/utils/src/process.rs, crates/utils/src/shell.rs, crates/vcs/src/git.rs, packages/cli/CHANGELOG.md, tests/fixtures/cases/system-windows/moon.yml, website/docs/faq.mdx, website/src/components/ComparisonTable.tsx
We're still seeing issues for Windows file paths that contain spaces and special characters not executing. 
`cmd.exe` doesn't handle this very well, and it's been a crazy amount of work to get working in Rust. So instead of supporting `cmd.exe`, I'm simply going to drop it for `powershell.exe`, which has existed for a long time. The newer `pwsh.exe` will be used if detected.
However, PS still has problems with file paths as arguments, so to work around this, arguments will now be passed via stdin.
=> breaking: Drop `cmd.exe` for Windows. Rework Windows shell.

Cargo.lock, Cargo.toml, crates/action-runner/Cargo.toml, crates/action/Cargo.toml, crates/cache/Cargo.toml, crates/cli/Cargo.toml, crates/config/Cargo.toml, crates/error/Cargo.toml, crates/generator/Cargo.toml, crates/hasher/Cargo.toml, crates/lang-node/Cargo.toml, crates/platform-node/Cargo.toml, crates/platform-system/Cargo.toml, crates/project-graph/Cargo.toml, crates/project/Cargo.toml, crates/task/Cargo.toml, crates/toolchain/Cargo.toml, crates/utils/Cargo.toml
Minor stuff.
Clap v4 is out, but it's quite a change, so I'll do it in a PR by itself.
=> deps: Update Cargo dependencies.

crates/lang-node/src/node.rs, packages/cli/CHANGELOG.md
This primarily affects pnpm, but should correctly resolve Go/Rust binaries as we now do a double pass.
=> fix: Handle Go/Rust binaries that are wrapped in node modules.

packages/types/src/template-config.ts, website/docs/config/global-project.mdx, website/docs/config/project.mdx, website/docs/config/template.mdx, website/docs/config/workspace.mdx, website/src/components/Docs/HeadingApiLink.tsx
Instead of displaying the setting "type" as a blockquote, this will link to the actual API docs. This is 100x better and actually cleans up the visuals of these config pages.
=> docs: Add links to API types for config settings.

crates/cache/src/engine.rs, crates/cache/tests/engine_test.rs, crates/cli/src/commands/setup.rs, crates/cli/src/commands/sync.rs, crates/contract/src/platform.rs, crates/platform-node/src/actions/install_deps.rs, crates/platform-node/src/actions/run_target.rs, crates/platform-node/src/lib.rs, crates/platform-system/src/lib.rs, crates/runner/src/actions/setup_toolchain.rs, crates/runner/src/dep_graph.rs, crates/runner/src/emitter.rs, crates/runner/src/node.rs, crates/runner/src/runner.rs, crates/runner/tests/dep_graph_test.rs, crates/toolchain/src/manager.rs, crates/toolchain/src/toolchain.rs, packages/cli/CHANGELOG.md, website/docs/terminology.md
The term platform was being overloaded. This refactors the enum to use "runtime" which is a combination of platform + version.
=> internal: Rename platform enum to runtime.

crates/config/src/workspace/runner.rs, crates/project-graph/src/graph.rs, crates/project/src/project.rs, crates/project/tests/project_test.rs, packages/cli/CHANGELOG.md, packages/types/src/workspace-config.ts, website/docs/config/workspace.mdx, website/src/components/ComparisonTable.tsx, website/static/schemas/workspace.json
This provides a way for task dependencies to be defined globally.
=> new: Add `runner.implicitDeps` setting.

.yarn/versions/e1f8405e.yml, crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces.snap, crates/cli/tests/snapshots/init_test__node__infers_globs_from_workspaces_expanded.snap, crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces.snap, crates/cli/tests/snapshots/init_test__node__infers_projects_from_workspaces_expanded.snap, crates/cli/tests/snapshots/init_test__node__infers_version_from_nodenv.snap, crates/cli/tests/snapshots/init_test__node__infers_version_from_nvm.snap, crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm.snap, crates/cli/tests/snapshots/init_test__node__package_manager__infers_npm_from_package.snap, crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm.snap, crates/cli/tests/snapshots/init_test__node__package_manager__infers_pnpm_from_package.snap, crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn.snap, crates/cli/tests/snapshots/init_test__node__package_manager__infers_yarn_from_package.snap, crates/config/templates/global_project.yml, crates/config/templates/project.yml, crates/config/templates/template.yml, crates/config/templates/workspace.yml
The `node.aliasPackageNames` setting was using an incorrect value.
=> fix: Rework `init` config templates to use correct values.

crates/toolchain/src/errors.rs, crates/toolchain/src/helpers.rs, packages/cli/CHANGELOG.md
This was an oversight on my part. I assumed that reqwest would throw errors for non-200s, but that's not the case. This fixes that and handles this failure case explicitly.
=> fix: Handle unsuccessful requests when downloading tools.

.github/workflows/rust.yml, Makefile.toml
We can use this action https://github.com/marketplace/actions/rust-cargo-make to avoid the 10m install time for `cargo-make`.
=> ci: Update workflow to use cargo-make.

.cargo/config.toml, .github/workflows/rust-stub.yml, .github/workflows/rust.yml
This enables link-time optimization, which should increase runtime performance. I have no way of benchmarking/verifying this at this time though.
It however does increase release build times by roughly 1 min, which isn't bad.
```
lto=false, non-cpu
cargo build --release  1424.32s user 85.85s system 618% cpu 4:04.21 total
cargo build --release  1345.28s user 70.56s system 721% cpu 3:16.37 total 
= 13.5mb
lto=true, non-cpu
cargo build --release  1252.25s user 71.29s system 457% cpu 4:49.60 total
cargo build --release  1233.79s user 68.33s system 455% cpu 4:46.13 total
= 12.1mb
--- 
RUSTFLAGS="-C target-cpu=native" 
lto=false, cpu
cargo build --release  1406.34s user 73.71s system 662% cpu 3:43.44 total
cargo build --release  1409.73s user 76.49s system 652% cpu 3:47.62 total
= 13.6mb …
```
=> build: Enable LTO.

crates/generator/tests/generator_test.rs, crates/utils/src/regex.rs, packages/cli/CHANGELOG.md
This has much better readability for common cases.
=> breaking: Use dashes when cleaning IDs.

crates/config/src/project/task.rs, crates/config/src/workspace/runner.rs, crates/project-graph/src/graph.rs, crates/project/src/project.rs, crates/project/tests/project_test.rs, crates/runner/src/dep_graph.rs, crates/task/src/target.rs, crates/task/src/task.rs, crates/task/src/test.rs, crates/task/tests/task_test.rs, packages/cli/CHANGELOG.md, packages/types/src/project.ts, tests/fixtures/task-deps/self-no-prefix/moon.yml, website/docs/concepts/target.mdx, website/docs/config/project.mdx
Instead of writing `~:build`, you can simply write `build`. This defaults to the "self" scope.
I've also added the `id` field to tasks, since it's required downstream by tools.
=> new: Support shorthand "self" target scopes.

crates/cli/src/app.rs, crates/cli/src/commands/check.rs, crates/cli/src/lib.rs, crates/cli/tests/check_test.rs, packages/cli/CHANGELOG.md, website/blog/2022-10-21_v0.17.mdx, website/docs/commands/check.mdx
Want this for the VS Code extension!
=> new: Add `--report` support to `moon check`.

Cargo.lock, crates/cli/tests/snapshots/migrate_test__from_package_json__converts_scripts-2.snap, crates/cli/tests/snapshots/migrate_test__from_package_json__links_depends_on-2.snap, crates/config/src/project/task.rs, crates/config/templates/global_project.yml, crates/config/tests/tasks_test.rs, crates/platform-node/src/task.rs, crates/platform-node/tests/task_test.rs, crates/project/tests/project_test.rs, crates/task/Cargo.toml, crates/task/src/task.rs, crates/task/src/token.rs, crates/task/tests/token_test.rs, crates/utils/src/regex.rs, packages/cli/CHANGELOG.md, packages/types/src/project-config.ts, tests/fixtures/cases/base/moon.yml, tests/fixtures/cases/system-windows/moon.yml, tests/fixtures/cases/system/moon.yml, tests/fixtures/tasks/merge-append/moon.yml, tests/fixtures/tasks/merge-prepend/moon.yml, tests/fixtures/tasks/merge-replace/moon.yml, website/blog/2022-10-21_v0.17.mdx, website/docs/concepts/token.mdx, website/docs/config/project.mdx, website/docs/faq.mdx
=> breaking: Rename task `type` to `platform`.

.yarn/versions/de0bc3b3.yml, crates/action/src/action.rs, crates/notifier/src/webhooks.rs, crates/utils/src/time.rs, packages/cli/CHANGELOG.md, packages/types/src/runner.ts
We're already UTC, we don't need the timezone. The upstream service doesn't require it either.
=> internal: Update UTC timestamps to not include timezone information.

crates/cache/src/engine.rs, crates/cache/src/helpers.rs, crates/cache/src/items.rs, crates/cache/tests/engine_test.rs, crates/cli/tests/run_test.rs, crates/platform-node/src/actions/install_deps.rs, crates/project-graph/src/graph.rs, crates/runner/src/actions/run_target.rs, crates/runner/src/actions/setup_toolchain.rs, crates/utils/src/fs.rs, crates/utils/src/time.rs, packages/cli/CHANGELOG.md, website/docs/concepts/cache.mdx
This reworks the cache item layer to write stdout/stderr as their own files, instead of storing them in the item.
=> new: Cache stdout/stderr as individual log files.

crates/cache/src/items/run_target_state.rs, packages/cli/CHANGELOG.md
It's weird that a command would not produce these files, but let's check for this anyways.
=> fix: Fix stdout/stderr logs not existing.

.yarn/versions/5c64ed6a.yml, crates/cli/src/commands/run.rs, crates/cli/tests/dep_graph_test.rs, crates/cli/tests/run_test.rs, crates/cli/tests/snapshots/run_test__caching__creates_run_state_cache.snap, crates/cli/tests/snapshots/run_test__output_styles__hash.snap, crates/cli/tests/snapshots/run_test__system__passthrough__doesnt_pass_to_non_primary.snap, crates/core/action/src/context.rs, crates/core/runner/src/actions/run_target.rs, packages/cli/CHANGELOG.md, packages/types/src/runner.ts, tests/fixtures/cases/.moon/workspace.yml, tests/fixtures/cases/passthrough-args/moon.yml, tests/fixtures/cases/passthrough-args/passthroughArgs.sh
When running `moon run :build -- --arg`, the `--arg` _should only_ be passed to `:build` targets and not their dependencies.
=> fix: Fix passthrough args being passed to dependent targets.

crates/cli/src/commands/bin.rs, crates/cli/src/commands/init/node.rs, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__node__tests__renders_alias_and_tasks.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__node__tests__renders_default.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__node__tests__renders_nodenv.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__node__tests__renders_nvm.snap, crates/cli/src/commands/node/run_script.rs, crates/cli/tests/run_node_test.rs, crates/cli/tests/snapshots/run_node_test__engines__adds_engines_constraint.snap, crates/core/config/src/workspace/node.rs, crates/core/config/templates/workspace_node.yml, crates/core/toolchain/src/helpers.rs, crates/core/toolchain/src/pms/npm.rs, crates/core/toolchain/src/pms/pnpm.rs, crates/core/toolchain/src/pms/yarn.rs, crates/core/toolchain/src/tools/node.rs, crates/core/toolchain/src/traits.rs, crates/core/toolchain/tests/node_test.rs, crates/core/toolchain/tests/npm_test.rs, crates/core/toolchain/tests/pnpm_test.rs, crates/core/toolchain/tests/yarn_test.rs, crates/core/utils/src/process.rs, crates/node/lang/src/node.rs, crates/node/platform/src/actions/install_deps.rs, crates/node/platform/src/actions/run_target.rs, packages/cli/CHANGELOG.md, tests/fixtures/node/.moon/workspace.yml, tests/fixtures/node/version-override/moon.yml
Up until now, we would install npm/pnpm/yarn into the npm of the current node version of the toolchain. While this worked, it actually causes a ton of issues when multiple repos/projects are all referencing the same node install.
For example, if 3 repos are using node 18, but each one has a different npm version, they would all be colliding with each other. This is even more problematic with corepack.
This change uses a different approach, where package managers are downloaded and installed as separate tools.
=> internal: Rework how package managers work in the toolchain.

crates/cli/src/commands/run.rs, crates/cli/tests/run_test.rs, crates/cli/tests/snapshots/run_system_test__system_windows__caching__creates_run_state_cache.snap, crates/cli/tests/snapshots/run_system_test__unix__caching__creates_run_state_cache.snap, crates/core/action/src/context.rs, crates/core/hasher/src/hasher.rs, crates/core/runner/src/actions/run_target.rs, crates/core/runner/src/actions/setup_toolchain.rs, crates/core/runner/src/runner.rs, crates/node/platform/src/actions/install_deps.rs, crates/node/platform/src/actions/sync_project.rs, packages/cli/CHANGELOG.md, packages/types/src/runner.ts, tests/fixtures/cases/outputs/generate.js, tests/fixtures/cases/outputs/moon.yml
This was an oversight on my part. If A depends on B, and B's hash changes, then A should generate a new hash. This wasn't working previously.
=> fix: Invalidate hashes if a dependencies hash changes.

.moon/project.yml, crates/cli/src/commands/run.rs, crates/cli/tests/run_node_test.rs, crates/cli/tests/run_system_test.rs, crates/cli/tests/snapshots/run_node_test__passes_args_through.snap, crates/cli/tests/snapshots/run_system_test__unix__caching__creates_run_state_cache.snap, crates/cli/tests/snapshots/run_system_test__unix__handles_ls.snap, crates/cli/tests/snapshots/run_system_test__unix__passes_args_through.snap, crates/core/action/src/context.rs, crates/core/config/src/project/task_options.rs, crates/core/project/tests/project_test.rs, crates/core/runner/src/actions/run_target.rs, crates/core/task/src/task.rs, crates/core/task/tests/task_test.rs, crates/core/utils/src/process.rs, crates/core/vcs/src/git.rs, packages/cli/CHANGELOG.md, packages/types/src/project-config.ts, packages/types/src/project.ts, tests/fixtures/node/base/args.js, tests/fixtures/node/base/moon.yml, tests/fixtures/node/base/passthroughArgs.js, tests/fixtures/system/unix/args.sh, tests/fixtures/system/unix/moon.yml, website/.eslintrc.js, website/blog/2022-10-31_v0.18.mdx, website/blog/2022-11-14_v0.19.mdx, website/docs/config/project.mdx, website/docs/guides/git-hooks.mdx, website/sidebars.js
When enabled and `--affected` is passed to `moon run`, a list of affected files for the current task will be passed as CLI arguments.
This is perfect for linting and formatting only a subset of touched files.
=> new: Add `affectedFiles` task option.

crates/core/cache/src/item.rs, packages/cli/CHANGELOG.md
Sometimes the states folder does not exist, and I'm not sure why, but it broke when I refactored this code into a macro. This is my throwing wrenches at the problem.
=> fix: Fix weird item caching issues.

crates/cli/tests/query_test.rs, crates/cli/tests/snapshots/project_graph_test__many_projects.snap, crates/cli/tests/snapshots/run_test__general__logs_command_for_project_root.snap, crates/cli/tests/snapshots/run_test__general__logs_command_for_workspace_root.snap, crates/core/config/src/project/local_config.rs, crates/core/config/src/project/task.rs, crates/core/platform/src/lib.rs, crates/core/project-graph/src/graph.rs, crates/core/project-graph/tests/project_graph_test.rs, crates/core/runner/src/dep_graph.rs, crates/core/runner/src/dep_graph_new.rs, crates/core/runner/tests/dep_graph_test.rs, crates/core/runner/tests/snapshots/dep_graph_test__installs_deps__tool_is_based_on_task_platform.snap, crates/node/platform/src/lib.rs, crates/system/platform/src/lib.rs, packages/cli/CHANGELOG.md, tests/fixtures/cases/base/moon.yml, tests/fixtures/projects/.moon/workspace.yml, tests/fixtures/projects/platforms/moon.yml
This moves the "install deps for tool" action to each task, instead of the project.
=> new: Use task platform instead of project language for installing deps.

crates/core/config/src/workspace/node.rs, crates/core/runner/src/actions/setup_toolchain.rs, packages/cli/CHANGELOG.md
When a project overrides the workspace tool version, we were inheriting the config defaults. We actually need to inherit the config the consumer has defined, with some minor modifications for the overriding.
=> fix: Fix project override config defaults.

.github/workflows/benchmark.yml, Cargo.lock, crates/cli/src/commands/docker/scaffold.rs, crates/cli/tests/snapshots/generate_test__doesnt_generate_files_when_dryrun.snap, crates/cli/tests/snapshots/generate_test__generates_files_from_template.snap, crates/cli/tests/snapshots/generate_test__overwrites_existing_files_when_forced.snap, crates/core/archive/Cargo.toml, crates/core/archive/benches/tar_benchmark.rs, crates/core/archive/src/lib.rs, crates/core/archive/src/tar.rs, crates/core/archive/src/tree_differ.rs, crates/core/archive/src/zip.rs, crates/core/archive/tests/tree_differ_test.rs, crates/core/cache/src/items/run_target_state.rs, crates/core/generator/src/template.rs, crates/core/runner/src/actions/run_target.rs, crates/core/runner/src/subscribers/local_cache.rs, crates/core/utils/Cargo.toml, crates/core/utils/src/fs.rs, crates/core/utils/src/yaml.rs, tests/fixtures/generator/templates/standard/file.txt, website/blog/2022-11-28_v0.20.mdx, website/docs/config/project.mdx
When hydrating outputs from a tarball, we now compare the dest and source files to determine whether to write the source or not. Previously we would just wipe all files before hand, which wasn't very performant. This change has resulted in 10x the speed.
time:   [226.88 ms 235.45 ms 244.67 ms]
time:   [27.861 ms 28.181 ms 28.542 ms]
=> new: Support file system diffing when hydrating outputs.

.yarn/versions/38005fb8.yml, crates/cli/tests/run_test.rs, crates/core/runner/src/actions/run_target.rs, packages/cli/CHANGELOG.md
Ran into this while running against a task that has cache disabled:
```
thread 'tokio-runtime-worker' panicked at 'byte index 8 is out of bounds of ``', crates/core/runner/src/actions/run_target.rs:341:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix: Fix byte out of bounds panic.

crates/cli/src/main.rs, packages/cli/CHANGELOG.md, website/docs/install.mdx
Previously, we only supported npm and would query `npm config get prefix`. 
To avoid this upfront cost of calling out to npm, we have hard-coded the global lookup paths. This allows us to easily support pnpm and yarn.
=> new: Allow moon to be installed globally with pnpm and yarn.

.yarn/versions/95a4fdd8.yml, crates/cli/src/app.rs, crates/cli/src/commands/ci.rs, crates/cli/src/commands/run.rs, crates/cli/src/lib.rs, crates/cli/src/queries/touched_files.rs, crates/cli/tests/query_test.rs, crates/cli/tests/run_test.rs, crates/core/task/src/task_options.rs, packages/cli/CHANGELOG.md, packages/types/src/project-config.ts, packages/types/src/project.ts, tests/fixtures/cases/files/affected.js, tests/fixtures/cases/files/moon.yml, website/blog/2022-12-16_v0.21.mdx, website/docs/commands/query/touched-files.mdx, website/docs/commands/run.mdx, website/docs/run-task.mdx
This expands upon our affected detection by allowing multiple statuses to be used.
=> new: Support multiple `--status` options.

Makefile.toml, crates/cli/tests/run_system_test.rs, crates/cli/tests/snapshots/run_node_test__engines__adds_engines_constraint.snap, crates/node/lang/src/package.rs, crates/typescript/lang/src/tsconfig.rs, packages/cli/CHANGELOG.md
I noticed on Windows that running a task would modify a bunch of package.json/tsconfig.json files, but it wouldn't change it's contents, but would change the newline character.
To combat this, I'm improving the dirty check logic, and improving the test cases.
=> fix: Fix config files unexpectedly changing new lines.

crates/cli/src/app.rs, crates/cli/src/commands/init/mod.rs, crates/cli/src/commands/init/node.rs, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__node__tests__renders_minimal.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__typescript__tests__renders_minimal.snap, crates/cli/src/commands/init/typescript.rs, crates/cli/src/lib.rs, crates/cli/tests/init_node_test.rs, crates/cli/tests/init_test.rs, crates/cli/tests/snapshots/init_node_test__init_node__minimal.snap, crates/core/config/templates/toolchain_node.yml, crates/core/config/templates/toolchain_typescript.yml, packages/cli/CHANGELOG.md, website/blog/2022-12-16_v0.21.mdx, website/docs/setup-workspace.mdx
Provides a simple way to test moon without having to go through all the configuration and "overhead".
=> new: Add `--minimal` option to `moon init`.

crates/core/moonbase/src/api.rs, crates/core/moonbase/src/lib.rs, crates/core/runner/src/subscribers/moonbase_cache.rs, packages/cli/CHANGELOG.md
We will start using these on the backend.
=> new: Use presigned URLs for remote caching.

crates/core/moonbase/src/lib.rs, crates/core/runner/src/subscribers/moonbase_cache.rs, packages/cli/CHANGELOG.md
We're making some changes to the upstream remote caching API, so this change future proofs us.
=> internal: Change artifact upload endpoint.

.yarn/versions/f656d236.yml, Cargo.lock, crates/cli/src/commands/setup.rs, crates/core/config/Cargo.toml, crates/core/config/src/toolchain/config.rs, crates/core/config/src/toolchain/node.rs, crates/core/config/tests/toolchain_test.rs, crates/core/dep-graph/tests/dep_graph_test.rs, crates/core/lang/src/lib.rs, crates/core/moon/src/lib.rs, crates/core/test-utils/src/configs.rs, crates/deno/lang/src/lib.rs, crates/go/lang/src/lib.rs, crates/node/lang/src/lib.rs, crates/node/platform/src/actions/install_deps.rs, crates/node/platform/src/hasher.rs, crates/node/platform/src/platform.rs, crates/node/tool/src/node_tool.rs, crates/php/lang/src/lib.rs, crates/python/lang/src/lib.rs, crates/ruby/lang/src/lib.rs, crates/rust/lang/src/lib.rs, crates/typescript/lang/src/lib.rs, website/static/schemas/toolchain.json
Going forward, the `node` setting will enable the platform, while `node.version` will enable the toolchain. We need to support both scenarios.
This also decouples `node_lang` from `config`, as config is a super crate.
=> internal: Make `node.version` optional and decouple crates.

.yarn/versions/cfd8ae71.yml, crates/cli/tests/run_node_test.rs, crates/cli/tests/snapshots/run_node_test__runs_npm_bin_from_workspace_root.snap, crates/core/runner/src/actions/run_target.rs, crates/node/platform/src/actions/run_target.rs, packages/cli/CHANGELOG.md, tests/fixtures/node/base/moon.yml, tests/fixtures/node/base/package.json
When we run a task, we resolve npm binaries to a relative path from the project directory. But when running in the workspace root, these relative paths are now wrong. This updates the relative logic to use the working dir instead of the project root.
=> fix: Fix `runFromWorkspaceRoot` for node modules.

crates/cli/src/commands/project.rs, crates/cli/src/lib.rs, crates/cli/tests/snapshots/run_test__configs__bubbles_up_invalid_project_config.snap, crates/core/config/src/project/local_config.rs, crates/core/project/tests/project_test.rs, packages/cli/CHANGELOG.md, website/blog/2023-01-17_v0.22.mdx, website/docs/config/project.mdx
Fixes https://github.com/moonrepo/moon/issues/524
Made them all optional except `description`, as that seems the most important.
=> new: Make `project` fields optional.

crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_default.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_git_vcs.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_glob_list.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_projects_map.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_svn_vcs.snap, crates/cli/src/lib.rs, crates/cli/tests/misc_test.rs, crates/cli/tests/snapshots/misc_test__fails_on_version_constraint.snap, crates/core/config/src/validators.rs, crates/core/config/src/workspace/config.rs, crates/core/config/templates/workspace.yml, crates/core/config/tests/workspace_test.rs, crates/core/workspace/src/errors.rs, crates/core/workspace/src/workspace.rs, packages/cli/CHANGELOG.md, packages/types/src/workspace-config.ts, tests/fixtures/node/base/envVarsMoon.js, tests/fixtures/system/unix/envVarsMoon.sh, website/blog/2023-01-17_v0.22.mdx, website/docs/config/workspace.mdx
Allows consumers to enforce a specific moon version.
=> new: Add `versionConstraint` setting to `.moon/workspace.yml`.

crates/cli/src/app.rs, crates/cli/src/commands/check.rs, crates/cli/src/commands/run.rs, crates/cli/src/lib.rs, packages/cli/CHANGELOG.md, website/blog/2023-01-17_v0.22.mdx, website/docs/commands/check.mdx, website/docs/commands/run.mdx, website/docs/editors/vscode.mdx
The report is now always created and this change was made in the previous pipeline PR. This PR merely removes the CLI option.
=> breaking: Remove `--report` option.

Cargo.lock, Cargo.toml, crates/bun/lang/Cargo.toml, crates/bun/lang/src/lib.rs, crates/core/platform-detector/Cargo.toml, crates/core/platform-detector/src/lib.rs, packages/cli/CHANGELOG.md, website/blog/2023-01-17_v0.22.mdx, website/docs/intro.mdx, website/src/components/ComparisonTable.tsx, website/src/components/LangPartials.tsx
While this adds bun, it doesn't really do much since the primary language is still JS/TS. Bun will really be useful once it has Tier 2 support.
=> new: Add Bun as a Tier 1 language.

crates/core/action-pipeline/src/subscribers/moonbase_cache.rs, crates/core/moonbase/src/api.rs, crates/core/moonbase/src/common.rs, crates/core/moonbase/src/errors.rs, crates/core/moonbase/src/lib.rs
We'll be utilizing presigned URLs entirely for this.
=> internal: Migrate to new artifacts endpoints.

crates/core/utils/src/process.rs, packages/cli/CHANGELOG.md
I've noticed that local tasks (web servers) would keep running after moon has exited via ctrl+c, so this attempts to fix that by killing the process when it's dropped out of scope.
=> fix: Fix child processes not being killed.

.moon/tasks.yml, .moon/workspace.yml, crates/cli/src/commands/migrate/from_turborepo.rs, crates/cli/tests/migrate_test.rs, crates/cli/tests/run_system_test.rs, crates/core/config/src/tasks/config.rs, crates/core/config/src/workspace/runner.rs, crates/core/config/tests/global_tasks_test.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/projects_test.rs, crates/core/project/tests/project_test.rs, packages/types/src/project-config.ts, packages/types/src/workspace-config.ts, scripts/release/buildPackages.sh, website/docs/commands/migrate/from-turborepo.mdx, website/docs/config/tasks.mdx, website/docs/config/workspace.mdx, website/static/schemas/tasks.json, website/static/schemas/workspace.json
These settings make much more sense in the new `.moon/tasks.yml` config file then they do in the runner config. Especially with the new inheritance coming in the next version.
=> breaking: Move `implicitDeps` and `implicitInputs`.

.moon/workspace.yml, crates/core/action-pipeline/src/processor.rs, crates/core/action/src/action.rs, packages/cli/CHANGELOG.md
Noticed that durations were kind of off. For example, an attempt was 2 seconds but the overall action duration would be 15 seconds! 
What is happening for those other 13 minutes? I'm assuming this is Tokio jumping between the thread queue.
To remedy this, I'm deferring the start time until it actually starts, instead of time of creation.
=> fix: Fix inaccurate run report action durations.

crates/node/tool/src/pnpm_tool.rs, packages/cli/CHANGELOG.md, website/blog/2023-01-30_v0.23.mdx
This was recently added: https://github.com/pnpm/pnpm/releases/tag/v7.26.0
=> new: Use `pnpm dedupe` when it's available.

.yarn/versions/1b36b2c6.yml, crates/core/launchpad/src/lib.rs
We need to differentiate local vs CI runs.
=> internal: Pass CI information to versions endpoint.

crates/core/action-pipeline/src/actions/run_target.rs, crates/core/platform-runtime/src/version.rs, crates/core/platform/src/platform.rs, crates/core/runner/src/runner.rs, crates/node/platform/src/actions/run_target.rs, crates/node/platform/src/platform.rs, crates/node/tool/src/node_tool.rs, crates/node/tool/src/npm_tool.rs, crates/system/platform/src/platform.rs, packages/cli/CHANGELOG.md
Technically the tool is optional, and is optional when the `version` field in `toolchain.yml` is not set, or is set to null. When this happens, we should default to the global "node" found in the user's shell.
=> fix: Fix issues around the Node.js tool not being configured.

.yarn/versions/22ae79cb.yml, crates/core/action-pipeline/src/pipeline.rs, crates/core/action-pipeline/src/subscribers/moonbase_cache.rs, crates/core/moonbase/src/api.rs, crates/core/moonbase/src/lib.rs, crates/core/workspace/src/workspace.rs, packages/cli/CHANGELOG.md, website/docs/guides/remote-cache.mdx
We'll be launching our remote caching service real real soon. This makes the final changes in preparation for that.
=> internal: Require a subscription for remote caching.

crates/proto/cli/src/bin.rs, crates/proto/cli/src/commands/bin.rs, crates/proto/cli/src/commands/global.rs, crates/proto/cli/src/commands/install.rs, crates/proto/cli/src/commands/list.rs, crates/proto/cli/src/commands/list_remote.rs, crates/proto/cli/src/commands/local.rs, crates/proto/cli/src/commands/mod.rs, crates/proto/cli/src/commands/run.rs, crates/proto/cli/src/commands/uninstall.rs, crates/proto/cli/src/config.rs, crates/proto/cli/src/helpers.rs, crates/proto/cli/src/lib.rs, crates/proto/error/src/lib.rs
One step closer to finalizing the proto CLI!
=> internal: Add `bin`, `global`, and `local` commands for proto.

crates/cli/src/app.rs, crates/cli/src/commands/query.rs, crates/cli/src/lib.rs
```shell
$ cargo run -- query tasks
types
:build | packemon
:format | prettier
:lint | eslint
:test | jest
:typecheck | tsc
report
:build | packemon
:format | prettier
:lint | eslint
:test | jest
:typecheck | tsc
runtime
:build | packemon
:format | prettier
:lint | eslint
:test | jest
:typecheck | tsc
visualizer
:build | vite
:dev | vite
:format | prettier
:lint | eslint
:serve | vite
:test | jest
:typecheck | tsc
website
:build | docusaurus
:format | prettier
:lint | eslint
:start | docusaurus
:test | jest
:typecheck | tsc
```
=> new: Add `moon query tasks` command.

.yarn/versions/7f63437c.yml, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/commands/mod.rs, crates/cli/src/commands/upgrade.rs, crates/cli/src/lib.rs, crates/core/launchpad/src/lib.rs
Hey!
I'm tinkering with #526. Are you open to something like this?
This doesn't consider installs through yarn and other methods. Maybe we could hide this command behind an `upgrade` feature and not compile it for distribution to npm?
=> Introduce upgrade command in CLI

.github/workflows/release.yml, .github/workflows/rust.yml, packages/cli/CHANGELOG.md, scripts/Dockerfile
Problem: https://moonrepo.dev/docs/faq#how-to-resolve-the-version-glibc_xxx-not-found-error
This attempts to fix it by building against Ubuntu 20, instead of Ubuntu 22, which should have an older and more compatible GLIBC.
=> fix: Attempt to fix GLIBC errors by using older runners.

crates/core/config/src/validators.rs, crates/core/config/tests/global_tasks_test.rs, crates/core/config/tests/local_project_test.rs, crates/core/config/tests/tasks_test.rs, crates/core/config/tests/workspace_test.rs, crates/core/utils/src/regex.rs, packages/cli/CHANGELOG.md, website/blog/2023-02-27_v0.25.mdx, website/docs/concepts/project.mdx, website/docs/concepts/task.mdx
=> new: Support periods (`.`) in identifiers.

Cargo.lock, crates/core/launchpad/Cargo.toml, crates/core/launchpad/src/lib.rs, crates/core/utils/src/fs.rs, crates/core/utils/src/lib.rs
Relying on IP's for usage stats isn't very reliable, so let's generate a UUID for each user.
=> internal: Generate a UUID for anonymous users.

.moon/workspace.yml, crates/cli/src/commands/ci.rs, crates/cli/src/commands/docker/scaffold.rs, crates/cli/src/queries/touched_files.rs, crates/cli/tests/snapshots/run_test__outputs__hydration__reuses_cache_from_previous_run-2.snap, crates/core/action-pipeline/src/subscribers/moonbase.rs, crates/core/archive/src/tar.rs, crates/core/archive/src/tree_differ.rs, crates/core/dep-graph/Cargo.toml, crates/core/dep-graph/src/dep_builder.rs, crates/core/dep-graph/tests/dep_graph_test.rs, crates/core/launchpad/src/lib.rs, crates/core/moon/src/lib.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/projects_test.rs, crates/core/project-graph/tests/token_resolver_test.rs, crates/core/project/src/project.rs, crates/core/runner/src/runner.rs, crates/core/task/src/task.rs, crates/core/task/tests/task_test.rs, crates/core/test-utils/src/sandbox.rs, crates/core/utils/src/glob.rs, crates/core/workspace/src/workspace.rs, packages/cli/CHANGELOG.md
Up until now, our glob matching would use and work on absolute paths. This is non-trivial, especially for Windows machines that include a drive prefix, and globs do not understand that.
It also over-complicated pieces, as the VCS is always workspace relative, and we had to constantly re-join paths to be either relative or absolute. Instead, this moves all globs and touched files to workspace relative. In a future PR, we may move input/output paths to relative too.
=> internal: Refactor globs to not be absolute.

.moon/workspace.yml, crates/cli/tests/project_test.rs, crates/cli/tests/query_test.rs, crates/core/project-graph/src/token_resolver.rs, crates/core/project/src/project.rs, crates/core/project/tests/project_test.rs, crates/core/task/src/file_group.rs, crates/core/utils/src/path.rs
While working on https://github.com/moonrepo/moon/pull/649 I noticed that Windows path use both / and \, resulting in patterns not matching, and duplicate paths. This attempts to normalize them.
=> internal: Normalize path related settings on Windows.

crates/core/project-graph/src/graph_hasher.rs, crates/core/project-graph/src/project_builder.rs, packages/cli/CHANGELOG.md
I encountered something weird yesterday. I was using 0.25 and noticed affected logic was not working _at all_. After digging into it, the project graph cache data was _wrong_, as all globs were using the 0.24 format, and not the new 0.25 format.
This makes sense because globs were an internal Rust change, and would not trigger a hash change, as the hash sources are based on file system contents. As such, the cache is not invalidated, putting the app in a weird state.
I'm not entirely sure how to fix this problem, or if there's a way to fix it, so for now, I'm including the moon release version in the hash contents, so that it it's invalidated with each release.
=> fix: Fix project graph cache invalidation between moon releases.

.yarn/versions/04bbcb16.yml, crates/cli/tests/run_test.rs, crates/cli/tests/snapshots/run_test__dependencies__changes_primary_hash_if_deps_hash_changes.snap, crates/cli/tests/snapshots/run_test__dependencies__generates_unique_hashes_for_each_target.snap, crates/cli/tests/snapshots/run_test__output_styles__hash.snap, crates/core/action-pipeline/src/subscribers/local_cache.rs, crates/core/cache/src/items/run_target_state.rs, crates/core/runner/src/target_hasher.rs, packages/cli/CHANGELOG.md, tests/fixtures/cases/outputs/generate.js, tests/fixtures/cases/outputs/moon.yml
Embarrassing, but tarballs were completely excluding workspace relative outputs. This was an oversight on my part.
Note to self: I should change paths to a Rust enum so that I properly handle all variations.
=> fix: Fix workspace relative `outputs` not being included in tarballs.

crates/cli/src/lib.rs, crates/core/launchpad/src/lib.rs, packages/cli/CHANGELOG.md
This is causing too much delay at the end of each CLI run.
=> fix: Move version check back into a thread.

crates/cli/src/commands/upgrade.rs, crates/cli/src/lib.rs, crates/core/launchpad/src/lib.rs, packages/cli/CHANGELOG.md
Actually fixes 2 things:
- We never write the cache if the same version (oops). This causes the request to always fire.
- The upgrade command would hit the stale cache.
=> fix: Fix version check inconsistencies.

Cargo.lock, Cargo.toml, crates/cli/tests/snapshots/run_node_test__handles_process_exit_code_nonzero.snap, crates/cli/tests/snapshots/run_node_test__handles_process_exit_nonzero.snap, crates/cli/tests/snapshots/run_node_test__handles_unhandled_promise.snap, crates/cli/tests/snapshots/run_test__output_styles__buffer_on_failure_when_failure.snap, crates/core/config/Cargo.toml, crates/core/config/src/toolchain/config.rs, crates/core/config/tests/toolchain_test.rs, crates/core/workspace/Cargo.toml, crates/core/workspace/src/workspace.rs, crates/core/workspace/tests/workspace_test.rs, crates/node/tool/src/node_tool.rs, packages/cli/CHANGELOG.md, website/blog/2023-03-13_v0.26.mdx, website/docs/config/toolchain.mdx, website/docs/guides/javascript/deno-handbook.mdx, website/docs/guides/javascript/node-handbook.mdx, website/docs/proto/config.mdx, website/docs/proto/index.mdx, website/docs/proto/install.mdx, website/src/components/Products/Proto/HeroTerminal.tsx, website/src/pages/proto.tsx, website/static/install/proto.ps1, website/static/install/proto.sh, website/static/schemas/project.json, website/static/schemas/toolchain.json
When this config file is found, it'll enable the tools in the toolchain, and inject the versions.
=> new: Integrate `.prototools` and support Windows for proto.

.yarn/versions/bd3ba277.yml, packages/visualizer/package.json, scripts/release/buildPackages.sh
Looks like dist folder is missing upstream: https://unpkg.com/browse/@moonrepo/visualizer@0.1.2/
After we migrated to packemon, we forgot to build the visualizer with vite.
=> fix: Fix missing visualizer assets.

crates/core/action-pipeline/src/actions/run_target.rs, crates/core/runner/src/errors.rs, crates/core/runner/src/runner.rs, crates/core/runner/src/target_hasher.rs, packages/cli/CHANGELOG.md
An empty hash typically means something has gone wrong, and we should bubble this up to the user instead of silently continuing.
=> new: Fail when a task generates or references an empty/missing hash.

crates/cli/tests/run_test.rs, crates/core/dep-graph/src/dep_builder.rs, crates/core/test-utils/src/configs.rs, packages/cli/CHANGELOG.md, tests/fixtures/cases/affected/affected.js, tests/fixtures/cases/affected/moon.yml
If A depends on B, and A is affected (via `--affected`), we should always run B. However, we were only running B if it was also affected, triggering an invalid state.
=> fix: Fix dependencies of affected targets not being ran.

Cargo.lock, crates/cli/src/commands/init/node.rs, crates/core/project-graph/Cargo.toml, crates/core/project-graph/src/helpers.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/project_graph_test.rs, crates/core/runner/src/inputs_collector.rs, crates/core/vcs/src/git.rs, crates/core/vcs/src/lib.rs, crates/core/vcs/src/loader.rs, crates/core/vcs/src/svn.rs, crates/core/vcs/src/vcs.rs, crates/core/workspace/src/workspace.rs, packages/cli/CHANGELOG.md, website/blog/2023-03-13_v0.26.mdx
Because git leaves ignored artifacts around when switching branches, there's a possibility of these ignored paths being considered a project source while globbing, causing issues.
This simply filters out any ignored paths while globbing for projects.
=> fix: Filter out gitignored projects while globbing.

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/commands/query.rs, crates/cli/src/lib.rs, crates/cli/src/queries/hash_diff.rs, crates/cli/src/queries/mod.rs, crates/cli/tests/query_test.rs, crates/cli/tests/snapshots/query_test__hash_diff__prints_a_diff.snap, crates/cli/tests/snapshots/query_test__hash_diff__prints_a_diff_in_json.snap, packages/cli/CHANGELOG.md, website/blog/_2023-03-13_v0.26.mdx, website/docs/commands/query/hash-diff.mdx, website/sidebars.js
This command provides a way for users to debug hashes generated from running tasks, especially when comparing across runs.
=> new: Add `moon query hash-diff` command.

Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/app.rs, crates/cli/src/commands/query.rs, crates/cli/src/lib.rs, crates/cli/src/queries/hash.rs, crates/cli/src/queries/hash_diff.rs, crates/cli/src/queries/mod.rs, crates/cli/tests/query_test.rs, crates/cli/tests/snapshots/query_test__hash__prints_the_manifest.snap, crates/cli/tests/snapshots/query_test__hash__prints_the_manifest_in_json.snap, crates/core/action-context/Cargo.toml, packages/cli/CHANGELOG.md, website/blog/2023-02-27_v0.25.mdx, website/blog/_2023-03-13_v0.26.mdx, website/docs/commands/query/hash-diff.mdx, website/docs/commands/query/hash.mdx, website/sidebars.js
Users can use this command to inspect the hash manifest of a ran task.
=> new: Add `moon query hash` command.

Cargo.lock, crates/cli/src/commands/docker/scaffold.rs, crates/core/archive/src/errors.rs, crates/core/error/Cargo.toml, crates/core/error/src/lib.rs, crates/core/project-graph/src/errors.rs, crates/core/runner/src/errors.rs, crates/core/task/src/errors.rs, crates/core/utils/src/glob.rs, crates/core/workspace/src/errors.rs, packages/cli/CHANGELOG.md
Right now when a glob fails to parse, the error is extremely unhelpful as it doesn't include the pattern that failed. This tries to rectify it.
=> internal: Improve glob error handling.

Cargo.lock, crates/cli/tests/bin_test.rs, crates/core/config/Cargo.toml, crates/core/config/src/helpers.rs, crates/core/config/src/project/config.rs, crates/core/config/src/tasks/config.rs, crates/core/config/src/template/config.rs, crates/core/config/src/toolchain/config.rs, crates/core/config/src/workspace/config.rs, crates/core/config/tests/toolchain_test.rs, crates/core/config/tests/workspace_test.rs, packages/cli/CHANGELOG.md, website/static/schemas/project.json, website/static/schemas/tasks.json, website/static/schemas/template.json, website/static/schemas/toolchain.json, website/static/schemas/workspace.json
This will only log unknown root-level fields. We have no easy way to dig into nested fields.
=> new: Warn on unknown config fields.

.yarn/versions/ee8bc2a6.yml, crates/cli/tests/bin_test.rs, crates/cli/tests/run_test.rs, crates/core/action-pipeline/src/actions/run_target.rs, crates/core/runner/src/errors.rs, crates/core/runner/src/target_hasher.rs, crates/core/utils/src/glob.rs, crates/node/platform/src/platform.rs, packages/cli/CHANGELOG.md, tests/fixtures/cases/depends-on/moon.yml
An edge case I forgot to account for. To solve this, and other future cases, we are now setting the hash at the beginning of the run.
=> fix: Fix tasks with `cache` disabled being considered an empty hash.

crates/cli/tests/snapshots/dep_graph_test__includes_dependents_when_focused.snap, crates/cli/tests/snapshots/project_graph_test__aliases__uses_ids_in_graph.snap, crates/cli/tests/snapshots/project_graph_test__many_projects.snap, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/project_graph_test.rs, packages/cli/CHANGELOG.md, tests/fixtures/project-graph/cycle/a/moon.yml, tests/fixtures/project-graph/cycle/b/moon.yml, tests/fixtures/project-graph/cycle/package.json, website/docs/config/workspace.mdx
This is simply a hack for the project graph to be created when it encounters a cycle. It achieves this by decoupling the leaf node from it's previous node, instead of depending on it. 
While this works, it also means that the task graph is no longer accurate, and may not build things in the correct order.
=> fix: Fix project graph generation crashing on circular dependencies.

crates/core/runner/src/inputs_collector.rs, packages/cli/CHANGELOG.md
Only applies to literal file paths, not globs, and helps to bubble up misconfigurations.
=> new: Warn when an input doesn't exist while hashing.

crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/project_graph_test.rs, crates/node/lang/src/pnpm/dependency_path.rs, packages/cli/CHANGELOG.md
The project config paths were missing from the hash manifest when running in a sub-directory, causing weird issues.
This updates them to be absolute instead of use cwd.
=> fix: Fix project graph cache when running from a sub-dir.

.yarn/versions/4745cdf3.yml, crates/core/config/src/project/language_platform.rs, packages/cli/CHANGELOG.md
They were being serialized as `{"other":"lang"}` instead of simply `"lang"`. This would cause issues during deserialization.
=> fix: Fix serialization of custom languages.

.yarn/versions/25d43247.yml, crates/cli/src/commands/docker/scaffold.rs, crates/cli/tests/docker_test.rs, packages/cli/CHANGELOG.md
I ran into this myself. Looks like Docker scaffolding was completely ignoring configs in `.moon/tasks/*.yml`, causing tasks to be no-ops.
=> fix: Fix Docker scaffolding not including tasks configs.

crates/cli/tests/dep_graph_test.rs, crates/core/config/src/project/task_options.rs, crates/core/config/tests/tasks_test.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/projects_test.rs, packages/cli/CHANGELOG.md, tests/fixtures/tasks/.env, tests/fixtures/tasks/expand-env/moon.yml, website/docs/config/project.mdx
This PR does 2 things:
- Logs a warning instead of triggering an error.
- Supports workspace relative paths.
Fixes: https://github.com/moonrepo/moon/issues/748
=> fix: Improve `envFile` implementation and ergonomics.

.yarn/versions/3e50ed09.yml, crates/core/moon/src/lib.rs, crates/core/workspace/src/errors.rs, crates/core/workspace/src/workspace.rs, packages/cli/CHANGELOG.md
Fixes https://github.com/moonrepo/moon/issues/757
So this only happened for `moon run/check`, which lead me to believe that it was the telemetry logic, and I was right. When the workspace is found, we mark the telemetry atomic as ready, but when it's not found we never set it to ready, causing an atomic deadlock and it hangs.
=> fix: Fix moon hanging when running outside of workspace root.

Cargo.lock, crates/core/action-pipeline/Cargo.toml, crates/core/action-pipeline/src/pipeline.rs, packages/cli/CHANGELOG.md
`rusty_pool` has far too much overhead, so let's try a semaphore.
=> internal: Switch to a semaphore.

crates/cli/src/commands/run.rs, crates/core/action-context/src/lib.rs, crates/core/action-pipeline/src/actions/run_target.rs, crates/core/action-pipeline/src/actions/sync_project.rs, crates/core/runner/src/runner.rs, crates/core/runner/src/target_hasher.rs, packages/cli/CHANGELOG.md
I've noticed and the community has noticed that watcher-type tasks that should run in parallel sometimes don't. Only 1 of the tasks runs, while the others never start. 
It turns out that the context rwlock was forever waiting to acquire a lock for the subsequent tasks.
=> fix: Fix concurrent task running problems.

crates/cli/src/commands/upgrade.rs, crates/cli/src/helpers.rs, crates/core/launchpad/src/lib.rs, packages/cli/CHANGELOG.md
This allows us to provide more context for what's available in the release. Especially when hotfixes are concerned.
=> new: Support optional messages when new versions are available.

crates/core/tool/src/errors.rs, crates/node/platform/src/actions/run_target.rs, crates/node/platform/src/task.rs, packages/cli/CHANGELOG.md, website/blog/2023-04-03_moon-v1.1.mdx, website/docs/config/project.mdx
Our task inference creates tasks with commands like `moon run-script build`, which work when the repo has `moon` installed as a node_module with `@moonrepo/cli`. If they do not have it installed, and use a global moon binary, all of these commands will fail.
To work around this, if a local moon binary is not found, we'll just fallback to the global one.
=> new: Better handling of Node.js tasks that call `moon`.

.yarn/versions/40bb9d89.yml, Cargo.lock, crates/cli/src/commands/project.rs, crates/core/project-graph/tests/projects_test.rs, crates/core/task/Cargo.toml, crates/core/task/src/file_group.rs, crates/core/task/tests/file_group_test.rs, packages/cli/CHANGELOG.md
If a project defines a file group that's inherited by 50 tasks, _each_ task would walk the file system, causing massive performance issues. This adds caching to solve the problem.
Fixes https://github.com/moonrepo/moon/issues/771
=> fix: Cache file group walking.

.github/workflows/benchmark.yml, .github/workflows/moon.yml, .github/workflows/release.yml, .github/workflows/rust.yml, rust-toolchain.toml
=> ci: Migrate to `moonrepo/setup-rust` action.

Cargo.lock, crates/core/config/src/project/config.rs, crates/core/config/src/project/language_platform.rs, crates/core/config/src/project/task.rs, crates/core/query/Cargo.toml, crates/core/query/src/builder.rs, crates/core/query/src/errors.rs, crates/core/query/src/lib.rs, crates/core/query/src/mql.pest, crates/core/query/src/parser.rs, crates/core/query/tests/builder_test.rs, crates/core/query/tests/parser_test.rs, crates/core/task/src/task.rs, packages/cli/CHANGELOG.md, website/docs/concepts/query-lang.mdx, website/docs/concepts/token.mdx, website/sidebars.js
This PR adds a new feature that I'm calling MQL, that allows for advanced searching/filtering/etc through an SQL-like syntax. This is a much better approach instead of supporting ad-hoc CLI args everywhere. For example:
```
moon run "projectType=library && task=build && language=javascript"
```
To do:
Fields:
Operators:
=> new: Implement a moon query language (MQL).

Cargo.lock, crates/core/archive/src/tar.rs, crates/core/cache/Cargo.toml, crates/core/cache/src/items/run_target_state.rs
We've received a few reports that hydration (tar unpacking) often results in partially hydrated output, causing a lot of issues. I've scoured our tar implementation and the tar crates themselves, but haven't found anything.
My only thought right now is that the thread is being interrupted while unpacking, resulting in a broken state. This tries to move the unpacking to a separate background thread that wouldn't be aborted.
=> fix: Unpack archives in a separate thread.

.yarn/versions/c9305e0b.yml, crates/cli/src/commands/project.rs, crates/cli/src/queries/projects.rs, crates/cli/tests/migrate_test.rs, crates/cli/tests/snapshots/project_test__root_level.snap, crates/core/config/src/toolchain/node.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/src/token_resolver.rs, crates/core/project-graph/tests/token_resolver_test.rs, crates/core/project/src/project.rs, crates/core/test-utils/src/configs.rs, crates/node/platform/src/platform.rs, crates/node/platform/tests/project_aliases_test.rs, packages/cli/CHANGELOG.md, packages/types/src/project.ts, website/docs/__partials__/create-project/node/aliases.mdx, website/docs/commands/migrate/from-turborepo.mdx, website/docs/concepts/query-lang.mdx, website/docs/concepts/token.mdx, website/docs/config/toolchain.mdx, website/docs/create-project.mdx, website/docs/guides/javascript/node-handbook.mdx
We don't really need this setting anymore. It also makes Node.js adoption harder.
=> new: Deprecate `node.aliasPackageNames` setting.

crates/core/task/src/task.rs, packages/cli/CHANGELOG.md, website/docs/concepts/task.mdx
If `runInCI` was false, it would set a task to `run` and not be found during `moon check`, which is incorrect.
=> fix: Fix task type detection.

crates/cli/src/commands/docker/scaffold.rs, crates/cli/tests/bin_test.rs, crates/cli/tests/check_test.rs, crates/cli/tests/dep_graph_test.rs, crates/cli/tests/docker_test.rs, crates/cli/tests/migrate_test.rs, crates/cli/tests/misc_test.rs, crates/cli/tests/node_test.rs, crates/cli/tests/project_graph_test.rs, crates/cli/tests/project_test.rs, crates/cli/tests/query_test.rs, crates/cli/tests/run_node_test.rs, crates/cli/tests/run_rust_test.rs, crates/cli/tests/run_system_test.rs, crates/cli/tests/run_test.rs, crates/cli/tests/run_typescript_test.rs, crates/cli/tests/run_webhooks_test.rs, crates/cli/tests/setup_teardown_test.rs, crates/cli/tests/sync_test.rs, crates/cli/tests/task_test.rs, crates/core/action-pipeline/benches/pipeline_benchmark.rs, crates/core/dep-graph/benches/dep_graph_benchmark.rs, crates/core/dep-graph/tests/dep_graph_test.rs, crates/core/project-graph/benches/project_graph_benchmark.rs, crates/core/project-graph/tests/project_graph_test.rs, crates/core/project-graph/tests/projects_test.rs, crates/core/runner/tests/inputs_collector_test.rs, crates/core/test-utils/src/sandbox.rs, crates/node/platform/tests/project_aliases_test.rs, crates/typescript/platform/tests/sync_project_test.rs
It's not necessary and was constantly causing rust-analyzer issues.
=> tests: Remove reference from sandbox API.

.moon/toolchain.yml, .moon/workspace.yml, crates/cli/tests/snapshots/run_rust_test__handles_process_exit_nonzero.snap, crates/cli/tests/snapshots/run_rust_test__handles_process_exit_zero.snap, crates/cli/tests/snapshots/run_rust_test__inherits_moon_env_vars.snap, crates/cli/tests/snapshots/run_rust_test__runs_from_project_root.snap, crates/cli/tests/snapshots/run_rust_test__runs_from_workspace_root.snap, crates/cli/tests/snapshots/run_rust_test__runs_standard_script.snap, crates/cli/tests/snapshots/run_rust_test__sets_env_vars.snap, crates/core/config/src/toolchain/rust.rs, crates/rust/platform/src/bins_hasher.rs, crates/rust/platform/src/lib.rs, crates/rust/platform/src/rust_platform.rs, crates/rust/platform/tests/rust_platform_test.rs, crates/rust/tool/src/rust_tool.rs, packages/types/src/toolchain-config.ts, website/docs/config/toolchain.mdx
This will install Cargo binaries with `cargo-binstall` so that they're available for tasks.
=> new: Add `rust.cargoBins` setting.

crates/cli/src/commands/init/mod.rs, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__rust__tests__renders_default.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_default.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_git_vcs.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_glob_list.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_projects_map.snap, crates/cli/src/commands/init/snapshots/moon_cli__commands__init__tests__renders_svn_vcs.snap, crates/cli/tests/init_test.rs, crates/core/config/templates/project.yml, crates/core/config/templates/tasks.yml, crates/core/config/templates/toolchain_rust.yml, crates/core/config/templates/workspace.yml, packages/cli/CHANGELOG.md, website/static/schemas/toolchain.json
Some of these were too noisy, or had outdated info.
=> internal: Clean up `moon init` templates.

.yarn/versions/5135b648.yml, crates/cli/src/commands/task.rs, crates/core/task/src/task.rs, packages/cli/CHANGELOG.md
Broke this when reworking the task type detection.
=> fix: Fix tasks running in CI when they shouldn't.

crates/core/platform-detector/src/task_platform.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/project_graph_test.rs, crates/core/project-graph/tests/projects_test.rs, crates/core/runner/src/runner.rs, packages/cli/CHANGELOG.md
When creating tasks, we attempt to detect the platform it should run in. For example, `cargo` commands should use the `rust` platform. This works perfectly, however... If the Rust platform has not been enabled in `.moon/toolchain.yml`, it triggers an error, an error that is confusing to consumers.
This updates detection to also check against the config.
=> fix: Update platform detection to infer based on toolchain settings.

website/docs/proto/plugins.mdx
The proto plugin docs have an example that reads:
```toml
[resolve]
git-url = "https://github.com/moonrepo/protostar"
git-tag-pattern = "^@protostar/cli@((\d+)\.(\d+)\.(\d+))"
```
But lint and proto cli complains:
```shell
× Failed to parse TOML file ~/Projects/skipa/www.skipa.io/./proto-dprint.toml
╰─▶ TOML parse error at line 26, column 37
|
26 | git-tag-pattern = "^@dprint/cli@((\d+)\.(\d+)\.(\d+)"
|                                     ^
invalid escape sequence
expected `b`, `f`, `n`, `r`, `t`, `u`, `U`, `\`, `"`      
```
This minor change escapes the digits with `\\d`
=> docs: correct escape sequence in proto plugin example

crates/core/archive/src/tree_differ.rs, packages/cli/CHANGELOG.md
Context: https://github.com/moonrepo/moon/issues/735#issuecomment-1572819680
The problem is that gzip doesn't support file seeking, so we can't reset the pointer. I'm just commenting out this code for now.
=> fix: Fix partial hydration issues.

.moon/toolchain.yml, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/commands/init/rust.rs, crates/cli/src/commands/query.rs, crates/cli/src/queries/projects.rs, crates/core/action-pipeline/src/pipeline.rs, packages/cli/CHANGELOG.md, rust-toolchain.toml
https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html
Not much for us to change.
=> deps: Upgrade to Rust v1.70.

.yarn/versions/fdaa96bc.yml, crates/rust/platform/src/rust_platform.rs, packages/cli/CHANGELOG.md
moon requires a Rust project to be the root of a Cargo workspace, but this platform method was causing it to be anywhere, resulting in the wrong working directory.
=> fix: Fix Cargo running in the wrong directory.

.yarn/versions/b8f025bc.yml, nextgen/config/src/project/mod.rs, nextgen/config/src/project/owners_config.rs, nextgen/config/src/project_config.rs, nextgen/config/tests/project_config_test.rs, packages/cli/CHANGELOG.md, packages/types/src/project-config.ts, website/docs/config/project.mdx
This is the first step in support code owners.
=> new: Add `owners` setting to `moon.yml`.

Cargo.lock, Cargo.toml, crates/cli/src/commands/query.rs, crates/cli/src/commands/task.rs, crates/cli/src/queries/projects.rs, crates/cli/src/queries/touched_files.rs, crates/core/action-context/Cargo.toml, crates/core/action-context/src/lib.rs, crates/core/action-pipeline/src/actions/install_deps.rs, crates/core/action-pipeline/src/subscribers/moonbase.rs, crates/core/dep-graph/tests/dep_graph_test.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/src/token_resolver.rs, crates/core/project-graph/tests/projects_test.rs, crates/core/project-graph/tests/token_resolver_test.rs, crates/core/runner/src/inputs_collector.rs, crates/core/runner/src/runner.rs, crates/core/task/src/task.rs, crates/core/task/src/types.rs, crates/core/task/tests/task_test.rs
This crate (https://crates.io/crates/relative-path) solves a bunch of our portability problems.
=> internal: Use `relative-path` for inputs/outputs/touched/etc.

crates/core/runner/src/runner.rs, crates/core/vcs/src/git.rs, crates/core/vcs/src/loader.rs, packages/cli/CHANGELOG.md
This results in broken builds but the problem isn't very noticeable. Everything "looks" like it's working, but caching acts weird. The problem is that the VCS paths are different than the workspace ones (the prefix between the 2 is missing), resulting in path comparisons to fail.
=> fix: Fix issues when VCS root and workspace root are not the same.

Cargo.lock, crates/core/action-pipeline/Cargo.toml, crates/core/action-pipeline/src/pipeline.rs, packages/cli/CHANGELOG.md
Right now, not all running tasks are properly cancelled. Hopefully this fixes the problem.
Based on this article: https://tokio.rs/tokio/topics/shutdown
=> fix: Better handling of ctrl+c signals.

.yarn/versions/0c454339.yml, crates/core/vcs/src/git.rs
When running git <2.22.0 (I had 2.14.1), I get
```
moon run build
Error:   × Process git failed with a 1 exit code.
│ 
│ git: 'rev-parse --abbrev-ref HEAD' is not a git command. See 'git --help'.
```
=> Fix broken get_local_branch when using older git versions

Cargo.lock, Cargo.toml, nextgen/codeowners/src/codeowners_generator.rs, packages/cli/CHANGELOG.md
=> fix: Use `.editorconfig` when writing `CODEOWNERS`.

.github/workflows/rust.yml, crates/cli/tests/run_node_test.rs, crates/core/action-pipeline/src/actions/run_target.rs, crates/node/platform/src/actions/install_deps.rs, crates/node/platform/src/actions/mod.rs, crates/node/platform/src/actions/setup_tool.rs, crates/node/platform/src/platform.rs, packages/cli/CHANGELOG.md
This sync logic shouldn't require installing node modules, so makes more sense as part of setup tool.
=> internal: Move Node.js syncing logic.

website/docs/guides/examples/angular.mdx, website/sidebars.js
Add an example of how to integrate an Angular application in a Moon repository.
Linked [Pull Requests](https://github.com/moonrepo/examples/pull/64) on [moonrepo/examples](https://github.com/moonrepo/examples)
=> docs: Add example on Angular

crates/deno/platform/src/bins_hasher.rs, crates/deno/platform/src/lib.rs, crates/deno/platform/src/platform.rs, crates/rust/platform/src/bins_hasher.rs, crates/rust/platform/src/rust_platform.rs, nextgen/config/src/main.rs, nextgen/config/src/toolchain/bin_config.rs, nextgen/config/src/toolchain/deno_config.rs, nextgen/config/src/toolchain/mod.rs, nextgen/config/src/toolchain/node_config.rs, nextgen/config/src/toolchain/rust_config.rs, nextgen/config/src/toolchain/typescript_config.rs, nextgen/config/tests/toolchain_config_test.rs, packages/cli/CHANGELOG.md, packages/types/src/toolchain-config.ts, website/docs/config/toolchain.mdx, website/static/schemas/toolchain.json
This adds an object form for `rust.bins` and also adds `deno.bins` support.
=> new: Support an object for `bins`. Add Deno support.

.moon/workspace.yml, crates/cli/tests/run_test.rs, crates/cli/tests/snapshots/run_test__dependencies__changes_primary_hash_if_deps_hash_changes.snap, crates/cli/tests/snapshots/run_test__dependencies__generates_unique_hashes_for_each_target.snap, crates/core/action-context/src/lib.rs, crates/core/action-pipeline/src/actions/run_target.rs, crates/core/action-pipeline/src/pipeline.rs, crates/core/project-graph/src/errors.rs, crates/core/project-graph/src/project_builder.rs, crates/core/project-graph/tests/projects_test.rs, crates/core/runner/src/runner.rs, crates/core/runner/src/target_hasher.rs, crates/core/runner/tests/inputs_collector_test.rs, crates/core/test-utils/src/cli.rs, packages/cli/CHANGELOG.md, packages/report/tests/report.test.ts, packages/types/src/common.ts, packages/types/src/pipeline.ts, tests/fixtures/cases/outputs/generate.js, tests/fixtures/cases/outputs/moon.yml, tests/fixtures/tasks/tokens/moon.yml
This fixes a few edge cases:
- Tasks writing to the same output location is no longer allowed.
- Task shouldn't run if one of it's deps failed.
=> new: Implement stricter dep/project graph rules.

.yarn/versions/ae826143.yml, crates/cli/tests/misc_test.rs, crates/core/project-graph/src/helpers.rs, nextgen/vcs/src/git.rs, nextgen/vcs/src/vcs.rs, packages/cli/CHANGELOG.md
Fixes https://github.com/moonrepo/moon/issues/966
Looks like `--stdin-paths` requires paths from the git root, and not relative from the working directory.
=> fix: Fix git hashing from sub-directories.

crates/cli/tests/run_rust_test.rs
Adds support for the new default panic handler message format landing in rust 1.73. rust-lang/rust#112849
=> fix: support new panic message format in rust 1.73

Cargo.lock, Cargo.toml, crates/cli/tests/snapshots/generate_test__supports_custom_filters.snap, crates/core/runner/tests/inputs_collector_test.rs, nextgen/codegen/Cargo.toml, nextgen/codegen/src/filters.rs, nextgen/common/src/path.rs, nextgen/project-graph/Cargo.toml, nextgen/project-graph/src/project_graph.rs
These are available now in relative-path 1.9.
=> internal: Use new relative path methods.

website/docs/proto/toml-plugin.mdx
The examples for the `git-tag-pattern` for a `proto` toml plugin need some additional escaping. This is a minor update to the docs to escape these correctly.
(Note - although the default pattern shows how it is represented *internally*, it needs the additional escaping to be used in the toml file).
=> docs: Fix escaping on git-tag-pattern examples

.yarn/versions/8dfb2dc3.yml, nextgen/config/src/inherited_tasks_config.rs, packages/cli/CHANGELOG.md
Fixes https://github.com/moonrepo/moon/issues/1077
=> fix: Allow non-yaml files in `.moon/tasks`.

crates/core/moon/src/lib.rs, nextgen/api/src/launchpad.rs, nextgen/vcs-hooks/src/hooks_generator.rs, nextgen/vcs-hooks/tests/snapshots/hooks_generator_test__unix__links_git_hooks-2.snap, nextgen/vcs-hooks/tests/snapshots/hooks_generator_test__unix__links_git_hooks.snap, nextgen/vcs-hooks/tests/snapshots/hooks_generator_test__windows__links_git_hooks-2.snap, nextgen/vcs-hooks/tests/snapshots/hooks_generator_test__windows__links_git_hooks.snap, packages/cli/CHANGELOG.md
Fixes https://github.com/moonrepo/moon/issues/1078
According to https://git-scm.com/docs/githooks the most args a hook can receive is 3, so passing all 3 to every hook. I tested this locally and its fine, they just are undefined.
=> fix: Include args when generating Git hooks.

crates/cli/src/commands/task.rs, crates/core/dep-graph/src/dep_builder.rs, crates/core/runner/src/runner.rs, crates/core/terminal/src/theme.rs, nextgen/project-builder/src/project_builder.rs, nextgen/project-expander/src/tasks_expander.rs, nextgen/project-graph/src/project_graph.rs, nextgen/project-graph/src/project_graph_builder.rs, nextgen/project/src/project.rs, nextgen/task-builder/src/tasks_builder.rs, packages/cli/CHANGELOG.md, website/docs/commands/query/projects.mdx, website/docs/commands/query/tasks.mdx
Fixes https://github.com/moonrepo/moon/issues/1079
=> fix: Fix self-referencing tasks using project aliases.

.yarn/versions/41ec5248.yml, crates/cli/src/commands/check.rs, crates/cli/src/commands/generate.rs, crates/cli/src/commands/graph/dep.rs, crates/cli/src/commands/init/mod.rs, crates/cli/src/commands/run.rs, crates/cli/src/commands/task.rs, crates/cli/tests/dep_graph_test.rs, crates/cli/tests/snapshots/dep_graph_test__focused_by_task_in_cwd.snap, crates/core/action-context/src/lib.rs, crates/core/action-pipeline/src/processor.rs, crates/core/dep-graph/src/dep_builder.rs, crates/core/moon/src/lib.rs, crates/core/runner/src/runner.rs, nextgen/process/src/command_inspector.rs, nextgen/project-graph/src/project_graph.rs, nextgen/project-graph/src/project_graph_builder.rs, nextgen/project-graph/tests/project_graph_test.rs, nextgen/target/src/lib.rs, nextgen/target/src/target.rs, nextgen/target/src/target_locator.rs, nextgen/target/tests/target_test.rs, nextgen/task/src/task.rs, packages/cli/CHANGELOG.md
Fixes https://github.com/moonrepo/moon/issues/1076
=> new: Update `moon dep-graph` to support task by path.

nextgen/config/src/inherited_tasks_config.rs, nextgen/config/src/project_config.rs, nextgen/config/tests/project_config_test.rs, nextgen/task-builder/src/lib.rs, nextgen/task-builder/src/tasks_builder.rs, nextgen/task-builder/src/tasks_builder_error.rs, nextgen/task-builder/tests/__fixtures__/builder/extends-unknown/moon.yml, nextgen/task-builder/tests/__fixtures__/builder/extends/moon.yml, nextgen/task-builder/tests/tasks_builder_test.rs, packages/cli/CHANGELOG.md
Our docs said this was possible but looks like I never finished the implementation.
=> fix: Allow local tasks to extend global tasks.

nextgen/codegen/src/filters.rs, packages/cli/CHANGELOG.md
The casing functions would remove chars like `-` since it tries to convert it. This is unexpected.
=> fix: Fix upper/lower case for codegen.

Cargo.lock, Cargo.toml, crates/cli/src/commands/docker/scaffold.rs, crates/cli/tests/docker_test.rs, packages/cli/CHANGELOG.md
Noticed `moon docker scaffold` was copying stuff like node modules. That's not good.
=> fix: Fix docker scaffolding greediness.

.yarn/versions/5f1de95c.yml, crates/node/platform/src/actions/sync_project.rs, nextgen/config/src/project/dep_config.rs, nextgen/project-builder/src/project_builder.rs, nextgen/project-builder/tests/project_builder_test.rs, nextgen/project-graph/src/project_graph_builder.rs, nextgen/project-graph/tests/__fixtures__/dependency-types/from-root-task-deps/moon.yml, nextgen/project-graph/tests/__fixtures__/dependency-types/moon.yml, nextgen/project-graph/tests/project_graph_test.rs, nextgen/project/src/project.rs, nextgen/test-utils/src/project_graph.rs, packages/cli/CHANGELOG.md
This is causing more problems than it solves, so adding an exception for the root project.
=> fix: Don't auto-link dependency when a root-level project.

crates/core/action-pipeline/src/actions/run_task.rs, crates/core/action-pipeline/src/estimator.rs, crates/core/action-pipeline/src/pipeline.rs, crates/core/action-pipeline/src/processor.rs, crates/core/action-pipeline/tests/estimator_test.rs, crates/core/action/src/action.rs, crates/core/runner/src/runner.rs, nextgen/action-graph/src/action_node.rs, packages/cli/CHANGELOG.md
When we would `take()` it, there's a small window where the node information is unavailable, causing some weirdness. This uses an `Arc` so it's always present.
=> fix: Ensure action node is always present.

.yarn/versions/4c6095cd.yml, crates/node/tool/src/pnpm_tool.rs, packages/cli/CHANGELOG.md
It runs the npx version when using a non-fq version, which isn't correct.
=> fix: Fix pnpm deduping.

website/src/data/proto-tools.tsx
Adds the following TOML plugins:
* buf - Protocol Buffers
* gojq - Go implementation of jq
* helm - Kubernetes package manager
* helmfile - Deploy kubernetes helm charts
* kubectl - Kubernetes CLI
* sops - Secrets operations
* terragrunt - Terraform wrapper
* zig - Zig language and toolchain
=> Add third-party plugins

website/docs/guides/examples/eslint.mdx
The additional space causes an error in the task execution:
```
× Failed to parse .moon/tasks/node.yml.
╰─▶   × tasks.lint.?: did not find expected key at line 6 column 7, while parsing a block mapping at line 3 column 5
╭─[5:1]
5 │       # Support other extensions
6 │       - '--ext'
·       ▲
·       ╰── Fix this
7 │       - '.js,.jsx,.ts,.tsx'
╰────
```
=> docs: fix indentation in eslint example

website/src/data/proto-tools.tsx
Hi.
I created a wasm plugin for Zig!
It supports installing zig [master builds](https://ziglang.org/download/) as well as release builds.
=> docs: Add zig-plugin for proto.

.yarn/versions/baeeda33.yml, packages/cli/postinstall.js
Fixes problem when installing via Bun package manager.
Bun runs its package manager process with the correct process.arch var. This env var influences Moon's arch-specific core dependency.
Bun runs postinstall processes however via node. Node does not have, or does not have set, the same process.arch which results in the postinstall process resolving the wrong core dependency
Bun thankfully sets a useful value at process.npm_config_user_agent which allows a safe edge case solution here
=> Force arch when running in a bun postinstall process

nextgen/vcs/src/git.rs, nextgen/vcs/tests/git_test.rs
VFSForGit has the version '2.43.0.vfs.0.0', which has raised issue #1281. 
The proposed fix includes a rewritten regex and an added assert.
=> fix:Fix version cleaning for VFSForGit windows (#1281).

.yarn/versions/0957d65a.yml, crates/cli/src/commands/docker/scaffold.rs, crates/cli/tests/docker_test.rs, packages/cli/CHANGELOG.md
Oversight? Previously this worked fine, since this config is just for tasks, which aren't important for the scaffolding process.
However, now that we support `id`, this causes a failure for unknown projects.
=> fix: Fix docker scaffold not copying `moon.yml`.

crates/core/action-pipeline/src/pipeline.rs, packages/cli/CHANGELOG.md
Otherwise, if you had more tasks than CPU count, some of them will never start. This is intended for the task runner, but for persistent tasks which are the last tasks to run, it's a blocker.
=> fix: Remove concurrency limit from persistent tasks.

CONTRIBUTING.md
When creating #1290 I needed to figure out what Just was and how to install it, so thought this might be helpful for future contributors
=> chore: add missing instructions for Just to CONTRIBUTING.md

website/docs/intro.mdx
👋 Hopefully this is not so minor to be a nuisance. Saw a couple of things that could be cleaned up on the introduction page in the docs.
Had an extra word and a missing "ly."
=> docs: Fix typos in intro.mdx (#1)

crates/cli/src/commands/docker/prune.rs, crates/cli/src/commands/project.rs, crates/cli/tests/snapshots/project_test__advanced_config.snap, crates/cli/tests/snapshots/project_test__basic_config.snap, crates/cli/tests/snapshots/project_test__depends_on_paths.snap, crates/cli/tests/snapshots/project_test__root_level.snap, crates/cli/tests/snapshots/project_test__with_tasks.snap, crates/cli/tests/snapshots/run_bun_test__bun__infer_tasks__inherits_tasks.snap, nextgen/config/src/language_platform.rs, nextgen/config/src/toolchain_config.rs, nextgen/platform-detector/src/lib.rs, nextgen/platform-detector/src/project_language.rs, nextgen/platform-detector/src/project_platform.rs, nextgen/project-builder/src/project_builder.rs, nextgen/project-builder/tests/project_builder_test.rs, packages/cli/CHANGELOG.md
We would always default to node, but this logic works better.
It's still a bit iffy deducing deno/bun/node explicitly though.
=> fix: Fix platform detection for JS/TS projects.

website/src/data/proto-tools.tsx
Hugo has two version/editions thus I provide a plugin for both.
Thanks! Frederik Zorn
=> docs: Add Hugo standard and extended for proto.

website/src/data/proto-tools.tsx
This pull request introduces a new plugin for [Black](https://black.readthedocs.io/en/stable/), a widely-used Python code formatter.
=> docs: Add black plugin

Cargo.lock, Cargo.toml, crates/core/action-context/Cargo.toml, crates/core/action-context/src/lib.rs, crates/core/action-pipeline/src/actions/run_task.rs, nextgen/config/src/project/task_options_config.rs, nextgen/task-builder/src/tasks_builder.rs, nextgen/task/src/task_options.rs, packages/types/src/project.ts, packages/types/src/tasks-config.ts, website/docs/config/project.mdx, website/static/schemas/project.json, website/static/schemas/tasks.json, website/tsconfig.json
This PR introduces a new `mutex` option to task options. This new option is intended to allow telling Moon when two or more tasks can't be executed at the same time.
Example:
```yaml
tasks:
task_a:
command: 'do something'
options:
mutex: 'resource_1'
task_b:
command: 'do something else'
options:
mutex: 'resource_1' # task_a and task_b won't run at the same time
```
Closes #1415 .
=> feat: add mutex option to task configuration

.yarn/versions/41d19279.yml, crates/bun/tool/src/bun_tool.rs, crates/core/runner/src/runner.rs, crates/deno/tool/src/deno_tool.rs, crates/node/tool/src/bun_tool.rs, crates/node/tool/src/node_tool.rs, crates/node/tool/src/npm_tool.rs, crates/node/tool/src/pnpm_tool.rs, crates/node/tool/src/yarn_tool.rs, packages/cli/CHANGELOG.md
This causes `.prototools` to be ignored.
=> fix: Fix proto falling back to any version.

.yarn/versions/18cba9f6.yml, nextgen/vcs-hooks/src/hooks_generator.rs, nextgen/vcs-hooks/tests/hooks_generator_test.rs
These files could create spurious diffs if someone were to open them with an editor that automatically fixes new lines, or when running with something to automatically fix missing new lines, e.g. a pre-commit hook[1]
[1] https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#end-of-file-fixer
=> Fix Git hooks not created with trailing newlines

.yarn/versions/42a4d275.yml, crates/cli/src/commands/init/mod.rs
Currently when you create a new repo it spits out 
This link does not exist. Must have meant https://moonrepo.dev/docs 😄
=> typo: monorepo.dev -> moonrepo.dev

website/src/data/proto-tools.tsx
Adds [Gleam](https://gleam.run/) to the third party tools for Proto
=> docs: Add Gleam to third party tools

.github/workflows/release.yml, nextgen/action/src/operation_meta.rs, packages/cli/CHANGELOG.md, scripts/release/setupNpm.sh
This stopped working at one point...
=> build: Fix canary/nightly scripts.

.github/workflows/release.yml, packages/cli/CHANGELOG.md, scripts/release/buildBinary.sh, scripts/release/planRelease.sh, scripts/release/publishBinaryPackages.sh, scripts/release/setupNpm.sh
This ensures `moon -V` reports the correct thing.
=> build: Update cargo CLI to use nightly/canary versions.

website/docs/comparison.mdx
moon has been already included, so the sentence needed updating.
=> docs: update text about monorepo.tools website

website/docs/proto/config.mdx
Adding npm version config to use `bundled` npm from node instead of other version. 
I've added this configuration near
```toml
[tools.node]
bundled-npm = true
```
Because I think they are related, and using `bundled-npm = true` without `npm = "bundled"` does not make sense.
This was missing in docs and I barely figured out this from [debug-env](https://moonrepo.dev/docs/proto/commands/debug/config) docs, so I am making this change.
=> docs: Updating tools.node bundled-npm configuration docs

.yarn/versions/a679b82f.yml, CHANGELOG.md, Cargo.lock, crates/action-graph/src/action_graph_builder.rs, crates/action-pipeline/src/action_pipeline.rs, crates/action-pipeline/src/job.rs, crates/action/src/action_node.rs, crates/process/src/lib.rs, crates/project-expander/src/tasks_expander.rs, crates/task-runner/Cargo.toml, crates/task-runner/src/command_executor.rs, packages/types/src/pipeline.ts
Moved from the job layer to the command layer.
Fixes https://github.com/moonrepo/moon/issues/1689
=> fix: Fix task timeout not applying to retries.

website/docs/proto/install.mdx
`apt` is only for Ubuntu / Debian.
We need to add a setup instruction for RHEL family.
```bash
docker run -it --rm almalinux # or fedora
dnf install git unzip gzip xz # Note: gzip & xz have already been installed
curl -fsSL https://moonrepo.dev/install/proto.sh | bash # choose Bash→~/.bash_profile
eval `tail -n 2 ~/.bash_profile`
proto install node 22
node --version
```
=> Add how to install requirements in RHEL-based

CHANGELOG.md, crates/affected/src/affected_tracker.rs, crates/affected/tests/__fixtures__/tasks/base/moon.yml, crates/affected/tests/affected_tracker_test.rs, website/docs/guides/root-project.mdx
Fixes https://github.com/moonrepo/moon/issues/1743
=> fix: Fix affected for empty inputs.

.yarn/versions/15d6e39f.yml, crates/app/src/commands/ci.rs
This PR aims to make some small improvements to moon's CI command based on production experience.
(i.e. 10 total jobs, 45 total targets - the last job will have 9 targets instead of 4)
=> fix: Improve CI job handling.

crates/app/src/commands/run.rs, crates/app/src/components.rs, website/docs/commands/run.mdx, website/docs/config/workspace.mdx
The `--eager` flag makes moon run behave more like moon ci.
Fixes #1770
=> new: Add `moon run --eager` to disable fail-fast behavior and execute as many tasks as possible

CHANGELOG.md, crates/action/src/operation.rs, crates/config/src/project/task_options_config.rs, crates/config/tests/inherited_tasks_config_test.rs, crates/task-builder/src/tasks_builder.rs, crates/task-expander/src/expander_utils.rs, crates/task-expander/src/task_expander.rs, crates/task-expander/src/token_expander.rs, crates/task-expander/tests/token_expander_test.rs, crates/task/src/task_options.rs, legacy/bun/platform/src/actions/install_deps.rs, legacy/node/platform/src/actions/install_deps.rs, legacy/python/platform/src/actions/install_deps.rs, packages/types/src/tasks-config.ts, packages/types/src/workspace-config.ts, tests/docker/Dockerfile, tests/docker/Dockerfile.staged, website/docs/config/project.mdx, website/static/schemas/project.json, website/static/schemas/tasks.json
Fixes https://github.com/moonrepo/moon/issues/1587 and https://github.com/moonrepo/moon/issues/1567
=> new: Random improvements.

crates/codegen/src/codegen.rs, crates/codegen/tests/codegen_test.rs, crates/config/src/template/template_locator.rs
This change would allow to work with remote templates in a remote git repository which are hosted on different uri formats rather than github.
For example:
- `my-gitlab.cooperate-domain.com` - which was not working due to `-` in hostname
- `IDENT@my-gitlab.cooperate-domain.com` - which was not working due to `@` (for identity) and upper case letters 
Additional the automatic appending postfix `.git` to the git clone url is removed and is now in the user responsibility to add the correct url.
=> fix: Adapt remote git regex for templates

CHANGELOG.md, crates/config/src/workspace/hasher_config.rs, crates/config/tests/workspace_config_test.rs, crates/process/src/command.rs, crates/process/src/command_line.rs, crates/process/src/exec_command.rs, crates/task-hasher/src/task_hasher.rs, crates/vcs/src/git.rs, crates/vcs/src/vcs.rs, crates/vcs/tests/git_test.rs, crates/workspace/src/workspace_builder.rs, website/docs/config/workspace.mdx
Fixes https://github.com/moonrepo/moon/issues/1855
=> new: Continuously pipe stdin during file hashing.

.yarn/versions/e6803309.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, crates/action-pipeline/src/job.rs, crates/action/src/operation.rs, crates/process/Cargo.toml, crates/process/src/exec_command.rs, crates/process/src/output.rs, crates/process/src/shared_child.rs, crates/task-runner/src/command_executor.rs, crates/vcs/src/process_cache.rs
Currently if we send a SIGINT the child process can exit with code 0, which results in a successful task, and in turn it will be cached. This is actually wrong since it never completed.
=> fix: Always fail interrupted processes.

crates/app/src/commands/check.rs, crates/app/src/commands/run.rs
Added environment variables to control `--summary`, `--no-actions`, `--no-bail`,  and `--affected`. 
Fixes https://github.com/moonrepo/moon/issues/1929
=> new: add environment variables for a few run arguments

.yarn/versions/8992253b.yml, crates/app/src/commands/docker/scaffold.rs
Fix for issue
https://github.com/moonrepo/moon/issues/2008
Currently `moon docker scaffold` command does a dependency graph traversal and copies the relevant files. But doesn't mark the node visited. Because of which same project gets processed twice i.e. copied twice.
We seen cases where this command takes more than 20 mins to run, where a single library gets copied over 105,000+ times. After this fix, the project now takes <30s for `moon docker scaffold` command to complete.
=> Fix: moon docker scaffold performance

crates/action-pipeline/src/action_pipeline.rs, crates/action-pipeline/src/subscribers/webhooks_subscriber.rs, crates/cli/tests/run_webhooks_test.rs, crates/config/src/workspace/notifier_config.rs, crates/config/tests/workspace_config_test.rs, crates/notifier/src/webhooks.rs, website/docs/config/workspace.mdx, website/docs/guides/webhooks.mdx
feat(webhooks): Add acknowledge setting and global trace ID
This commit implements webhook acknowledgment and global trace ID features:
- Add webhookAcknowledge setting in workspace config
- Support MOON_TRACE_ID environment variable
- Update documentation
Closes #1961
=> feat(webhooks) Add acknowledge setting and global trace (2nd attempt)

.yarn/versions/16dcd96a.yml, crates/app/src/commands/setup.rs
To resolve #2074 by reusing the `SetupProto` and `SetupToolchain` actions.
New: 
```sh
moon on  opt/setup-with-new-action [!] via  v24.5.0 via 🦀 v1.88.0 
❯ cargo run --bin moon setup
Finished `dev` profile [unoptimized] target(s) in 0.60s
Running `target/debug/moon setup`
▪▪▪▪ installing proto 0.51.4
▪▪▪▪ installing bun 1.2.2
▪▪▪▪ installing deno 2.1.9
▪▪▪▪ installing python 3.11.10
▪▪▪▪ installing node 22.14.0
▪▪▪▪ installing yarn 4.8.0
Tasks: 0 tasks ran
Time: 28s 961ms ❯❯❯❯ to the moon
│ SUCCESS
│ Successfully setup 5 toolchain(s)!
```
Original with issue:
```sh
moon on  opt/setup-with-new-action [!] via  v24.5.0 via 🦀 v1.88.0 
❯ moon setup
━━━━━━━━╾            Downloading and installing toolchains...
━━━━━━━━━━━━━━━━━━━━ Downloading and installing toolchains...
Error: …
```
=> fix: enhance toolchain setup process and feedback mechanism

website/docs/commands/run.mdx
- Add shorten arg for `summary` 
- Move `--profile` arg to debugging section
=> docs: Align the doc to `moon run --help` cli prompt.

website/docs/config/workspace.mdx
just a fix for a typo in the documentation
=> docs(workspace.mdx): fix typo notfier -> notifier

website/docs/config/toolchain.mdx, website/docs/config/workspace.mdx
See https://astral.sh/blog/python-build-standalone
=> docs: python-build-standalone governance has been passed to Astral-sh
